INFO 2025-06-03 12:28:19,180 autoreload 3092 23084 Watching for file changes with StatReloader
INFO 2025-06-03 12:29:04,495 autoreload 15856 1960 Watching for file changes with StatReloader
WARNING 2025-06-03 12:29:21,601 log 15856 23364 Not Found: /
WARNING 2025-06-03 12:29:21,601 basehttp 15856 23364 "GET / HTTP/1.1" 404 1937
WARNING 2025-06-03 12:29:21,995 log 15856 21484 Not Found: /favicon.ico
WARNING 2025-06-03 12:29:21,995 basehttp 15856 21484 "GET /favicon.ico HTTP/1.1" 404 1835
WARNING 2025-06-03 12:31:01,898 log 15856 1132 Not Found: /login
WARNING 2025-06-03 12:31:01,898 basehttp 15856 1132 "GET /login HTTP/1.1" 404 1823
WARNING 2025-06-03 12:31:05,776 log 15856 13536 Not Found: /accounts
WARNING 2025-06-03 12:31:05,777 basehttp 15856 13536 "GET /accounts HTTP/1.1" 404 1829
WARNING 2025-06-03 12:36:31,020 log 15856 23388 Not Found: /accounts
WARNING 2025-06-03 12:36:31,021 basehttp 15856 23388 "GET /accounts HTTP/1.1" 404 1829
INFO 2025-06-03 12:37:03,064 autoreload 10288 2512 Watching for file changes with StatReloader
WARNING 2025-06-03 12:37:07,363 log 10288 12708 Not Found: /
WARNING 2025-06-03 12:37:07,364 basehttp 10288 12708 "GET / HTTP/1.1" 404 1937
ERROR 2025-06-03 12:37:13,541 log 10288 8476 Internal Server Error: /
Traceback (most recent call last):
  File "D:\WORK PROJECTS\Autowash Build\autowash\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "D:\WORK PROJECTS\Autowash Build\autowash\venv\Lib\site-packages\django\utils\deprecation.py", line 119, in __call__
    response = self.process_request(request)
  File "D:\WORK PROJECTS\Autowash Build\autowash\venv\Lib\site-packages\django_tenants\middleware\main.py", line 50, in process_request
    tenant.domain_url = hostname
    ^^^^^^^^^^^^^^^^^
AttributeError: property 'domain_url' of 'Business' object has no setter
ERROR 2025-06-03 12:37:13,545 basehttp 10288 8476 "GET / HTTP/1.1" 500 86898
ERROR 2025-06-03 12:37:14,157 log 10288 12488 Internal Server Error: /favicon.ico
Traceback (most recent call last):
  File "D:\WORK PROJECTS\Autowash Build\autowash\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "D:\WORK PROJECTS\Autowash Build\autowash\venv\Lib\site-packages\django\utils\deprecation.py", line 119, in __call__
    response = self.process_request(request)
  File "D:\WORK PROJECTS\Autowash Build\autowash\venv\Lib\site-packages\django_tenants\middleware\main.py", line 50, in process_request
    tenant.domain_url = hostname
    ^^^^^^^^^^^^^^^^^
AttributeError: property 'domain_url' of 'Business' object has no setter
ERROR 2025-06-03 12:37:14,161 basehttp 10288 12488 "GET /favicon.ico HTTP/1.1" 500 86698
INFO 2025-06-03 12:43:36,434 autoreload 10288 2512 D:\WORK PROJECTS\Autowash Build\autowash\apps\accounts\models.py changed, reloading.
INFO 2025-06-03 12:43:41,125 autoreload 15856 22184 Watching for file changes with StatReloader
ERROR 2025-06-03 12:44:05,721 log 15856 15152 Internal Server Error: /
Traceback (most recent call last):
  File "D:\WORK PROJECTS\Autowash Build\autowash\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "D:\WORK PROJECTS\Autowash Build\autowash\venv\Lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
  File "D:\WORK PROJECTS\Autowash Build\autowash\venv\Lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "D:\WORK PROJECTS\Autowash Build\autowash\venv\Lib\site-packages\django\template\response.py", line 90, in rendered_content
    template = self.resolve_template(self.template_name)
  File "D:\WORK PROJECTS\Autowash Build\autowash\venv\Lib\site-packages\django\template\response.py", line 72, in resolve_template
    return select_template(template, using=self.using)
  File "D:\WORK PROJECTS\Autowash Build\autowash\venv\Lib\site-packages\django\template\loader.py", line 47, in select_template
    raise TemplateDoesNotExist(", ".join(template_name_list), chain=chain)
django.template.exceptions.TemplateDoesNotExist: public/landing.html
ERROR 2025-06-03 12:44:05,726 basehttp 15856 15152 "GET / HTTP/1.1" 500 105335
WARNING 2025-06-03 12:44:06,178 log 15856 15152 Not Found: /favicon.ico
WARNING 2025-06-03 12:44:06,179 basehttp 15856 15152 "GET /favicon.ico HTTP/1.1" 404 3682
INFO 2025-06-03 12:48:03,185 basehttp 15856 14844 code 400, message Bad request version ("\x9c\x1b\x95'\x83³AÕ\x8en\x91\x8eòsZlà»/j9\x92\x98")
ERROR 2025-06-03 12:48:03,198 basehttp 15856 14844 You're accessing the development server over HTTPS, but it only supports HTTP.
INFO 2025-06-03 12:48:03,204 basehttp 15856 11160 code 400, message Bad request version ('Ömù')
ERROR 2025-06-03 12:48:03,205 basehttp 15856 11160 You're accessing the development server over HTTPS, but it only supports HTTP.
INFO 2025-06-03 12:48:07,268 basehttp 15856 3112 code 400, message Bad HTTP/0.9 request type ('\x16\x03\x01\x06à\x01\x00\x06Ü\x03\x03*r@9')
ERROR 2025-06-03 12:48:07,269 basehttp 15856 3112 You're accessing the development server over HTTPS, but it only supports HTTP.
INFO 2025-06-03 12:48:07,269 basehttp 15856 13276 code 400, message Bad HTTP/0.9 request type ('\x16\x03\x01\x06À\x01\x00\x06¼\x03\x03ÏZAÛ\x9fàð£yH\x02{&Å(uþh¤øÑbGñµ\x1ao-"ø¥L')
ERROR 2025-06-03 12:48:07,270 basehttp 15856 13276 You're accessing the development server over HTTPS, but it only supports HTTP.
INFO 2025-06-03 12:48:07,271 basehttp 15856 23452 code 400, message Bad request syntax ('\x16\x03\x01\x06À\x01\x00\x06¼\x03\x03K\x07©èz¨×¬Ðà\x1bø')
ERROR 2025-06-03 12:48:07,271 basehttp 15856 23452 You're accessing the development server over HTTPS, but it only supports HTTP.
INFO 2025-06-03 12:48:07,272 basehttp 15856 23776 code 400, message Bad request version ('íÖ^½ÂF')
ERROR 2025-06-03 12:48:07,272 basehttp 15856 23776 You're accessing the development server over HTTPS, but it only supports HTTP.
INFO 2025-06-03 12:48:16,992 basehttp 15856 10156 code 400, message Bad request version ('ºº\x13\x01\x13\x02\x13\x03À+À/À,À0Ì©Ì¨À\x13À\x14\x00\x9c\x00\x9d\x00/\x005\x01\x00\x06\x93JJ\x00\x00\x00\x1b\x00\x03\x02\x00\x02ÿ\x01\x00\x01\x00\x00')
ERROR 2025-06-03 12:48:16,993 basehttp 15856 10156 You're accessing the development server over HTTPS, but it only supports HTTP.
INFO 2025-06-03 12:48:16,995 basehttp 15856 19960 code 400, message Bad request version ('AkÖ÷Å\x8c\x19ÜiW{µ·')
ERROR 2025-06-03 12:48:16,996 basehttp 15856 19960 You're accessing the development server over HTTPS, but it only supports HTTP.
INFO 2025-06-03 12:48:24,697 basehttp 15856 19956 code 400, message Bad request version ('A¦Z\x02ðq¤\x02î$Ï«')
ERROR 2025-06-03 12:48:24,698 basehttp 15856 19956 You're accessing the development server over HTTPS, but it only supports HTTP.
INFO 2025-06-03 12:48:24,700 basehttp 15856 13164 code 400, message Bad request version ('\x00\x12\x00\x10\x04\x03\x08\x04\x04\x01\x05\x03\x08\x05\x05\x01\x08\x06\x06\x01\x00\x05\x00\x05\x01\x00\x00\x00\x00\x00\x1b\x00\x03\x02\x00\x02\x00')
ERROR 2025-06-03 12:48:24,700 basehttp 15856 13164 You're accessing the development server over HTTPS, but it only supports HTTP.
INFO 2025-06-03 12:48:24,703 basehttp 15856 13344 code 400, message Bad request version ('aiñ\x89\x80Z.^a=i')
INFO 2025-06-03 12:48:24,704 basehttp 15856 23648 code 400, message Bad request version ('ÈÆØ')
ERROR 2025-06-03 12:48:24,704 basehttp 15856 13344 You're accessing the development server over HTTPS, but it only supports HTTP.
ERROR 2025-06-03 12:48:24,704 basehttp 15856 23648 You're accessing the development server over HTTPS, but it only supports HTTP.
INFO 2025-06-03 12:48:24,707 basehttp 15856 13492 code 400, message Bad request version ('\x00\x02\x01\x00\x00\x12\x00\x00\x00\x17\x00\x00\x00')
INFO 2025-06-03 12:48:24,707 basehttp 15856 16056 code 400, message Bad HTTP/0.9 request type ('\x16\x03\x01\x07\x00\x01\x00\x06ü\x03\x03\x9cÀIåPx\x05\x07íëNèmûo_\x93Õä\x15\x0774\x86)Ûän]\x04Ê%')
ERROR 2025-06-03 12:48:24,708 basehttp 15856 13492 You're accessing the development server over HTTPS, but it only supports HTTP.
ERROR 2025-06-03 12:48:24,710 basehttp 15856 16056 You're accessing the development server over HTTPS, but it only supports HTTP.
INFO 2025-06-03 12:49:56,039 basehttp 15856 3444 code 400, message Bad request version ('\x02\x95\x8cª?IØ\x07\x12¥,P\x9bÕ¸v3Y\x86\x06u[g¸b\x05cÿ\x9a!I§\x7fI.àU;\x185Èô}\x946ûmqb¥È\x95]S&\x9cÙ´z×WÎ5!a')
ERROR 2025-06-03 12:49:56,040 basehttp 15856 3444 You're accessing the development server over HTTPS, but it only supports HTTP.
INFO 2025-06-03 12:49:56,042 basehttp 15856 19328 code 400, message Bad request syntax ("\x16\x03\x01\x06à\x01\x00\x06Ü\x03\x03M%9'ºq&«\x91L\x11\x1b\x93ÛÚx*'\x94\x00\x8a\x8eR\x02")
ERROR 2025-06-03 12:49:56,042 basehttp 15856 19328 You're accessing the development server over HTTPS, but it only supports HTTP.
INFO 2025-06-03 12:49:58,692 basehttp 15856 8476 code 400, message Bad request version ('i4\x82')
ERROR 2025-06-03 12:49:58,693 basehttp 15856 8476 You're accessing the development server over HTTPS, but it only supports HTTP.
INFO 2025-06-03 12:49:58,694 basehttp 15856 17412 code 400, message Bad request version ('"K\x8dðxúU\xad®\x16yW\x92e\x9bëë\x83Kâþ\x8e')
ERROR 2025-06-03 12:49:58,695 basehttp 15856 17412 You're accessing the development server over HTTPS, but it only supports HTTP.
INFO 2025-06-03 12:49:58,697 basehttp 15856 15792 code 400, message Bad request version ('(')
ERROR 2025-06-03 12:49:58,698 basehttp 15856 15792 You're accessing the development server over HTTPS, but it only supports HTTP.
INFO 2025-06-03 12:49:58,698 basehttp 15856 4428 code 400, message Bad request version ('X\x98\x05¼\x8d»\x19Ð\x10H^\x18Ï')
ERROR 2025-06-03 12:49:58,699 basehttp 15856 4428 You're accessing the development server over HTTPS, but it only supports HTTP.
INFO 2025-06-03 12:49:58,700 basehttp 15856 15976 code 400, message Bad request version ('::\x13\x01\x13\x02\x13\x03À+À/À,À0Ì©Ì¨À\x13À\x14\x00\x9c\x00\x9d\x00/\x005\x01\x00\x06S\x1a\x1a\x00\x00\x00+\x00\x07\x06ªª\x03\x04\x03\x03\x00')
ERROR 2025-06-03 12:49:58,700 basehttp 15856 15976 You're accessing the development server over HTTPS, but it only supports HTTP.
INFO 2025-06-03 12:49:58,701 basehttp 15856 23944 code 400, message Bad request syntax ('\x16\x03\x01\x06à\x01\x00\x06Ü\x03\x03ZÆ\x8fX\x13SÑ¤x\x8d\x94Ó\x05íHú]\x80\x88')
ERROR 2025-06-03 12:49:58,702 basehttp 15856 23944 You're accessing the development server over HTTPS, but it only supports HTTP.
INFO 2025-06-03 12:50:22,040 basehttp 15856 21712 code 400, message Bad request version ('ªª\x13\x01\x13\x02\x13\x03À+À/À,À0Ì©Ì¨À\x13À\x14\x00\x9c\x00\x9d\x00/\x005\x01\x00\x06\x93ªª\x00\x00\x00')
ERROR 2025-06-03 12:50:22,040 basehttp 15856 21712 You're accessing the development server over HTTPS, but it only supports HTTP.
INFO 2025-06-03 12:50:22,042 basehttp 15856 20212 code 400, message Bad request version ('\x00\x02\x01\x00\x00-\x00\x02\x01\x01\x00+\x00\x07\x06úú\x03\x04\x03\x03\x00')
ERROR 2025-06-03 12:50:22,042 basehttp 15856 20212 You're accessing the development server over HTTPS, but it only supports HTTP.
INFO 2025-06-03 12:51:21,571 basehttp 15856 6776 code 400, message Bad request version ('\x02h2\x08http/1.1\x00')
ERROR 2025-06-03 12:51:21,572 basehttp 15856 6776 You're accessing the development server over HTTPS, but it only supports HTTP.
INFO 2025-06-03 12:51:21,573 basehttp 15856 21484 code 400, message Bad HTTP/0.9 request type ('\x16\x03\x01\x06')
ERROR 2025-06-03 12:51:21,574 basehttp 15856 21484 You're accessing the development server over HTTPS, but it only supports HTTP.
INFO 2025-06-03 12:52:08,866 autoreload 23068 21712 Watching for file changes with StatReloader
ERROR 2025-06-03 12:52:14,704 log 23068 13108 Internal Server Error: /
Traceback (most recent call last):
  File "D:\WORK PROJECTS\Autowash Build\autowash\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "D:\WORK PROJECTS\Autowash Build\autowash\venv\Lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
  File "D:\WORK PROJECTS\Autowash Build\autowash\venv\Lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "D:\WORK PROJECTS\Autowash Build\autowash\venv\Lib\site-packages\django\template\response.py", line 90, in rendered_content
    template = self.resolve_template(self.template_name)
  File "D:\WORK PROJECTS\Autowash Build\autowash\venv\Lib\site-packages\django\template\response.py", line 72, in resolve_template
    return select_template(template, using=self.using)
  File "D:\WORK PROJECTS\Autowash Build\autowash\venv\Lib\site-packages\django\template\loader.py", line 47, in select_template
    raise TemplateDoesNotExist(", ".join(template_name_list), chain=chain)
django.template.exceptions.TemplateDoesNotExist: public/landing.html
ERROR 2025-06-03 12:52:14,709 basehttp 23068 13108 "GET / HTTP/1.1" 500 100814
WARNING 2025-06-03 12:52:15,168 log 23068 14004 Not Found: /favicon.ico
WARNING 2025-06-03 12:52:15,169 basehttp 23068 14004 "GET /favicon.ico HTTP/1.1" 404 3682
WARNING 2025-06-03 12:52:30,135 log 23068 12104 Not Found: /accounts/register
WARNING 2025-06-03 12:52:30,136 basehttp 23068 12104 "GET /accounts/register HTTP/1.1" 404 10566
INFO 2025-06-03 12:52:41,412 basehttp 23068 12104 "GET /accounts/signup HTTP/1.1" 301 0
INFO 2025-06-03 12:52:41,678 basehttp 23068 20132 "GET /accounts/signup/ HTTP/1.1" 200 2510
WARNING 2025-06-03 12:52:56,105 log 23068 20132 Not Found: /accounts/register/
WARNING 2025-06-03 12:52:56,105 basehttp 23068 20132 "GET /accounts/register/ HTTP/1.1" 404 10569
INFO 2025-06-03 12:53:48,556 autoreload 23068 21712 D:\WORK PROJECTS\Autowash Build\autowash\autowash\urls_public.py changed, reloading.
INFO 2025-06-03 12:53:52,863 autoreload 5632 14860 Watching for file changes with StatReloader
ERROR 2025-06-03 12:53:56,178 log 5632 23636 Internal Server Error: /auth/register/
Traceback (most recent call last):
  File "D:\WORK PROJECTS\Autowash Build\autowash\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "D:\WORK PROJECTS\Autowash Build\autowash\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\WORK PROJECTS\Autowash Build\autowash\apps\accounts\views.py", line 90, in register_view
    return render(request, 'auth/register.html', {'form': form})
  File "D:\WORK PROJECTS\Autowash Build\autowash\venv\Lib\site-packages\django\shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "D:\WORK PROJECTS\Autowash Build\autowash\venv\Lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "D:\WORK PROJECTS\Autowash Build\autowash\venv\Lib\site-packages\django\template\loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: auth/register.html
ERROR 2025-06-03 12:53:56,183 basehttp 5632 23636 "GET /auth/register/ HTTP/1.1" 500 102730
ERROR 2025-06-03 13:02:24,557 log 5632 24144 Internal Server Error: /auth/register/
Traceback (most recent call last):
  File "D:\WORK PROJECTS\Autowash Build\autowash\venv\Lib\site-packages\django\template\backends\django.py", line 107, in render
    return self.template.render(context)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "D:\WORK PROJECTS\Autowash Build\autowash\venv\Lib\site-packages\django\template\base.py", line 171, in render
    return self._render(context)
           ~~~~~~~~~~~~^^^^^^^^^
  File "D:\WORK PROJECTS\Autowash Build\autowash\venv\Lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "D:\WORK PROJECTS\Autowash Build\autowash\venv\Lib\site-packages\django\template\base.py", line 1016, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "D:\WORK PROJECTS\Autowash Build\autowash\venv\Lib\site-packages\django\template\base.py", line 977, in render_annotated
    return self.render(context)
           ~~~~~~~~~~~^^^^^^^^^
  File "D:\WORK PROJECTS\Autowash Build\autowash\venv\Lib\site-packages\django\template\loader_tags.py", line 134, in render
    compiled_parent = self.get_parent(context)
  File "D:\WORK PROJECTS\Autowash Build\autowash\venv\Lib\site-packages\django\template\loader_tags.py", line 131, in get_parent
    return self.find_template(parent, context)
           ~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
  File "D:\WORK PROJECTS\Autowash Build\autowash\venv\Lib\site-packages\django\template\loader_tags.py", line 109, in find_template
    template, origin = context.template.engine.find_template(
                       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
        template_name,
        ^^^^^^^^^^^^^^
        skip=history,
        ^^^^^^^^^^^^^
    )
    ^
  File "D:\WORK PROJECTS\Autowash Build\autowash\venv\Lib\site-packages\django\template\engine.py", line 163, in find_template
    raise TemplateDoesNotExist(name, tried=tried)
django.template.exceptions.TemplateDoesNotExist: base.html

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\WORK PROJECTS\Autowash Build\autowash\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "D:\WORK PROJECTS\Autowash Build\autowash\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\WORK PROJECTS\Autowash Build\autowash\apps\accounts\views.py", line 90, in register_view
    return render(request, 'auth/register.html', {'form': form})
  File "D:\WORK PROJECTS\Autowash Build\autowash\venv\Lib\site-packages\django\shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "D:\WORK PROJECTS\Autowash Build\autowash\venv\Lib\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^
  File "D:\WORK PROJECTS\Autowash Build\autowash\venv\Lib\site-packages\django\template\backends\django.py", line 109, in render
    reraise(exc, self.backend)
    ~~~~~~~^^^^^^^^^^^^^^^^^^^
  File "D:\WORK PROJECTS\Autowash Build\autowash\venv\Lib\site-packages\django\template\backends\django.py", line 130, in reraise
    raise new from exc
django.template.exceptions.TemplateDoesNotExist: base.html
ERROR 2025-06-03 13:02:24,566 basehttp 5632 24144 "GET /auth/register/ HTTP/1.1" 500 152481
ERROR 2025-06-03 13:02:26,292 log 5632 24144 Internal Server Error: /auth/register/
Traceback (most recent call last):
  File "D:\WORK PROJECTS\Autowash Build\autowash\venv\Lib\site-packages\django\template\backends\django.py", line 107, in render
    return self.template.render(context)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "D:\WORK PROJECTS\Autowash Build\autowash\venv\Lib\site-packages\django\template\base.py", line 171, in render
    return self._render(context)
           ~~~~~~~~~~~~^^^^^^^^^
  File "D:\WORK PROJECTS\Autowash Build\autowash\venv\Lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "D:\WORK PROJECTS\Autowash Build\autowash\venv\Lib\site-packages\django\template\base.py", line 1016, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "D:\WORK PROJECTS\Autowash Build\autowash\venv\Lib\site-packages\django\template\base.py", line 977, in render_annotated
    return self.render(context)
           ~~~~~~~~~~~^^^^^^^^^
  File "D:\WORK PROJECTS\Autowash Build\autowash\venv\Lib\site-packages\django\template\loader_tags.py", line 134, in render
    compiled_parent = self.get_parent(context)
  File "D:\WORK PROJECTS\Autowash Build\autowash\venv\Lib\site-packages\django\template\loader_tags.py", line 131, in get_parent
    return self.find_template(parent, context)
           ~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
  File "D:\WORK PROJECTS\Autowash Build\autowash\venv\Lib\site-packages\django\template\loader_tags.py", line 109, in find_template
    template, origin = context.template.engine.find_template(
                       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
        template_name,
        ^^^^^^^^^^^^^^
        skip=history,
        ^^^^^^^^^^^^^
    )
    ^
  File "D:\WORK PROJECTS\Autowash Build\autowash\venv\Lib\site-packages\django\template\engine.py", line 163, in find_template
    raise TemplateDoesNotExist(name, tried=tried)
django.template.exceptions.TemplateDoesNotExist: base.html

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\WORK PROJECTS\Autowash Build\autowash\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "D:\WORK PROJECTS\Autowash Build\autowash\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\WORK PROJECTS\Autowash Build\autowash\apps\accounts\views.py", line 90, in register_view
    return render(request, 'auth/register.html', {'form': form})
  File "D:\WORK PROJECTS\Autowash Build\autowash\venv\Lib\site-packages\django\shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "D:\WORK PROJECTS\Autowash Build\autowash\venv\Lib\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^
  File "D:\WORK PROJECTS\Autowash Build\autowash\venv\Lib\site-packages\django\template\backends\django.py", line 109, in render
    reraise(exc, self.backend)
    ~~~~~~~^^^^^^^^^^^^^^^^^^^
  File "D:\WORK PROJECTS\Autowash Build\autowash\venv\Lib\site-packages\django\template\backends\django.py", line 130, in reraise
    raise new from exc
django.template.exceptions.TemplateDoesNotExist: base.html
ERROR 2025-06-03 13:02:26,297 basehttp 5632 24144 "GET /auth/register/ HTTP/1.1" 500 152481
ERROR 2025-06-03 13:03:45,575 log 5632 24144 Internal Server Error: /auth/register/
Traceback (most recent call last):
  File "D:\WORK PROJECTS\Autowash Build\autowash\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "D:\WORK PROJECTS\Autowash Build\autowash\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\WORK PROJECTS\Autowash Build\autowash\apps\accounts\views.py", line 90, in register_view
    return render(request, 'auth/register.html', {'form': form})
  File "D:\WORK PROJECTS\Autowash Build\autowash\venv\Lib\site-packages\django\shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "D:\WORK PROJECTS\Autowash Build\autowash\venv\Lib\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^
  File "D:\WORK PROJECTS\Autowash Build\autowash\venv\Lib\site-packages\django\template\backends\django.py", line 107, in render
    return self.template.render(context)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "D:\WORK PROJECTS\Autowash Build\autowash\venv\Lib\site-packages\django\template\base.py", line 171, in render
    return self._render(context)
           ~~~~~~~~~~~~^^^^^^^^^
  File "D:\WORK PROJECTS\Autowash Build\autowash\venv\Lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "D:\WORK PROJECTS\Autowash Build\autowash\venv\Lib\site-packages\django\template\base.py", line 1016, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "D:\WORK PROJECTS\Autowash Build\autowash\venv\Lib\site-packages\django\template\base.py", line 977, in render_annotated
    return self.render(context)
           ~~~~~~~~~~~^^^^^^^^^
  File "D:\WORK PROJECTS\Autowash Build\autowash\venv\Lib\site-packages\django\template\loader_tags.py", line 134, in render
    compiled_parent = self.get_parent(context)
  File "D:\WORK PROJECTS\Autowash Build\autowash\venv\Lib\site-packages\django\template\loader_tags.py", line 131, in get_parent
    return self.find_template(parent, context)
           ~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
  File "D:\WORK PROJECTS\Autowash Build\autowash\venv\Lib\site-packages\django\template\loader_tags.py", line 109, in find_template
    template, origin = context.template.engine.find_template(
                       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
        template_name,
        ^^^^^^^^^^^^^^
        skip=history,
        ^^^^^^^^^^^^^
    )
    ^
  File "D:\WORK PROJECTS\Autowash Build\autowash\venv\Lib\site-packages\django\template\engine.py", line 159, in find_template
    template = loader.get_template(name, skip=skip)
  File "D:\WORK PROJECTS\Autowash Build\autowash\venv\Lib\site-packages\django\template\loaders\cached.py", line 57, in get_template
    template = super().get_template(template_name, skip)
  File "D:\WORK PROJECTS\Autowash Build\autowash\venv\Lib\site-packages\django\template\loaders\base.py", line 28, in get_template
    return Template(
        contents,
    ...<2 lines>...
        self.engine,
    )
  File "D:\WORK PROJECTS\Autowash Build\autowash\venv\Lib\site-packages\django\template\base.py", line 154, in __init__
    self.nodelist = self.compile_nodelist()
                    ~~~~~~~~~~~~~~~~~~~~~^^
  File "D:\WORK PROJECTS\Autowash Build\autowash\venv\Lib\site-packages\django\template\base.py", line 196, in compile_nodelist
    nodelist = parser.parse()
  File "D:\WORK PROJECTS\Autowash Build\autowash\venv\Lib\site-packages\django\template\base.py", line 518, in parse
    raise self.error(token, e)
  File "D:\WORK PROJECTS\Autowash Build\autowash\venv\Lib\site-packages\django\template\base.py", line 516, in parse
    compiled_result = compile_func(self, token)
  File "D:\WORK PROJECTS\Autowash Build\autowash\venv\Lib\site-packages\django\template\defaulttags.py", line 976, in do_if
    nodelist = parser.parse(("endif",))
  File "D:\WORK PROJECTS\Autowash Build\autowash\venv\Lib\site-packages\django\template\base.py", line 518, in parse
    raise self.error(token, e)
  File "D:\WORK PROJECTS\Autowash Build\autowash\venv\Lib\site-packages\django\template\base.py", line 516, in parse
    compiled_result = compile_func(self, token)
  File "D:\WORK PROJECTS\Autowash Build\autowash\venv\Lib\site-packages\django\template\loader_tags.py", line 228, in do_block
    raise TemplateSyntaxError(
        "'%s' tag with name '%s' appears more than once" % (bits[0], block_name)
    )
django.template.exceptions.TemplateSyntaxError: 'block' tag with name 'content' appears more than once
ERROR 2025-06-03 13:03:45,585 basehttp 5632 24144 "GET /auth/register/ HTTP/1.1" 500 222952
INFO 2025-06-03 13:04:53,629 basehttp 5632 24144 "GET /auth/register/ HTTP/1.1" 200 12570
WARNING 2025-06-03 13:04:53,653 basehttp 5632 24144 "GET /static/css/custom.css HTTP/1.1" 404 1969
WARNING 2025-06-03 13:04:53,659 basehttp 5632 21036 "GET /static/css/dashboard.css HTTP/1.1" 404 1978
WARNING 2025-06-03 13:04:54,250 basehttp 5632 23236 "GET /static/img/favicon.ico HTTP/1.1" 404 1972
INFO 2025-06-03 13:04:59,910 basehttp 5632 3528 "GET /auth/login/ HTTP/1.1" 200 12567
WARNING 2025-06-03 13:04:59,957 basehttp 5632 3528 "GET /static/css/custom.css HTTP/1.1" 404 1969
WARNING 2025-06-03 13:04:59,957 basehttp 5632 2604 "GET /static/css/dashboard.css HTTP/1.1" 404 1978
INFO 2025-06-03 13:05:02,164 basehttp 5632 5748 "GET /auth/register/ HTTP/1.1" 200 12570
WARNING 2025-06-03 13:05:02,201 basehttp 5632 5748 "GET /static/css/custom.css HTTP/1.1" 404 1969
WARNING 2025-06-03 13:05:02,207 basehttp 5632 23752 "GET /static/css/dashboard.css HTTP/1.1" 404 1978
ERROR 2025-06-03 13:05:10,720 log 5632 19260 Internal Server Error: /
Traceback (most recent call last):
  File "D:\WORK PROJECTS\Autowash Build\autowash\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "D:\WORK PROJECTS\Autowash Build\autowash\venv\Lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
  File "D:\WORK PROJECTS\Autowash Build\autowash\venv\Lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "D:\WORK PROJECTS\Autowash Build\autowash\venv\Lib\site-packages\django\template\response.py", line 90, in rendered_content
    template = self.resolve_template(self.template_name)
  File "D:\WORK PROJECTS\Autowash Build\autowash\venv\Lib\site-packages\django\template\response.py", line 72, in resolve_template
    return select_template(template, using=self.using)
  File "D:\WORK PROJECTS\Autowash Build\autowash\venv\Lib\site-packages\django\template\loader.py", line 47, in select_template
    raise TemplateDoesNotExist(", ".join(template_name_list), chain=chain)
django.template.exceptions.TemplateDoesNotExist: public/landing.html
ERROR 2025-06-03 13:05:10,723 basehttp 5632 19260 "GET / HTTP/1.1" 500 101604
ERROR 2025-06-03 13:05:13,536 log 5632 19260 Internal Server Error: /features/
Traceback (most recent call last):
  File "D:\WORK PROJECTS\Autowash Build\autowash\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "D:\WORK PROJECTS\Autowash Build\autowash\venv\Lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
  File "D:\WORK PROJECTS\Autowash Build\autowash\venv\Lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "D:\WORK PROJECTS\Autowash Build\autowash\venv\Lib\site-packages\django\template\response.py", line 90, in rendered_content
    template = self.resolve_template(self.template_name)
  File "D:\WORK PROJECTS\Autowash Build\autowash\venv\Lib\site-packages\django\template\response.py", line 72, in resolve_template
    return select_template(template, using=self.using)
  File "D:\WORK PROJECTS\Autowash Build\autowash\venv\Lib\site-packages\django\template\loader.py", line 47, in select_template
    raise TemplateDoesNotExist(", ".join(template_name_list), chain=chain)
django.template.exceptions.TemplateDoesNotExist: public/features.html
ERROR 2025-06-03 13:05:13,539 basehttp 5632 19260 "GET /features/ HTTP/1.1" 500 101715
ERROR 2025-06-03 13:05:16,802 log 5632 19260 Internal Server Error: /pricing/
Traceback (most recent call last):
  File "D:\WORK PROJECTS\Autowash Build\autowash\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "D:\WORK PROJECTS\Autowash Build\autowash\venv\Lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
  File "D:\WORK PROJECTS\Autowash Build\autowash\venv\Lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "D:\WORK PROJECTS\Autowash Build\autowash\venv\Lib\site-packages\django\template\response.py", line 90, in rendered_content
    template = self.resolve_template(self.template_name)
  File "D:\WORK PROJECTS\Autowash Build\autowash\venv\Lib\site-packages\django\template\response.py", line 72, in resolve_template
    return select_template(template, using=self.using)
  File "D:\WORK PROJECTS\Autowash Build\autowash\venv\Lib\site-packages\django\template\loader.py", line 47, in select_template
    raise TemplateDoesNotExist(", ".join(template_name_list), chain=chain)
django.template.exceptions.TemplateDoesNotExist: public/pricing.html
ERROR 2025-06-03 13:05:16,805 basehttp 5632 19260 "GET /pricing/ HTTP/1.1" 500 101676
ERROR 2025-06-03 13:05:20,642 log 5632 19260 Internal Server Error: /contact/
Traceback (most recent call last):
  File "D:\WORK PROJECTS\Autowash Build\autowash\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "D:\WORK PROJECTS\Autowash Build\autowash\venv\Lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
  File "D:\WORK PROJECTS\Autowash Build\autowash\venv\Lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "D:\WORK PROJECTS\Autowash Build\autowash\venv\Lib\site-packages\django\template\response.py", line 90, in rendered_content
    template = self.resolve_template(self.template_name)
  File "D:\WORK PROJECTS\Autowash Build\autowash\venv\Lib\site-packages\django\template\response.py", line 72, in resolve_template
    return select_template(template, using=self.using)
  File "D:\WORK PROJECTS\Autowash Build\autowash\venv\Lib\site-packages\django\template\loader.py", line 47, in select_template
    raise TemplateDoesNotExist(", ".join(template_name_list), chain=chain)
django.template.exceptions.TemplateDoesNotExist: public/contact.html
ERROR 2025-06-03 13:05:20,644 basehttp 5632 19260 "GET /contact/ HTTP/1.1" 500 101676
INFO 2025-06-03 13:05:24,524 basehttp 5632 19260 "GET /auth/register/ HTTP/1.1" 200 12570
WARNING 2025-06-03 13:05:24,544 basehttp 5632 19260 "GET /static/css/custom.css HTTP/1.1" 404 1969
WARNING 2025-06-03 13:05:24,545 basehttp 5632 7856 "GET /static/css/dashboard.css HTTP/1.1" 404 1978
ERROR 2025-06-03 13:05:36,028 log 5632 5996 Internal Server Error: /
Traceback (most recent call last):
  File "D:\WORK PROJECTS\Autowash Build\autowash\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "D:\WORK PROJECTS\Autowash Build\autowash\venv\Lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
  File "D:\WORK PROJECTS\Autowash Build\autowash\venv\Lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "D:\WORK PROJECTS\Autowash Build\autowash\venv\Lib\site-packages\django\template\response.py", line 90, in rendered_content
    template = self.resolve_template(self.template_name)
  File "D:\WORK PROJECTS\Autowash Build\autowash\venv\Lib\site-packages\django\template\response.py", line 72, in resolve_template
    return select_template(template, using=self.using)
  File "D:\WORK PROJECTS\Autowash Build\autowash\venv\Lib\site-packages\django\template\loader.py", line 47, in select_template
    raise TemplateDoesNotExist(", ".join(template_name_list), chain=chain)
django.template.exceptions.TemplateDoesNotExist: public/landing.html
ERROR 2025-06-03 13:05:36,030 basehttp 5632 5996 "GET / HTTP/1.1" 500 101604
INFO 2025-06-03 13:05:40,444 basehttp 5632 5996 "GET /auth/login/ HTTP/1.1" 200 12567
WARNING 2025-06-03 13:05:40,481 basehttp 5632 5996 "GET /static/css/custom.css HTTP/1.1" 404 1969
WARNING 2025-06-03 13:05:40,491 basehttp 5632 13248 "GET /static/css/dashboard.css HTTP/1.1" 404 1978
INFO 2025-06-03 13:05:43,899 basehttp 5632 17716 "GET /auth/register/ HTTP/1.1" 200 12570
WARNING 2025-06-03 13:05:43,932 basehttp 5632 17716 "GET /static/css/custom.css HTTP/1.1" 404 1969
WARNING 2025-06-03 13:05:43,932 basehttp 5632 13820 "GET /static/css/dashboard.css HTTP/1.1" 404 1978
INFO 2025-06-03 13:05:46,651 basehttp 5632 12260 "GET /auth/register/ HTTP/1.1" 200 12570
WARNING 2025-06-03 13:05:46,677 basehttp 5632 12260 "GET /static/css/custom.css HTTP/1.1" 404 1969
WARNING 2025-06-03 13:05:46,677 basehttp 5632 10164 "GET /static/css/dashboard.css HTTP/1.1" 404 1978
INFO 2025-06-03 13:06:01,515 basehttp 5632 17032 "GET /auth/register/ HTTP/1.1" 200 12570
WARNING 2025-06-03 13:06:01,537 basehttp 5632 17032 "GET /static/css/custom.css HTTP/1.1" 404 1969
WARNING 2025-06-03 13:06:01,542 basehttp 5632 12964 "GET /static/css/dashboard.css HTTP/1.1" 404 1978
ERROR 2025-06-03 13:06:04,035 log 5632 19180 Internal Server Error: /
Traceback (most recent call last):
  File "D:\WORK PROJECTS\Autowash Build\autowash\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "D:\WORK PROJECTS\Autowash Build\autowash\venv\Lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
  File "D:\WORK PROJECTS\Autowash Build\autowash\venv\Lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "D:\WORK PROJECTS\Autowash Build\autowash\venv\Lib\site-packages\django\template\response.py", line 90, in rendered_content
    template = self.resolve_template(self.template_name)
  File "D:\WORK PROJECTS\Autowash Build\autowash\venv\Lib\site-packages\django\template\response.py", line 72, in resolve_template
    return select_template(template, using=self.using)
  File "D:\WORK PROJECTS\Autowash Build\autowash\venv\Lib\site-packages\django\template\loader.py", line 47, in select_template
    raise TemplateDoesNotExist(", ".join(template_name_list), chain=chain)
django.template.exceptions.TemplateDoesNotExist: public/landing.html
ERROR 2025-06-03 13:06:04,038 basehttp 5632 19180 "GET / HTTP/1.1" 500 101604
ERROR 2025-06-03 13:06:34,175 log 5632 19180 Internal Server Error: /auth/login/
Traceback (most recent call last):
  File "D:\WORK PROJECTS\Autowash Build\autowash\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "D:\WORK PROJECTS\Autowash Build\autowash\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\WORK PROJECTS\Autowash Build\autowash\apps\accounts\views.py", line 112, in login_view
    return render(request, 'auth/login.html')
  File "D:\WORK PROJECTS\Autowash Build\autowash\venv\Lib\site-packages\django\shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "D:\WORK PROJECTS\Autowash Build\autowash\venv\Lib\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^
  File "D:\WORK PROJECTS\Autowash Build\autowash\venv\Lib\site-packages\django\template\backends\django.py", line 107, in render
    return self.template.render(context)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "D:\WORK PROJECTS\Autowash Build\autowash\venv\Lib\site-packages\django\template\base.py", line 171, in render
    return self._render(context)
           ~~~~~~~~~~~~^^^^^^^^^
  File "D:\WORK PROJECTS\Autowash Build\autowash\venv\Lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "D:\WORK PROJECTS\Autowash Build\autowash\venv\Lib\site-packages\django\template\base.py", line 1016, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "D:\WORK PROJECTS\Autowash Build\autowash\venv\Lib\site-packages\django\template\base.py", line 977, in render_annotated
    return self.render(context)
           ~~~~~~~~~~~^^^^^^^^^
  File "D:\WORK PROJECTS\Autowash Build\autowash\venv\Lib\site-packages\django\template\loader_tags.py", line 134, in render
    compiled_parent = self.get_parent(context)
  File "D:\WORK PROJECTS\Autowash Build\autowash\venv\Lib\site-packages\django\template\loader_tags.py", line 131, in get_parent
    return self.find_template(parent, context)
           ~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
  File "D:\WORK PROJECTS\Autowash Build\autowash\venv\Lib\site-packages\django\template\loader_tags.py", line 109, in find_template
    template, origin = context.template.engine.find_template(
                       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
        template_name,
        ^^^^^^^^^^^^^^
        skip=history,
        ^^^^^^^^^^^^^
    )
    ^
  File "D:\WORK PROJECTS\Autowash Build\autowash\venv\Lib\site-packages\django\template\engine.py", line 159, in find_template
    template = loader.get_template(name, skip=skip)
  File "D:\WORK PROJECTS\Autowash Build\autowash\venv\Lib\site-packages\django\template\loaders\cached.py", line 57, in get_template
    template = super().get_template(template_name, skip)
  File "D:\WORK PROJECTS\Autowash Build\autowash\venv\Lib\site-packages\django\template\loaders\base.py", line 28, in get_template
    return Template(
        contents,
    ...<2 lines>...
        self.engine,
    )
  File "D:\WORK PROJECTS\Autowash Build\autowash\venv\Lib\site-packages\django\template\base.py", line 154, in __init__
    self.nodelist = self.compile_nodelist()
                    ~~~~~~~~~~~~~~~~~~~~~^^
  File "D:\WORK PROJECTS\Autowash Build\autowash\venv\Lib\site-packages\django\template\base.py", line 196, in compile_nodelist
    nodelist = parser.parse()
  File "D:\WORK PROJECTS\Autowash Build\autowash\venv\Lib\site-packages\django\template\base.py", line 518, in parse
    raise self.error(token, e)
  File "D:\WORK PROJECTS\Autowash Build\autowash\venv\Lib\site-packages\django\template\base.py", line 516, in parse
    compiled_result = compile_func(self, token)
  File "D:\WORK PROJECTS\Autowash Build\autowash\venv\Lib\site-packages\django\template\defaulttags.py", line 976, in do_if
    nodelist = parser.parse(("endif",))
  File "D:\WORK PROJECTS\Autowash Build\autowash\venv\Lib\site-packages\django\template\base.py", line 518, in parse
    raise self.error(token, e)
  File "D:\WORK PROJECTS\Autowash Build\autowash\venv\Lib\site-packages\django\template\base.py", line 516, in parse
    compiled_result = compile_func(self, token)
  File "D:\WORK PROJECTS\Autowash Build\autowash\venv\Lib\site-packages\django\template\loader_tags.py", line 228, in do_block
    raise TemplateSyntaxError(
        "'%s' tag with name '%s' appears more than once" % (bits[0], block_name)
    )
django.template.exceptions.TemplateSyntaxError: 'block' tag with name 'content' appears more than once
ERROR 2025-06-03 13:06:34,181 basehttp 5632 19180 "GET /auth/login/ HTTP/1.1" 500 221094
WARNING 2025-06-03 13:08:40,282 log 5632 19180 Not Found: /admin
WARNING 2025-06-03 13:08:40,283 basehttp 5632 19180 "GET /admin HTTP/1.1" 404 3664
INFO 2025-06-03 13:08:49,594 basehttp 5632 19180 "GET /system-admin HTTP/1.1" 301 0
INFO 2025-06-03 13:08:49,695 basehttp 5632 14112 "GET /system-admin/ HTTP/1.1" 302 0
INFO 2025-06-03 13:08:49,857 basehttp 5632 14112 "GET /system-admin/login/?next=/system-admin/ HTTP/1.1" 200 4202
INFO 2025-06-03 13:08:49,876 basehttp 5632 14112 "GET /static/admin/css/base.css HTTP/1.1" 200 22120
INFO 2025-06-03 13:08:49,885 basehttp 5632 14112 "GET /static/admin/css/dark_mode.css HTTP/1.1" 200 2808
INFO 2025-06-03 13:08:49,887 basehttp 5632 3968 "GET /static/admin/css/login.css HTTP/1.1" 200 951
INFO 2025-06-03 13:08:49,888 basehttp 5632 21684 "GET /static/admin/css/nav_sidebar.css HTTP/1.1" 200 2810
INFO 2025-06-03 13:08:49,889 basehttp 5632 1220 "GET /static/admin/css/responsive.css HTTP/1.1" 200 16565
INFO 2025-06-03 13:08:49,912 basehttp 5632 13892 "GET /static/admin/js/theme.js HTTP/1.1" 200 1653
INFO 2025-06-03 13:08:49,921 basehttp 5632 1220 "GET /static/admin/js/nav_sidebar.js HTTP/1.1" 200 3063
INFO 2025-06-03 13:08:58,834 basehttp 5632 1220 "POST /system-admin/login/?next=/system-admin/ HTTP/1.1" 302 0
INFO 2025-06-03 13:08:59,020 basehttp 5632 1220 "GET /system-admin/ HTTP/1.1" 200 26412
INFO 2025-06-03 13:08:59,060 basehttp 5632 1220 "GET /static/admin/css/dashboard.css HTTP/1.1" 200 441
INFO 2025-06-03 13:08:59,078 basehttp 5632 13892 "GET /static/admin/img/icon-addlink.svg HTTP/1.1" 200 331
INFO 2025-06-03 13:08:59,078 basehttp 5632 21684 "GET /static/admin/img/icon-changelink.svg HTTP/1.1" 200 380
INFO 2025-06-03 13:09:09,079 basehttp 5632 13892 "GET /system-admin/subscriptions/subscriptionplan/ HTTP/1.1" 200 18855
INFO 2025-06-03 13:09:09,133 basehttp 5632 13892 "GET /static/admin/css/changelists.css HTTP/1.1" 200 6878
INFO 2025-06-03 13:09:09,165 basehttp 5632 3968 "GET /static/admin/js/jquery.init.js HTTP/1.1" 200 347
INFO 2025-06-03 13:09:09,185 basehttp 5632 14112 "GET /static/admin/js/core.js HTTP/1.1" 200 6208
INFO 2025-06-03 13:09:09,191 basehttp 5632 13892 "GET /static/admin/js/actions.js HTTP/1.1" 200 8076
INFO 2025-06-03 13:09:09,199 basehttp 5632 17092 "GET /static/admin/js/admin/RelatedObjectLookups.js HTTP/1.1" 200 9777
INFO 2025-06-03 13:09:09,235 basehttp 5632 14112 "GET /static/admin/js/prepopulate.js HTTP/1.1" 200 1531
INFO 2025-06-03 13:09:09,236 basehttp 5632 17092 "GET /static/admin/img/search.svg HTTP/1.1" 200 458
INFO 2025-06-03 13:09:09,243 basehttp 5632 3968 "GET /static/admin/js/urlify.js HTTP/1.1" 200 7887
INFO 2025-06-03 13:09:09,301 basehttp 5632 1220 "GET /static/admin/js/vendor/jquery/jquery.js HTTP/1.1" 200 285314
INFO 2025-06-03 13:09:09,383 basehttp 5632 21684 "GET /system-admin/jsi18n/ HTTP/1.1" 200 3342
INFO 2025-06-03 13:09:09,419 basehttp 5632 21684 "GET /static/admin/js/filters.js HTTP/1.1" 200 978
INFO 2025-06-03 13:09:09,448 basehttp 5632 13892 "GET /static/admin/js/vendor/xregexp/xregexp.js HTTP/1.1" 200 325171
INFO 2025-06-03 13:09:09,506 basehttp 5632 21684 "GET /static/admin/img/icon-viewlink.svg HTTP/1.1" 200 581
INFO 2025-06-03 13:09:09,510 basehttp 5632 13892 "GET /static/admin/img/tooltag-add.svg HTTP/1.1" 200 331
INFO 2025-06-03 13:09:22,675 basehttp 5632 13892 "GET /system-admin/auth/user/ HTTP/1.1" 200 20968
INFO 2025-06-03 13:09:22,715 basehttp 5632 13892 "GET /static/admin/img/icon-yes.svg HTTP/1.1" 200 436
INFO 2025-06-03 13:09:22,798 basehttp 5632 21684 "GET /system-admin/jsi18n/ HTTP/1.1" 200 3342
INFO 2025-06-03 13:09:22,834 basehttp 5632 21684 "GET /static/admin/img/sorting-icons.svg HTTP/1.1" 200 1097
INFO 2025-06-03 13:09:25,116 basehttp 5632 21684 "GET /system-admin/auth/user/1/change/ HTTP/1.1" 200 68421
INFO 2025-06-03 13:09:25,154 basehttp 5632 21684 "GET /static/admin/css/forms.css HTTP/1.1" 200 8525
INFO 2025-06-03 13:09:25,203 basehttp 5632 13892 "GET /static/admin/js/calendar.js HTTP/1.1" 200 9141
INFO 2025-06-03 13:09:25,209 basehttp 5632 1220 "GET /static/admin/js/admin/DateTimeShortcuts.js HTTP/1.1" 200 19319
INFO 2025-06-03 13:09:25,211 basehttp 5632 13892 "GET /static/admin/css/widgets.css HTTP/1.1" 200 11991
INFO 2025-06-03 13:09:25,212 basehttp 5632 17092 "GET /static/admin/js/SelectFilter2.js HTTP/1.1" 200 15709
INFO 2025-06-03 13:09:25,213 basehttp 5632 3968 "GET /static/admin/js/SelectBox.js HTTP/1.1" 200 4530
INFO 2025-06-03 13:09:25,214 basehttp 5632 21684 "GET /static/admin/js/prepopulate_init.js HTTP/1.1" 200 586
INFO 2025-06-03 13:09:25,255 basehttp 5632 13892 "GET /static/admin/js/change_form.js HTTP/1.1" 200 606
INFO 2025-06-03 13:09:25,323 basehttp 5632 14112 "GET /system-admin/jsi18n/ HTTP/1.1" 200 3342
INFO 2025-06-03 13:09:25,437 basehttp 5632 3968 "GET /static/admin/img/icon-clock.svg HTTP/1.1" 200 677
INFO 2025-06-03 13:09:25,439 basehttp 5632 14112 "GET /static/admin/img/selector-icons.svg HTTP/1.1" 200 3291
INFO 2025-06-03 13:09:25,439 basehttp 5632 13892 "GET /static/admin/img/icon-calendar.svg HTTP/1.1" 200 1086
INFO 2025-06-03 13:09:36,271 basehttp 5632 13892 "GET /system-admin/account/emailaddress/ HTTP/1.1" 200 18379
INFO 2025-06-03 13:09:36,399 basehttp 5632 13892 "GET /system-admin/jsi18n/ HTTP/1.1" 200 3342
INFO 2025-06-03 13:09:39,330 basehttp 5632 13892 "GET /system-admin/account/emailaddress/add/ HTTP/1.1" 200 19635
INFO 2025-06-03 13:09:39,457 basehttp 5632 13892 "GET /system-admin/jsi18n/ HTTP/1.1" 200 3342
INFO 2025-06-03 13:09:42,949 basehttp 5632 13892 "GET /system-admin/account/emailaddress/ HTTP/1.1" 200 18379
ERROR 2025-06-03 13:11:41,900 log 5632 13892 Internal Server Error: /
Traceback (most recent call last):
  File "D:\WORK PROJECTS\Autowash Build\autowash\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "D:\WORK PROJECTS\Autowash Build\autowash\venv\Lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
  File "D:\WORK PROJECTS\Autowash Build\autowash\venv\Lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "D:\WORK PROJECTS\Autowash Build\autowash\venv\Lib\site-packages\django\template\response.py", line 90, in rendered_content
    template = self.resolve_template(self.template_name)
  File "D:\WORK PROJECTS\Autowash Build\autowash\venv\Lib\site-packages\django\template\response.py", line 72, in resolve_template
    return select_template(template, using=self.using)
  File "D:\WORK PROJECTS\Autowash Build\autowash\venv\Lib\site-packages\django\template\loader.py", line 47, in select_template
    raise TemplateDoesNotExist(", ".join(template_name_list), chain=chain)
django.template.exceptions.TemplateDoesNotExist: public/landing.html
ERROR 2025-06-03 13:11:41,902 basehttp 5632 13892 "GET / HTTP/1.1" 500 101767
INFO 2025-06-03 13:11:59,216 basehttp 5632 13892 "GET /auth/profile/ HTTP/1.1" 200 12561
WARNING 2025-06-03 13:11:59,255 basehttp 5632 14112 "GET /static/css/dashboard.css HTTP/1.1" 404 1978
WARNING 2025-06-03 13:11:59,256 basehttp 5632 13892 "GET /static/css/custom.css HTTP/1.1" 404 1969
ERROR 2025-06-03 13:12:04,200 log 5632 3968 Internal Server Error: /auth/dashboard/
Traceback (most recent call last):
  File "D:\WORK PROJECTS\Autowash Build\autowash\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "D:\WORK PROJECTS\Autowash Build\autowash\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\WORK PROJECTS\Autowash Build\autowash\venv\Lib\site-packages\django\contrib\auth\decorators.py", line 59, in _view_wrapper
    return view_func(request, *args, **kwargs)
  File "D:\WORK PROJECTS\Autowash Build\autowash\apps\accounts\views.py", line 289, in dashboard_redirect
    return redirect('subscriptions:plans')
  File "D:\WORK PROJECTS\Autowash Build\autowash\venv\Lib\site-packages\django\shortcuts.py", line 51, in redirect
    resolve_url(to, *args, **kwargs),
    ~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^
  File "D:\WORK PROJECTS\Autowash Build\autowash\venv\Lib\site-packages\django\shortcuts.py", line 184, in resolve_url
    return reverse(to, args=args, kwargs=kwargs)
  File "D:\WORK PROJECTS\Autowash Build\autowash\venv\Lib\site-packages\django\urls\base.py", line 98, in reverse
    resolved_url = resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
  File "D:\WORK PROJECTS\Autowash Build\autowash\venv\Lib\site-packages\django\urls\resolvers.py", line 831, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'plans' not found. 'plans' is not a valid view function or pattern name.
ERROR 2025-06-03 13:12:04,205 basehttp 5632 3968 "GET /auth/dashboard/ HTTP/1.1" 500 109445
INFO 2025-06-03 13:16:51,440 autoreload 5632 14860 D:\WORK PROJECTS\Autowash Build\autowash\apps\subscriptions\urls.py changed, reloading.
INFO 2025-06-03 13:16:55,821 autoreload 20140 13720 Watching for file changes with StatReloader
ERROR 2025-06-03 13:17:42,299 log 20140 3356 Internal Server Error: /auth/dashboard/
Traceback (most recent call last):
  File "D:\WORK PROJECTS\Autowash Build\autowash\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "D:\WORK PROJECTS\Autowash Build\autowash\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\WORK PROJECTS\Autowash Build\autowash\venv\Lib\site-packages\django\contrib\auth\decorators.py", line 59, in _view_wrapper
    return view_func(request, *args, **kwargs)
  File "D:\WORK PROJECTS\Autowash Build\autowash\apps\accounts\views.py", line 289, in dashboard_redirect
    return redirect('subscriptions:plans')
  File "D:\WORK PROJECTS\Autowash Build\autowash\venv\Lib\site-packages\django\shortcuts.py", line 51, in redirect
    resolve_url(to, *args, **kwargs),
    ~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^
  File "D:\WORK PROJECTS\Autowash Build\autowash\venv\Lib\site-packages\django\shortcuts.py", line 184, in resolve_url
    return reverse(to, args=args, kwargs=kwargs)
  File "D:\WORK PROJECTS\Autowash Build\autowash\venv\Lib\site-packages\django\urls\base.py", line 98, in reverse
    resolved_url = resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
  File "D:\WORK PROJECTS\Autowash Build\autowash\venv\Lib\site-packages\django\urls\resolvers.py", line 831, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'plans' not found. 'plans' is not a valid view function or pattern name.
ERROR 2025-06-03 13:17:42,307 basehttp 20140 3356 "GET /auth/dashboard/ HTTP/1.1" 500 109563
INFO 2025-06-03 13:18:02,167 autoreload 20140 13720 D:\WORK PROJECTS\Autowash Build\autowash\apps\subscriptions\urls.py changed, reloading.
INFO 2025-06-03 13:18:06,740 autoreload 14544 15292 Watching for file changes with StatReloader
INFO 2025-06-03 13:18:08,020 basehttp 14544 11464 "GET /auth/dashboard/ HTTP/1.1" 302 0
ERROR 2025-06-03 13:18:08,299 log 14544 11464 Internal Server Error: /subscriptions/
Traceback (most recent call last):
  File "D:\WORK PROJECTS\Autowash Build\autowash\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "D:\WORK PROJECTS\Autowash Build\autowash\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\WORK PROJECTS\Autowash Build\autowash\apps\subscriptions\views.py", line 52, in pricing_view
    return render(request, 'subscriptions/pricing.html', context)
  File "D:\WORK PROJECTS\Autowash Build\autowash\venv\Lib\site-packages\django\shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "D:\WORK PROJECTS\Autowash Build\autowash\venv\Lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "D:\WORK PROJECTS\Autowash Build\autowash\venv\Lib\site-packages\django\template\loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: subscriptions/pricing.html
ERROR 2025-06-03 13:18:08,308 basehttp 14544 11464 "GET /subscriptions/ HTTP/1.1" 500 103821
INFO 2025-06-03 13:18:31,222 basehttp 14544 11464 "GET /auth/profile/ HTTP/1.1" 200 13527
INFO 2025-06-03 13:18:37,534 basehttp 14544 11464 "GET /auth/logout/ HTTP/1.1" 302 0
ERROR 2025-06-03 13:18:37,642 log 14544 11464 Internal Server Error: /
Traceback (most recent call last):
  File "D:\WORK PROJECTS\Autowash Build\autowash\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "D:\WORK PROJECTS\Autowash Build\autowash\venv\Lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
  File "D:\WORK PROJECTS\Autowash Build\autowash\venv\Lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "D:\WORK PROJECTS\Autowash Build\autowash\venv\Lib\site-packages\django\template\response.py", line 90, in rendered_content
    template = self.resolve_template(self.template_name)
  File "D:\WORK PROJECTS\Autowash Build\autowash\venv\Lib\site-packages\django\template\response.py", line 72, in resolve_template
    return select_template(template, using=self.using)
  File "D:\WORK PROJECTS\Autowash Build\autowash\venv\Lib\site-packages\django\template\loader.py", line 47, in select_template
    raise TemplateDoesNotExist(", ".join(template_name_list), chain=chain)
django.template.exceptions.TemplateDoesNotExist: public/landing.html
ERROR 2025-06-03 13:18:37,644 basehttp 14544 11464 "GET / HTTP/1.1" 500 101874
INFO 2025-06-03 13:18:41,751 basehttp 14544 11464 "GET /auth/profile/ HTTP/1.1" 302 0
INFO 2025-06-03 13:18:41,929 basehttp 14544 11464 "GET /auth/login/?next=/auth/profile/ HTTP/1.1" 200 12938
WARNING 2025-06-03 13:18:41,956 basehttp 14544 11464 "GET /static/css/custom.css HTTP/1.1" 404 1969
WARNING 2025-06-03 13:18:41,957 basehttp 14544 14184 "GET /static/css/dashboard.css HTTP/1.1" 404 1978
INFO 2025-06-03 13:18:44,519 basehttp 14544 23240 "GET /auth/register/ HTTP/1.1" 200 12570
WARNING 2025-06-03 13:18:44,554 basehttp 14544 23240 "GET /static/css/custom.css HTTP/1.1" 404 1969
WARNING 2025-06-03 13:18:44,559 basehttp 14544 21208 "GET /static/css/dashboard.css HTTP/1.1" 404 1978
INFO 2025-06-03 13:19:06,108 basehttp 14544 18064 "GET /auth/login/ HTTP/1.1" 200 12567
WARNING 2025-06-03 13:19:06,151 basehttp 14544 17292 "GET /static/css/dashboard.css HTTP/1.1" 404 1978
WARNING 2025-06-03 13:19:06,151 basehttp 14544 18064 "GET /static/css/custom.css HTTP/1.1" 404 1969
ERROR 2025-06-03 13:19:11,523 log 14544 5260 Internal Server Error: /
Traceback (most recent call last):
  File "D:\WORK PROJECTS\Autowash Build\autowash\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "D:\WORK PROJECTS\Autowash Build\autowash\venv\Lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
  File "D:\WORK PROJECTS\Autowash Build\autowash\venv\Lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "D:\WORK PROJECTS\Autowash Build\autowash\venv\Lib\site-packages\django\template\response.py", line 90, in rendered_content
    template = self.resolve_template(self.template_name)
  File "D:\WORK PROJECTS\Autowash Build\autowash\venv\Lib\site-packages\django\template\response.py", line 72, in resolve_template
    return select_template(template, using=self.using)
  File "D:\WORK PROJECTS\Autowash Build\autowash\venv\Lib\site-packages\django\template\loader.py", line 47, in select_template
    raise TemplateDoesNotExist(", ".join(template_name_list), chain=chain)
django.template.exceptions.TemplateDoesNotExist: public/landing.html
ERROR 2025-06-03 13:19:11,525 basehttp 14544 5260 "GET / HTTP/1.1" 500 101601
INFO 2025-06-03 13:20:18,931 basehttp 14544 5260 "GET /auth/register/ HTTP/1.1" 200 12570
WARNING 2025-06-03 13:20:18,962 basehttp 14544 5260 "GET /static/css/custom.css HTTP/1.1" 404 1969
WARNING 2025-06-03 13:20:18,972 basehttp 14544 23020 "GET /static/css/dashboard.css HTTP/1.1" 404 1978
ERROR 2025-06-03 13:20:20,829 log 14544 4372 Internal Server Error: /pricing/
Traceback (most recent call last):
  File "D:\WORK PROJECTS\Autowash Build\autowash\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "D:\WORK PROJECTS\Autowash Build\autowash\venv\Lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
  File "D:\WORK PROJECTS\Autowash Build\autowash\venv\Lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "D:\WORK PROJECTS\Autowash Build\autowash\venv\Lib\site-packages\django\template\response.py", line 90, in rendered_content
    template = self.resolve_template(self.template_name)
  File "D:\WORK PROJECTS\Autowash Build\autowash\venv\Lib\site-packages\django\template\response.py", line 72, in resolve_template
    return select_template(template, using=self.using)
  File "D:\WORK PROJECTS\Autowash Build\autowash\venv\Lib\site-packages\django\template\loader.py", line 47, in select_template
    raise TemplateDoesNotExist(", ".join(template_name_list), chain=chain)
django.template.exceptions.TemplateDoesNotExist: public/pricing.html
ERROR 2025-06-03 13:20:20,831 basehttp 14544 4372 "GET /pricing/ HTTP/1.1" 500 101676
ERROR 2025-06-03 13:20:25,741 log 14544 4372 Internal Server Error: /
Traceback (most recent call last):
  File "D:\WORK PROJECTS\Autowash Build\autowash\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "D:\WORK PROJECTS\Autowash Build\autowash\venv\Lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
  File "D:\WORK PROJECTS\Autowash Build\autowash\venv\Lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "D:\WORK PROJECTS\Autowash Build\autowash\venv\Lib\site-packages\django\template\response.py", line 90, in rendered_content
    template = self.resolve_template(self.template_name)
  File "D:\WORK PROJECTS\Autowash Build\autowash\venv\Lib\site-packages\django\template\response.py", line 72, in resolve_template
    return select_template(template, using=self.using)
  File "D:\WORK PROJECTS\Autowash Build\autowash\venv\Lib\site-packages\django\template\loader.py", line 47, in select_template
    raise TemplateDoesNotExist(", ".join(template_name_list), chain=chain)
django.template.exceptions.TemplateDoesNotExist: public/landing.html
ERROR 2025-06-03 13:20:25,743 basehttp 14544 4372 "GET / HTTP/1.1" 500 101604
INFO 2025-06-03 14:31:37,737 basehttp 14544 22116 "GET /auth/register/ HTTP/1.1" 200 12570
WARNING 2025-06-03 14:31:37,769 basehttp 14544 22116 "GET /static/css/custom.css HTTP/1.1" 404 1969
WARNING 2025-06-03 14:31:37,769 basehttp 14544 10268 "GET /static/css/dashboard.css HTTP/1.1" 404 1978
ERROR 2025-06-03 14:31:39,436 log 14544 13672 Internal Server Error: /auth/login/
Traceback (most recent call last):
  File "D:\WORK PROJECTS\Autowash Build\autowash\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "D:\WORK PROJECTS\Autowash Build\autowash\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\WORK PROJECTS\Autowash Build\autowash\apps\accounts\views.py", line 112, in login_view
    return render(request, 'auth/login.html')
  File "D:\WORK PROJECTS\Autowash Build\autowash\venv\Lib\site-packages\django\shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "D:\WORK PROJECTS\Autowash Build\autowash\venv\Lib\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^
  File "D:\WORK PROJECTS\Autowash Build\autowash\venv\Lib\site-packages\django\template\backends\django.py", line 107, in render
    return self.template.render(context)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "D:\WORK PROJECTS\Autowash Build\autowash\venv\Lib\site-packages\django\template\base.py", line 171, in render
    return self._render(context)
           ~~~~~~~~~~~~^^^^^^^^^
  File "D:\WORK PROJECTS\Autowash Build\autowash\venv\Lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "D:\WORK PROJECTS\Autowash Build\autowash\venv\Lib\site-packages\django\template\base.py", line 1016, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "D:\WORK PROJECTS\Autowash Build\autowash\venv\Lib\site-packages\django\template\base.py", line 977, in render_annotated
    return self.render(context)
           ~~~~~~~~~~~^^^^^^^^^
  File "D:\WORK PROJECTS\Autowash Build\autowash\venv\Lib\site-packages\django\template\defaulttags.py", line 480, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
  File "D:\WORK PROJECTS\Autowash Build\autowash\venv\Lib\site-packages\django\urls\base.py", line 98, in reverse
    resolved_url = resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
  File "D:\WORK PROJECTS\Autowash Build\autowash\venv\Lib\site-packages\django\urls\resolvers.py", line 831, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'password_reset' not found. 'password_reset' is not a valid view function or pattern name.
ERROR 2025-06-03 14:31:39,444 basehttp 14544 13672 "GET /auth/login/ HTTP/1.1" 500 136255
INFO 2025-06-03 14:33:08,268 basehttp 14544 13672 "GET /auth/login/ HTTP/1.1" 200 4178
ERROR 2025-06-03 14:33:22,717 log 14544 13672 Internal Server Error: /auth/login/
Traceback (most recent call last):
  File "D:\WORK PROJECTS\Autowash Build\autowash\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "D:\WORK PROJECTS\Autowash Build\autowash\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\WORK PROJECTS\Autowash Build\autowash\apps\accounts\views.py", line 108, in login_view
    return redirect(next_url)
  File "D:\WORK PROJECTS\Autowash Build\autowash\venv\Lib\site-packages\django\shortcuts.py", line 51, in redirect
    resolve_url(to, *args, **kwargs),
    ~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^
  File "D:\WORK PROJECTS\Autowash Build\autowash\venv\Lib\site-packages\django\shortcuts.py", line 184, in resolve_url
    return reverse(to, args=args, kwargs=kwargs)
  File "D:\WORK PROJECTS\Autowash Build\autowash\venv\Lib\site-packages\django\urls\base.py", line 98, in reverse
    resolved_url = resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
  File "D:\WORK PROJECTS\Autowash Build\autowash\venv\Lib\site-packages\django\urls\resolvers.py", line 831, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'dashboard' not found. 'dashboard' is not a valid view function or pattern name.
ERROR 2025-06-03 14:33:22,721 basehttp 14544 13672 "POST /auth/login/ HTTP/1.1" 500 104969
INFO 2025-06-03 14:33:32,072 basehttp 14544 13672 "GET /auth/login/ HTTP/1.1" 200 4634
INFO 2025-06-03 14:33:38,163 basehttp 14544 13672 "GET /auth/profile/ HTTP/1.1" 302 0
INFO 2025-06-03 14:33:38,235 basehttp 14544 13672 "GET /auth/login/?next=/auth/profile/ HTTP/1.1" 200 4178
INFO 2025-06-03 14:33:45,592 basehttp 14544 13672 "GET /auth/login/?next=/auth/profile/ HTTP/1.1" 200 4178
INFO 2025-06-03 14:34:12,042 basehttp 14544 13672 "GET /auth/login/?next=/auth/profile/ HTTP/1.1" 200 5055
INFO 2025-06-03 14:34:15,570 basehttp 14544 13672 "GET /accounts/signup/ HTTP/1.1" 200 2510
INFO 2025-06-03 14:34:34,683 basehttp 14544 13672 "GET /auth/profile/ HTTP/1.1" 302 0
INFO 2025-06-03 14:34:34,849 basehttp 14544 13672 "GET /auth/login/?next=/auth/profile/ HTTP/1.1" 200 5055
INFO 2025-06-03 14:34:40,188 basehttp 14544 13672 "GET /system-admin/account/emailaddress/ HTTP/1.1" 302 0
INFO 2025-06-03 14:34:40,371 basehttp 14544 13672 "GET /system-admin/login/?next=/system-admin/account/emailaddress/ HTTP/1.1" 200 4244
INFO 2025-06-03 14:34:40,393 basehttp 14544 13672 "GET /static/admin/css/base.css HTTP/1.1" 304 0
INFO 2025-06-03 14:34:40,393 basehttp 14544 14460 "GET /static/admin/css/dark_mode.css HTTP/1.1" 304 0
INFO 2025-06-03 14:34:40,395 basehttp 14544 2200 "GET /static/admin/css/login.css HTTP/1.1" 304 0
INFO 2025-06-03 14:34:40,396 basehttp 14544 20760 "GET /static/admin/css/responsive.css HTTP/1.1" 304 0
INFO 2025-06-03 14:34:40,396 basehttp 14544 22624 "GET /static/admin/css/nav_sidebar.css HTTP/1.1" 304 0
INFO 2025-06-03 14:34:40,397 basehttp 14544 6660 "GET /static/admin/js/theme.js HTTP/1.1" 304 0
INFO 2025-06-03 14:34:40,403 basehttp 14544 6660 "GET /static/admin/js/nav_sidebar.js HTTP/1.1" 304 0
INFO 2025-06-03 14:34:45,491 basehttp 14544 6660 "GET /accounts/signup/ HTTP/1.1" 200 2510
ERROR 2025-06-03 14:35:12,246 log 14544 6660 Internal Server Error: /accounts/signup/
Traceback (most recent call last):
  File "D:\WORK PROJECTS\Autowash Build\autowash\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "D:\WORK PROJECTS\Autowash Build\autowash\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\WORK PROJECTS\Autowash Build\autowash\venv\Lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\WORK PROJECTS\Autowash Build\autowash\venv\Lib\site-packages\django\utils\decorators.py", line 48, in _wrapper
    return bound_method(*args, **kwargs)
  File "D:\WORK PROJECTS\Autowash Build\autowash\venv\Lib\site-packages\allauth\decorators.py", line 12, in wrap
    resp = function(request, *args, **kwargs)
  File "D:\WORK PROJECTS\Autowash Build\autowash\venv\Lib\site-packages\django\utils\decorators.py", line 48, in _wrapper
    return bound_method(*args, **kwargs)
  File "D:\WORK PROJECTS\Autowash Build\autowash\venv\Lib\site-packages\django\utils\decorators.py", line 48, in _wrapper
    return bound_method(*args, **kwargs)
  File "D:\WORK PROJECTS\Autowash Build\autowash\venv\Lib\site-packages\django\views\decorators\debug.py", line 143, in sensitive_post_parameters_wrapper
    return view(request, *args, **kwargs)
  File "D:\WORK PROJECTS\Autowash Build\autowash\venv\Lib\site-packages\django\utils\decorators.py", line 48, in _wrapper
    return bound_method(*args, **kwargs)
  File "D:\WORK PROJECTS\Autowash Build\autowash\venv\Lib\site-packages\django\views\decorators\cache.py", line 80, in _view_wrapper
    response = view_func(request, *args, **kwargs)
  File "D:\WORK PROJECTS\Autowash Build\autowash\venv\Lib\site-packages\allauth\account\views.py", line 164, in dispatch
    return super().dispatch(request, *args, **kwargs)
           ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\WORK PROJECTS\Autowash Build\autowash\venv\Lib\site-packages\django\utils\decorators.py", line 48, in _wrapper
    return bound_method(*args, **kwargs)
  File "D:\WORK PROJECTS\Autowash Build\autowash\venv\Lib\site-packages\django\utils\decorators.py", line 48, in _wrapper
    return bound_method(*args, **kwargs)
  File "D:\WORK PROJECTS\Autowash Build\autowash\venv\Lib\site-packages\django\views\decorators\cache.py", line 80, in _view_wrapper
    response = view_func(request, *args, **kwargs)
  File "D:\WORK PROJECTS\Autowash Build\autowash\venv\Lib\site-packages\allauth\account\mixins.py", line 53, in dispatch
    response = super().dispatch(request, *args, **kwargs)
  File "D:\WORK PROJECTS\Autowash Build\autowash\venv\Lib\site-packages\allauth\account\mixins.py", line 118, in dispatch
    return super().dispatch(request, *args, **kwargs)
           ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\WORK PROJECTS\Autowash Build\autowash\venv\Lib\site-packages\django\views\generic\base.py", line 143, in dispatch
    return handler(request, *args, **kwargs)
  File "D:\WORK PROJECTS\Autowash Build\autowash\venv\Lib\site-packages\allauth\account\mixins.py", line 82, in post
    response = self.form_valid(form)
  File "D:\WORK PROJECTS\Autowash Build\autowash\venv\Lib\site-packages\allauth\account\views.py", line 175, in form_valid
    return flows.signup.complete_signup(
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
        self.request,
        ^^^^^^^^^^^^^
    ...<2 lines>...
        by_passkey=form.by_passkey,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "D:\WORK PROJECTS\Autowash Build\autowash\venv\Lib\site-packages\allauth\account\internal\flows\signup.py", line 114, in complete_signup
    return perform_login(request, login)
  File "D:\WORK PROJECTS\Autowash Build\autowash\venv\Lib\site-packages\allauth\account\internal\flows\login.py", line 89, in perform_login
    return resume_login(request, login)
  File "D:\WORK PROJECTS\Autowash Build\autowash\venv\Lib\site-packages\allauth\account\internal\flows\login.py", line 98, in resume_login
    response = ctrl.handle()
  File "D:\WORK PROJECTS\Autowash Build\autowash\venv\Lib\site-packages\allauth\account\stages.py", line 112, in handle
    response, cont = stage.handle()
                     ~~~~~~~~~~~~^^
  File "D:\WORK PROJECTS\Autowash Build\autowash\venv\Lib\site-packages\allauth\account\stages.py", line 151, in handle
    send_email_confirmation(
    ~~~~~~~~~~~~~~~~~~~~~~~^
        self.request, login.user, signup=login.signup, email=login.email
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "D:\WORK PROJECTS\Autowash Build\autowash\venv\Lib\site-packages\allauth\account\utils.py", line 222, in send_email_confirmation
    return flows.email_verification.send_verification_email(
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
        request, user, signup=signup, email=email
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "D:\WORK PROJECTS\Autowash Build\autowash\venv\Lib\site-packages\allauth\account\internal\flows\email_verification.py", line 263, in send_verification_email
    email_address.send_confirmation(request, signup=signup)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\WORK PROJECTS\Autowash Build\autowash\venv\Lib\site-packages\allauth\account\models.py", line 107, in send_confirmation
    confirmation.send(request, signup=signup)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\WORK PROJECTS\Autowash Build\autowash\venv\Lib\site-packages\allauth\account\models.py", line 136, in send
    get_adapter().send_confirmation_mail(request, self, signup)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\WORK PROJECTS\Autowash Build\autowash\venv\Lib\site-packages\allauth\account\adapter.py", line 671, in send_confirmation_mail
    self.send_mail(email_template, emailconfirmation.email_address.email, ctx)
    ~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\WORK PROJECTS\Autowash Build\autowash\venv\Lib\site-packages\allauth\account\adapter.py", line 214, in send_mail
    msg.send()
    ~~~~~~~~^^
  File "D:\WORK PROJECTS\Autowash Build\autowash\venv\Lib\site-packages\django\core\mail\message.py", line 307, in send
    return self.get_connection(fail_silently).send_messages([self])
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^
  File "D:\WORK PROJECTS\Autowash Build\autowash\venv\Lib\site-packages\django\core\mail\backends\smtp.py", line 128, in send_messages
    new_conn_created = self.open()
  File "D:\WORK PROJECTS\Autowash Build\autowash\venv\Lib\site-packages\django\core\mail\backends\smtp.py", line 95, in open
    self.connection.login(self.username, self.password)
    ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Brandon\AppData\Local\Programs\Python\Python313\Lib\smtplib.py", line 750, in login
    raise last_exception
  File "C:\Users\Brandon\AppData\Local\Programs\Python\Python313\Lib\smtplib.py", line 739, in login
    (code, resp) = self.auth(
                   ~~~~~~~~~^
        authmethod, getattr(self, method_name),
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        initial_response_ok=initial_response_ok)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Brandon\AppData\Local\Programs\Python\Python313\Lib\smtplib.py", line 662, in auth
    raise SMTPAuthenticationError(code, resp)
smtplib.SMTPAuthenticationError: (535, b'5.7.8 Username and Password not accepted. For more information, go to\n5.7.8  https://support.google.com/mail/?p=BadCredentials 5b1f17b1804b1-450d7f8f194sm160116215e9.4 - gsmtp')
ERROR 2025-06-03 14:35:12,264 basehttp 14544 6660 "POST /accounts/signup/ HTTP/1.1" 500 244948
INFO 2025-06-03 14:35:30,506 basehttp 14544 6660 "GET /auth/profile/ HTTP/1.1" 302 0
INFO 2025-06-03 14:35:30,572 basehttp 14544 6660 "GET /auth/login/?next=/auth/profile/ HTTP/1.1" 200 5055
INFO 2025-06-03 14:35:47,418 basehttp 14544 6660 "POST /accounts/login/ HTTP/1.1" 200 2441
INFO 2025-06-03 14:35:59,420 basehttp 14544 6660 "POST /accounts/login/ HTTP/1.1" 200 2441
INFO 2025-06-03 14:36:55,537 basehttp 14544 6660 "GET /accounts/login/ HTTP/1.1" 200 2289
ERROR 2025-06-03 14:37:03,235 log 14544 6660 Internal Server Error: /
Traceback (most recent call last):
  File "D:\WORK PROJECTS\Autowash Build\autowash\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "D:\WORK PROJECTS\Autowash Build\autowash\venv\Lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
  File "D:\WORK PROJECTS\Autowash Build\autowash\venv\Lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "D:\WORK PROJECTS\Autowash Build\autowash\venv\Lib\site-packages\django\template\response.py", line 90, in rendered_content
    template = self.resolve_template(self.template_name)
  File "D:\WORK PROJECTS\Autowash Build\autowash\venv\Lib\site-packages\django\template\response.py", line 72, in resolve_template
    return select_template(template, using=self.using)
  File "D:\WORK PROJECTS\Autowash Build\autowash\venv\Lib\site-packages\django\template\loader.py", line 47, in select_template
    raise TemplateDoesNotExist(", ".join(template_name_list), chain=chain)
django.template.exceptions.TemplateDoesNotExist: public/landing.html
ERROR 2025-06-03 14:37:03,237 basehttp 14544 6660 "GET / HTTP/1.1" 500 101439
WARNING 2025-06-03 14:37:11,414 log 14544 6660 Not Found: /login
WARNING 2025-06-03 14:37:11,415 basehttp 14544 6660 "GET /login HTTP/1.1" 404 3664
INFO 2025-06-03 14:37:21,119 basehttp 14544 6660 "GET /auth/profile/ HTTP/1.1" 302 0
INFO 2025-06-03 14:37:21,203 basehttp 14544 6660 "GET /auth/login/?next=/auth/profile/ HTTP/1.1" 200 12567
WARNING 2025-06-03 14:37:21,227 basehttp 14544 6660 "GET /static/css/custom.css HTTP/1.1" 404 1969
WARNING 2025-06-03 14:37:21,228 basehttp 14544 2200 "GET /static/css/dashboard.css HTTP/1.1" 404 1978
INFO 2025-06-03 14:37:23,223 basehttp 14544 20760 "GET /auth/register/ HTTP/1.1" 200 12570
WARNING 2025-06-03 14:37:23,250 basehttp 14544 20760 "GET /static/css/custom.css HTTP/1.1" 404 1969
WARNING 2025-06-03 14:37:23,257 basehttp 14544 22624 "GET /static/css/dashboard.css HTTP/1.1" 404 1978
INFO 2025-06-03 14:38:33,711 basehttp 14544 14460 "GET /auth/register/ HTTP/1.1" 200 12570
WARNING 2025-06-03 14:38:33,731 basehttp 14544 14460 "GET /static/css/custom.css HTTP/1.1" 404 1969
WARNING 2025-06-03 14:38:33,731 basehttp 14544 13672 "GET /static/css/dashboard.css HTTP/1.1" 404 1978
INFO 2025-06-03 15:06:13,779 basehttp 14544 22632 "GET /system-admin/auth/user/1/change/ HTTP/1.1" 302 0
INFO 2025-06-03 15:06:13,879 basehttp 14544 22632 "GET /system-admin/login/?next=/system-admin/auth/user/1/change/ HTTP/1.1" 200 4240
INFO 2025-06-03 15:06:15,212 basehttp 14544 22632 "GET /system-admin/auth/user/ HTTP/1.1" 302 0
INFO 2025-06-03 15:06:15,386 basehttp 14544 22632 "GET /system-admin/login/?next=/system-admin/auth/user/ HTTP/1.1" 200 4222
ERROR 2025-06-03 15:06:24,849 log 14544 22632 Internal Server Error: /
Traceback (most recent call last):
  File "D:\WORK PROJECTS\Autowash Build\autowash\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "D:\WORK PROJECTS\Autowash Build\autowash\venv\Lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
  File "D:\WORK PROJECTS\Autowash Build\autowash\venv\Lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "D:\WORK PROJECTS\Autowash Build\autowash\venv\Lib\site-packages\django\template\response.py", line 90, in rendered_content
    template = self.resolve_template(self.template_name)
  File "D:\WORK PROJECTS\Autowash Build\autowash\venv\Lib\site-packages\django\template\response.py", line 72, in resolve_template
    return select_template(template, using=self.using)
  File "D:\WORK PROJECTS\Autowash Build\autowash\venv\Lib\site-packages\django\template\loader.py", line 47, in select_template
    raise TemplateDoesNotExist(", ".join(template_name_list), chain=chain)
django.template.exceptions.TemplateDoesNotExist: public/landing.html
ERROR 2025-06-03 15:06:24,852 basehttp 14544 22632 "GET / HTTP/1.1" 500 101439
ERROR 2025-06-03 15:09:23,719 log 14544 22632 Internal Server Error: /
Traceback (most recent call last):
  File "D:\WORK PROJECTS\Autowash Build\autowash\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "D:\WORK PROJECTS\Autowash Build\autowash\venv\Lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
  File "D:\WORK PROJECTS\Autowash Build\autowash\venv\Lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "D:\WORK PROJECTS\Autowash Build\autowash\venv\Lib\site-packages\django\template\response.py", line 90, in rendered_content
    template = self.resolve_template(self.template_name)
  File "D:\WORK PROJECTS\Autowash Build\autowash\venv\Lib\site-packages\django\template\response.py", line 72, in resolve_template
    return select_template(template, using=self.using)
  File "D:\WORK PROJECTS\Autowash Build\autowash\venv\Lib\site-packages\django\template\loader.py", line 47, in select_template
    raise TemplateDoesNotExist(", ".join(template_name_list), chain=chain)
django.template.exceptions.TemplateDoesNotExist: public/landing.html
ERROR 2025-06-03 15:09:23,723 basehttp 14544 22632 "GET / HTTP/1.1" 500 101439
ERROR 2025-06-03 15:09:26,787 log 14544 22632 Internal Server Error: /
Traceback (most recent call last):
  File "D:\WORK PROJECTS\Autowash Build\autowash\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "D:\WORK PROJECTS\Autowash Build\autowash\venv\Lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
  File "D:\WORK PROJECTS\Autowash Build\autowash\venv\Lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "D:\WORK PROJECTS\Autowash Build\autowash\venv\Lib\site-packages\django\template\response.py", line 90, in rendered_content
    template = self.resolve_template(self.template_name)
  File "D:\WORK PROJECTS\Autowash Build\autowash\venv\Lib\site-packages\django\template\response.py", line 72, in resolve_template
    return select_template(template, using=self.using)
  File "D:\WORK PROJECTS\Autowash Build\autowash\venv\Lib\site-packages\django\template\loader.py", line 47, in select_template
    raise TemplateDoesNotExist(", ".join(template_name_list), chain=chain)
django.template.exceptions.TemplateDoesNotExist: public/landing.html
ERROR 2025-06-03 15:09:26,790 basehttp 14544 22632 "GET / HTTP/1.1" 500 101576
INFO 2025-06-03 15:09:28,501 basehttp 14544 22632 "GET /system-admin/login/?next=/system-admin/auth/user/ HTTP/1.1" 200 4222
INFO 2025-06-03 15:09:30,398 basehttp 14544 22632 "GET /system-admin/subscriptions/subscriptionplan/ HTTP/1.1" 302 0
INFO 2025-06-03 15:09:30,480 basehttp 14544 22632 "GET /system-admin/login/?next=/system-admin/subscriptions/subscriptionplan/ HTTP/1.1" 200 4264
ERROR 2025-06-03 15:09:34,022 log 14544 22632 Internal Server Error: /
Traceback (most recent call last):
  File "D:\WORK PROJECTS\Autowash Build\autowash\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "D:\WORK PROJECTS\Autowash Build\autowash\venv\Lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
  File "D:\WORK PROJECTS\Autowash Build\autowash\venv\Lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "D:\WORK PROJECTS\Autowash Build\autowash\venv\Lib\site-packages\django\template\response.py", line 90, in rendered_content
    template = self.resolve_template(self.template_name)
  File "D:\WORK PROJECTS\Autowash Build\autowash\venv\Lib\site-packages\django\template\response.py", line 72, in resolve_template
    return select_template(template, using=self.using)
  File "D:\WORK PROJECTS\Autowash Build\autowash\venv\Lib\site-packages\django\template\loader.py", line 47, in select_template
    raise TemplateDoesNotExist(", ".join(template_name_list), chain=chain)
django.template.exceptions.TemplateDoesNotExist: public/landing.html
ERROR 2025-06-03 15:09:34,025 basehttp 14544 22632 "GET / HTTP/1.1" 500 101439
ERROR 2025-06-03 15:12:40,199 log 14544 22632 Internal Server Error: /
Traceback (most recent call last):
  File "D:\WORK PROJECTS\Autowash Build\autowash\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "D:\WORK PROJECTS\Autowash Build\autowash\venv\Lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
  File "D:\WORK PROJECTS\Autowash Build\autowash\venv\Lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "D:\WORK PROJECTS\Autowash Build\autowash\venv\Lib\site-packages\django\template\response.py", line 90, in rendered_content
    template = self.resolve_template(self.template_name)
  File "D:\WORK PROJECTS\Autowash Build\autowash\venv\Lib\site-packages\django\template\response.py", line 72, in resolve_template
    return select_template(template, using=self.using)
  File "D:\WORK PROJECTS\Autowash Build\autowash\venv\Lib\site-packages\django\template\loader.py", line 47, in select_template
    raise TemplateDoesNotExist(", ".join(template_name_list), chain=chain)
django.template.exceptions.TemplateDoesNotExist: public/landing.html
ERROR 2025-06-03 15:12:40,202 basehttp 14544 22632 "GET / HTTP/1.1" 500 101439
ERROR 2025-06-03 15:12:42,992 log 14544 22632 Internal Server Error: /
Traceback (most recent call last):
  File "D:\WORK PROJECTS\Autowash Build\autowash\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "D:\WORK PROJECTS\Autowash Build\autowash\venv\Lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
  File "D:\WORK PROJECTS\Autowash Build\autowash\venv\Lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "D:\WORK PROJECTS\Autowash Build\autowash\venv\Lib\site-packages\django\template\response.py", line 90, in rendered_content
    template = self.resolve_template(self.template_name)
  File "D:\WORK PROJECTS\Autowash Build\autowash\venv\Lib\site-packages\django\template\response.py", line 72, in resolve_template
    return select_template(template, using=self.using)
  File "D:\WORK PROJECTS\Autowash Build\autowash\venv\Lib\site-packages\django\template\loader.py", line 47, in select_template
    raise TemplateDoesNotExist(", ".join(template_name_list), chain=chain)
django.template.exceptions.TemplateDoesNotExist: public/landing.html
ERROR 2025-06-03 15:12:42,995 basehttp 14544 22632 "GET / HTTP/1.1" 500 101439
INFO 2025-06-03 15:12:44,604 basehttp 14544 22632 "GET /system-admin/login/?next=/system-admin/subscriptions/subscriptionplan/ HTTP/1.1" 200 4264
ERROR 2025-06-03 15:13:20,478 log 14544 22632 Internal Server Error: /
Traceback (most recent call last):
  File "D:\WORK PROJECTS\Autowash Build\autowash\venv\Lib\site-packages\django\template\backends\django.py", line 107, in render
    return self.template.render(context)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "D:\WORK PROJECTS\Autowash Build\autowash\venv\Lib\site-packages\django\template\base.py", line 171, in render
    return self._render(context)
           ~~~~~~~~~~~~^^^^^^^^^
  File "D:\WORK PROJECTS\Autowash Build\autowash\venv\Lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "D:\WORK PROJECTS\Autowash Build\autowash\venv\Lib\site-packages\django\template\base.py", line 1016, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "D:\WORK PROJECTS\Autowash Build\autowash\venv\Lib\site-packages\django\template\base.py", line 977, in render_annotated
    return self.render(context)
           ~~~~~~~~~~~^^^^^^^^^
  File "D:\WORK PROJECTS\Autowash Build\autowash\venv\Lib\site-packages\django\template\loader_tags.py", line 134, in render
    compiled_parent = self.get_parent(context)
  File "D:\WORK PROJECTS\Autowash Build\autowash\venv\Lib\site-packages\django\template\loader_tags.py", line 131, in get_parent
    return self.find_template(parent, context)
           ~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
  File "D:\WORK PROJECTS\Autowash Build\autowash\venv\Lib\site-packages\django\template\loader_tags.py", line 109, in find_template
    template, origin = context.template.engine.find_template(
                       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
        template_name,
        ^^^^^^^^^^^^^^
        skip=history,
        ^^^^^^^^^^^^^
    )
    ^
  File "D:\WORK PROJECTS\Autowash Build\autowash\venv\Lib\site-packages\django\template\engine.py", line 163, in find_template
    raise TemplateDoesNotExist(name, tried=tried)
django.template.exceptions.TemplateDoesNotExist: base.html

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\WORK PROJECTS\Autowash Build\autowash\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "D:\WORK PROJECTS\Autowash Build\autowash\venv\Lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
  File "D:\WORK PROJECTS\Autowash Build\autowash\venv\Lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "D:\WORK PROJECTS\Autowash Build\autowash\venv\Lib\site-packages\django\template\response.py", line 92, in rendered_content
    return template.render(context, self._request)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\WORK PROJECTS\Autowash Build\autowash\venv\Lib\site-packages\django\template\backends\django.py", line 109, in render
    reraise(exc, self.backend)
    ~~~~~~~^^^^^^^^^^^^^^^^^^^
  File "D:\WORK PROJECTS\Autowash Build\autowash\venv\Lib\site-packages\django\template\backends\django.py", line 130, in reraise
    raise new from exc
django.template.exceptions.TemplateDoesNotExist: base.html
ERROR 2025-06-03 15:13:20,488 basehttp 14544 22632 "GET / HTTP/1.1" 500 146905
ERROR 2025-06-03 15:13:21,063 log 14544 22632 Internal Server Error: /
Traceback (most recent call last):
  File "D:\WORK PROJECTS\Autowash Build\autowash\venv\Lib\site-packages\django\template\backends\django.py", line 107, in render
    return self.template.render(context)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "D:\WORK PROJECTS\Autowash Build\autowash\venv\Lib\site-packages\django\template\base.py", line 171, in render
    return self._render(context)
           ~~~~~~~~~~~~^^^^^^^^^
  File "D:\WORK PROJECTS\Autowash Build\autowash\venv\Lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "D:\WORK PROJECTS\Autowash Build\autowash\venv\Lib\site-packages\django\template\base.py", line 1016, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "D:\WORK PROJECTS\Autowash Build\autowash\venv\Lib\site-packages\django\template\base.py", line 977, in render_annotated
    return self.render(context)
           ~~~~~~~~~~~^^^^^^^^^
  File "D:\WORK PROJECTS\Autowash Build\autowash\venv\Lib\site-packages\django\template\loader_tags.py", line 134, in render
    compiled_parent = self.get_parent(context)
  File "D:\WORK PROJECTS\Autowash Build\autowash\venv\Lib\site-packages\django\template\loader_tags.py", line 131, in get_parent
    return self.find_template(parent, context)
           ~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
  File "D:\WORK PROJECTS\Autowash Build\autowash\venv\Lib\site-packages\django\template\loader_tags.py", line 109, in find_template
    template, origin = context.template.engine.find_template(
                       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
        template_name,
        ^^^^^^^^^^^^^^
        skip=history,
        ^^^^^^^^^^^^^
    )
    ^
  File "D:\WORK PROJECTS\Autowash Build\autowash\venv\Lib\site-packages\django\template\engine.py", line 163, in find_template
    raise TemplateDoesNotExist(name, tried=tried)
django.template.exceptions.TemplateDoesNotExist: base.html

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\WORK PROJECTS\Autowash Build\autowash\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "D:\WORK PROJECTS\Autowash Build\autowash\venv\Lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
  File "D:\WORK PROJECTS\Autowash Build\autowash\venv\Lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "D:\WORK PROJECTS\Autowash Build\autowash\venv\Lib\site-packages\django\template\response.py", line 92, in rendered_content
    return template.render(context, self._request)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\WORK PROJECTS\Autowash Build\autowash\venv\Lib\site-packages\django\template\backends\django.py", line 109, in render
    reraise(exc, self.backend)
    ~~~~~~~^^^^^^^^^^^^^^^^^^^
  File "D:\WORK PROJECTS\Autowash Build\autowash\venv\Lib\site-packages\django\template\backends\django.py", line 130, in reraise
    raise new from exc
django.template.exceptions.TemplateDoesNotExist: base.html
ERROR 2025-06-03 15:13:21,068 basehttp 14544 22632 "GET / HTTP/1.1" 500 146631
INFO 2025-06-03 15:26:26,375 basehttp 14544 19308 "GET / HTTP/1.1" 200 53991
WARNING 2025-06-03 15:26:26,410 basehttp 14544 19308 "GET /static/img/dashboard-preview.png HTTP/1.1" 404 2002
WARNING 2025-06-03 15:26:26,410 basehttp 14544 12656 "GET /static/css/custom.css HTTP/1.1" 404 1969
WARNING 2025-06-03 15:26:26,416 basehttp 14544 12992 "GET /static/css/dashboard.css HTTP/1.1" 404 1978
INFO 2025-06-03 15:26:35,403 basehttp 14544 14804 "GET /auth/register/ HTTP/1.1" 200 35297
WARNING 2025-06-03 15:26:35,443 basehttp 14544 14804 "GET /static/css/custom.css HTTP/1.1" 404 1969
WARNING 2025-06-03 15:26:35,453 basehttp 14544 21904 "GET /static/css/dashboard.css HTTP/1.1" 404 1978
INFO 2025-06-03 15:26:58,358 basehttp 14544 1456 "GET / HTTP/1.1" 200 53991
WARNING 2025-06-03 15:26:58,383 basehttp 14544 19892 "GET /static/css/dashboard.css HTTP/1.1" 404 1978
WARNING 2025-06-03 15:26:58,383 basehttp 14544 1456 "GET /static/css/custom.css HTTP/1.1" 404 1969
WARNING 2025-06-03 15:26:58,389 basehttp 14544 12080 "GET /static/img/dashboard-preview.png HTTP/1.1" 404 2002
ERROR 2025-06-03 15:27:01,412 log 14544 21388 Internal Server Error: /features/
Traceback (most recent call last):
  File "D:\WORK PROJECTS\Autowash Build\autowash\venv\Lib\site-packages\django\template\backends\django.py", line 107, in render
    return self.template.render(context)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "D:\WORK PROJECTS\Autowash Build\autowash\venv\Lib\site-packages\django\template\base.py", line 171, in render
    return self._render(context)
           ~~~~~~~~~~~~^^^^^^^^^
  File "D:\WORK PROJECTS\Autowash Build\autowash\venv\Lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "D:\WORK PROJECTS\Autowash Build\autowash\venv\Lib\site-packages\django\template\base.py", line 1016, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "D:\WORK PROJECTS\Autowash Build\autowash\venv\Lib\site-packages\django\template\base.py", line 977, in render_annotated
    return self.render(context)
           ~~~~~~~~~~~^^^^^^^^^
  File "D:\WORK PROJECTS\Autowash Build\autowash\venv\Lib\site-packages\django\template\loader_tags.py", line 134, in render
    compiled_parent = self.get_parent(context)
  File "D:\WORK PROJECTS\Autowash Build\autowash\venv\Lib\site-packages\django\template\loader_tags.py", line 131, in get_parent
    return self.find_template(parent, context)
           ~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
  File "D:\WORK PROJECTS\Autowash Build\autowash\venv\Lib\site-packages\django\template\loader_tags.py", line 109, in find_template
    template, origin = context.template.engine.find_template(
                       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
        template_name,
        ^^^^^^^^^^^^^^
        skip=history,
        ^^^^^^^^^^^^^
    )
    ^
  File "D:\WORK PROJECTS\Autowash Build\autowash\venv\Lib\site-packages\django\template\engine.py", line 163, in find_template
    raise TemplateDoesNotExist(name, tried=tried)
django.template.exceptions.TemplateDoesNotExist: base.html

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\WORK PROJECTS\Autowash Build\autowash\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "D:\WORK PROJECTS\Autowash Build\autowash\venv\Lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
  File "D:\WORK PROJECTS\Autowash Build\autowash\venv\Lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "D:\WORK PROJECTS\Autowash Build\autowash\venv\Lib\site-packages\django\template\response.py", line 92, in rendered_content
    return template.render(context, self._request)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\WORK PROJECTS\Autowash Build\autowash\venv\Lib\site-packages\django\template\backends\django.py", line 109, in render
    reraise(exc, self.backend)
    ~~~~~~~^^^^^^^^^^^^^^^^^^^
  File "D:\WORK PROJECTS\Autowash Build\autowash\venv\Lib\site-packages\django\template\backends\django.py", line 130, in reraise
    raise new from exc
django.template.exceptions.TemplateDoesNotExist: base.html
ERROR 2025-06-03 15:27:01,417 basehttp 14544 21388 "GET /features/ HTTP/1.1" 500 146909
INFO 2025-06-03 15:28:46,929 basehttp 14544 21388 "GET /features/ HTTP/1.1" 200 54008
WARNING 2025-06-03 15:28:46,958 basehttp 14544 22688 "GET /static/img/customer-management.png HTTP/1.1" 404 2008
WARNING 2025-06-03 15:28:46,965 basehttp 14544 21388 "GET /static/css/custom.css HTTP/1.1" 404 1969
WARNING 2025-06-03 15:28:46,974 basehttp 14544 14004 "GET /static/img/service-management.png HTTP/1.1" 404 2005
WARNING 2025-06-03 15:28:46,980 basehttp 14544 1672 "GET /static/img/analytics-dashboard.png HTTP/1.1" 404 2008
WARNING 2025-06-03 15:28:46,980 basehttp 14544 17476 "GET /static/css/dashboard.css HTTP/1.1" 404 1978
INFO 2025-06-03 15:29:12,718 basehttp 14544 18132 "GET /pricing/ HTTP/1.1" 200 61320
WARNING 2025-06-03 15:29:12,757 basehttp 14544 18132 "GET /static/css/custom.css HTTP/1.1" 404 1969
WARNING 2025-06-03 15:29:12,764 basehttp 14544 14100 "GET /static/css/dashboard.css HTTP/1.1" 404 1978
INFO 2025-06-03 15:29:27,275 basehttp 14544 5996 "GET /contact/ HTTP/1.1" 200 53764
WARNING 2025-06-03 15:29:27,307 basehttp 14544 5996 "GET /static/css/custom.css HTTP/1.1" 404 1969
WARNING 2025-06-03 15:29:27,313 basehttp 14544 6796 "GET /static/css/dashboard.css HTTP/1.1" 404 1978
INFO 2025-06-03 15:29:34,655 basehttp 14544 11004 "GET /auth/register/ HTTP/1.1" 200 35297
WARNING 2025-06-03 15:29:34,691 basehttp 14544 11004 "GET /static/css/custom.css HTTP/1.1" 404 1969
WARNING 2025-06-03 15:29:34,698 basehttp 14544 17560 "GET /static/css/dashboard.css HTTP/1.1" 404 1978
INFO 2025-06-03 15:29:58,104 basehttp 14544 24480 "GET /contact/ HTTP/1.1" 200 53764
WARNING 2025-06-03 15:29:58,129 basehttp 14544 24480 "GET /static/css/custom.css HTTP/1.1" 404 1969
WARNING 2025-06-03 15:29:58,134 basehttp 14544 13388 "GET /static/css/dashboard.css HTTP/1.1" 404 1978
INFO 2025-06-03 15:30:00,696 basehttp 14544 15884 "GET /auth/login/ HTTP/1.1" 200 43518
WARNING 2025-06-03 15:30:00,732 basehttp 14544 15884 "GET /static/css/custom.css HTTP/1.1" 404 1969
WARNING 2025-06-03 15:30:00,738 basehttp 14544 10104 "GET /static/css/dashboard.css HTTP/1.1" 404 1978
INFO 2025-06-03 15:30:15,654 basehttp 14544 7036 "GET /auth/register/ HTTP/1.1" 200 35297
WARNING 2025-06-03 15:30:15,700 basehttp 14544 12116 "GET /static/css/dashboard.css HTTP/1.1" 404 1978
WARNING 2025-06-03 15:30:15,700 basehttp 14544 7036 "GET /static/css/custom.css HTTP/1.1" 404 1969
INFO 2025-06-03 15:31:30,557 basehttp 14544 19588 "GET /auth/login/ HTTP/1.1" 200 43518
WARNING 2025-06-03 15:31:30,598 basehttp 14544 19588 "GET /static/css/custom.css HTTP/1.1" 404 1969
WARNING 2025-06-03 15:31:30,599 basehttp 14544 10448 "GET /static/css/dashboard.css HTTP/1.1" 404 1978
ERROR 2025-06-03 15:31:33,151 log 14544 24480 Internal Server Error: /auth/register/
Traceback (most recent call last):
  File "D:\WORK PROJECTS\Autowash Build\autowash\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "D:\WORK PROJECTS\Autowash Build\autowash\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\WORK PROJECTS\Autowash Build\autowash\apps\accounts\views.py", line 90, in register_view
    return render(request, 'auth/register.html', {'form': form})
  File "D:\WORK PROJECTS\Autowash Build\autowash\venv\Lib\site-packages\django\shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "D:\WORK PROJECTS\Autowash Build\autowash\venv\Lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "D:\WORK PROJECTS\Autowash Build\autowash\venv\Lib\site-packages\django\template\loader.py", line 15, in get_template
    return engine.get_template(template_name)
           ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
  File "D:\WORK PROJECTS\Autowash Build\autowash\venv\Lib\site-packages\django\template\backends\django.py", line 79, in get_template
    return Template(self.engine.get_template(template_name), self)
                    ~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
  File "D:\WORK PROJECTS\Autowash Build\autowash\venv\Lib\site-packages\django\template\engine.py", line 177, in get_template
    template, origin = self.find_template(template_name)
                       ~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
  File "D:\WORK PROJECTS\Autowash Build\autowash\venv\Lib\site-packages\django\template\engine.py", line 159, in find_template
    template = loader.get_template(name, skip=skip)
  File "D:\WORK PROJECTS\Autowash Build\autowash\venv\Lib\site-packages\django\template\loaders\cached.py", line 57, in get_template
    template = super().get_template(template_name, skip)
  File "D:\WORK PROJECTS\Autowash Build\autowash\venv\Lib\site-packages\django\template\loaders\base.py", line 28, in get_template
    return Template(
        contents,
    ...<2 lines>...
        self.engine,
    )
  File "D:\WORK PROJECTS\Autowash Build\autowash\venv\Lib\site-packages\django\template\base.py", line 154, in __init__
    self.nodelist = self.compile_nodelist()
                    ~~~~~~~~~~~~~~~~~~~~~^^
  File "D:\WORK PROJECTS\Autowash Build\autowash\venv\Lib\site-packages\django\template\base.py", line 196, in compile_nodelist
    nodelist = parser.parse()
  File "D:\WORK PROJECTS\Autowash Build\autowash\venv\Lib\site-packages\django\template\base.py", line 518, in parse
    raise self.error(token, e)
  File "D:\WORK PROJECTS\Autowash Build\autowash\venv\Lib\site-packages\django\template\base.py", line 516, in parse
    compiled_result = compile_func(self, token)
  File "D:\WORK PROJECTS\Autowash Build\autowash\venv\Lib\site-packages\django\template\loader_tags.py", line 299, in do_extends
    nodelist = parser.parse()
  File "D:\WORK PROJECTS\Autowash Build\autowash\venv\Lib\site-packages\django\template\base.py", line 518, in parse
    raise self.error(token, e)
  File "D:\WORK PROJECTS\Autowash Build\autowash\venv\Lib\site-packages\django\template\base.py", line 516, in parse
    compiled_result = compile_func(self, token)
  File "D:\WORK PROJECTS\Autowash Build\autowash\venv\Lib\site-packages\django\template\loader_tags.py", line 234, in do_block
    nodelist = parser.parse(("endblock",))
  File "D:\WORK PROJECTS\Autowash Build\autowash\venv\Lib\site-packages\django\template\base.py", line 489, in parse
    raise self.error(token, e)
  File "D:\WORK PROJECTS\Autowash Build\autowash\venv\Lib\site-packages\django\template\base.py", line 487, in parse
    filter_expression = self.compile_filter(token.contents)
  File "D:\WORK PROJECTS\Autowash Build\autowash\venv\Lib\site-packages\django\template\base.py", line 609, in compile_filter
    return FilterExpression(token, self)
  File "D:\WORK PROJECTS\Autowash Build\autowash\venv\Lib\site-packages\django\template\base.py", line 705, in __init__
    filter_func = parser.find_filter(filter_name)
  File "D:\WORK PROJECTS\Autowash Build\autowash\venv\Lib\site-packages\django\template\base.py", line 615, in find_filter
    raise TemplateSyntaxError("Invalid filter: '%s'" % filter_name)
django.template.exceptions.TemplateSyntaxError: Invalid filter: 'add_class'
ERROR 2025-06-03 15:31:33,161 basehttp 14544 24480 "GET /auth/register/ HTTP/1.1" 500 262657
ERROR 2025-06-03 15:33:12,994 log 14544 24480 Internal Server Error: /auth/register/
Traceback (most recent call last):
  File "D:\WORK PROJECTS\Autowash Build\autowash\venv\Lib\site-packages\django\template\defaulttags.py", line 1035, in find_library
    return parser.libraries[name]
           ~~~~~~~~~~~~~~~~^^^^^^
KeyError: 'custom_filters'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\WORK PROJECTS\Autowash Build\autowash\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "D:\WORK PROJECTS\Autowash Build\autowash\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\WORK PROJECTS\Autowash Build\autowash\apps\accounts\views.py", line 90, in register_view
    return render(request, 'auth/register.html', {'form': form})
  File "D:\WORK PROJECTS\Autowash Build\autowash\venv\Lib\site-packages\django\shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "D:\WORK PROJECTS\Autowash Build\autowash\venv\Lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "D:\WORK PROJECTS\Autowash Build\autowash\venv\Lib\site-packages\django\template\loader.py", line 15, in get_template
    return engine.get_template(template_name)
           ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
  File "D:\WORK PROJECTS\Autowash Build\autowash\venv\Lib\site-packages\django\template\backends\django.py", line 79, in get_template
    return Template(self.engine.get_template(template_name), self)
                    ~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
  File "D:\WORK PROJECTS\Autowash Build\autowash\venv\Lib\site-packages\django\template\engine.py", line 177, in get_template
    template, origin = self.find_template(template_name)
                       ~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
  File "D:\WORK PROJECTS\Autowash Build\autowash\venv\Lib\site-packages\django\template\engine.py", line 159, in find_template
    template = loader.get_template(name, skip=skip)
  File "D:\WORK PROJECTS\Autowash Build\autowash\venv\Lib\site-packages\django\template\loaders\cached.py", line 57, in get_template
    template = super().get_template(template_name, skip)
  File "D:\WORK PROJECTS\Autowash Build\autowash\venv\Lib\site-packages\django\template\loaders\base.py", line 28, in get_template
    return Template(
        contents,
    ...<2 lines>...
        self.engine,
    )
  File "D:\WORK PROJECTS\Autowash Build\autowash\venv\Lib\site-packages\django\template\base.py", line 154, in __init__
    self.nodelist = self.compile_nodelist()
                    ~~~~~~~~~~~~~~~~~~~~~^^
  File "D:\WORK PROJECTS\Autowash Build\autowash\venv\Lib\site-packages\django\template\base.py", line 196, in compile_nodelist
    nodelist = parser.parse()
  File "D:\WORK PROJECTS\Autowash Build\autowash\venv\Lib\site-packages\django\template\base.py", line 518, in parse
    raise self.error(token, e)
  File "D:\WORK PROJECTS\Autowash Build\autowash\venv\Lib\site-packages\django\template\base.py", line 516, in parse
    compiled_result = compile_func(self, token)
  File "D:\WORK PROJECTS\Autowash Build\autowash\venv\Lib\site-packages\django\template\loader_tags.py", line 299, in do_extends
    nodelist = parser.parse()
  File "D:\WORK PROJECTS\Autowash Build\autowash\venv\Lib\site-packages\django\template\base.py", line 518, in parse
    raise self.error(token, e)
  File "D:\WORK PROJECTS\Autowash Build\autowash\venv\Lib\site-packages\django\template\base.py", line 516, in parse
    compiled_result = compile_func(self, token)
  File "D:\WORK PROJECTS\Autowash Build\autowash\venv\Lib\site-packages\django\template\defaulttags.py", line 1097, in load
    lib = find_library(parser, name)
  File "D:\WORK PROJECTS\Autowash Build\autowash\venv\Lib\site-packages\django\template\defaulttags.py", line 1037, in find_library
    raise TemplateSyntaxError(
    ...<5 lines>...
    )
django.template.exceptions.TemplateSyntaxError: 'custom_filters' is not a registered tag library. Must be one of:
account
admin_list
admin_modify
admin_urls
allauth
cache
crispy_forms_field
crispy_forms_filters
crispy_forms_tags
crispy_forms_utils
debugger_tags
highlighting
i18n
import_export_tags
indent_text
l10n
log
rest_framework
socialaccount
static
syntax_color
tenant
tz
widont
ERROR 2025-06-03 15:33:13,002 basehttp 14544 24480 "GET /auth/register/ HTTP/1.1" 500 236609
INFO 2025-06-03 15:33:33,353 autoreload 13876 23380 Watching for file changes with StatReloader
INFO 2025-06-03 15:33:38,525 basehttp 13876 17404 "GET /auth/register/ HTTP/1.1" 200 51742
WARNING 2025-06-03 15:33:38,583 basehttp 13876 17404 "GET /static/css/custom.css HTTP/1.1" 404 1969
WARNING 2025-06-03 15:33:38,583 basehttp 13876 11512 "GET /static/css/dashboard.css HTTP/1.1" 404 1978
INFO 2025-06-03 15:35:13,208 basehttp 13876 6964 "POST /auth/register/ HTTP/1.1" 200 52032
WARNING 2025-06-03 15:35:13,235 basehttp 13876 6964 "GET /static/css/custom.css HTTP/1.1" 404 1969
WARNING 2025-06-03 15:35:13,242 basehttp 13876 4116 "GET /static/css/dashboard.css HTTP/1.1" 404 1978
INFO 2025-06-03 15:35:34,980 basehttp 13876 20616 "POST /auth/register/ HTTP/1.1" 200 52033
WARNING 2025-06-03 15:35:35,021 basehttp 13876 20616 "GET /static/css/custom.css HTTP/1.1" 404 1969
WARNING 2025-06-03 15:35:35,021 basehttp 13876 13976 "GET /static/css/dashboard.css HTTP/1.1" 404 1978
INFO 2025-06-03 15:35:56,226 basehttp 13876 6976 "POST /auth/register/ HTTP/1.1" 302 0
INFO 2025-06-03 15:35:56,350 basehttp 13876 6976 "GET /auth/business/register/ HTTP/1.1" 200 36911
WARNING 2025-06-03 15:35:56,378 basehttp 13876 6976 "GET /static/css/custom.css HTTP/1.1" 404 1969
WARNING 2025-06-03 15:35:56,384 basehttp 13876 4944 "GET /static/css/dashboard.css HTTP/1.1" 404 1978
ERROR 2025-06-03 15:36:05,144 log 13876 23168 Internal Server Error: /auth/dashboard/
Traceback (most recent call last):
  File "D:\WORK PROJECTS\Autowash Build\autowash\venv\Lib\site-packages\django\db\backends\utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
psycopg2.errors.UndefinedTable: relation "employees_employee" does not exist
LINE 1: ...", "employees_employee"."performance_rating" FROM "employees...
                                                             ^


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\WORK PROJECTS\Autowash Build\autowash\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "D:\WORK PROJECTS\Autowash Build\autowash\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\WORK PROJECTS\Autowash Build\autowash\venv\Lib\site-packages\django\contrib\auth\decorators.py", line 59, in _view_wrapper
    return view_func(request, *args, **kwargs)
  File "D:\WORK PROJECTS\Autowash Build\autowash\apps\accounts\views.py", line 297, in dashboard_redirect
    employee = Employee.objects.get(user=request.user)
  File "D:\WORK PROJECTS\Autowash Build\autowash\venv\Lib\site-packages\django\db\models\manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
  File "D:\WORK PROJECTS\Autowash Build\autowash\venv\Lib\site-packages\django\db\models\query.py", line 629, in get
    num = len(clone)
  File "D:\WORK PROJECTS\Autowash Build\autowash\venv\Lib\site-packages\django\db\models\query.py", line 366, in __len__
    self._fetch_all()
    ~~~~~~~~~~~~~~~^^
  File "D:\WORK PROJECTS\Autowash Build\autowash\venv\Lib\site-packages\django\db\models\query.py", line 1945, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
                         ~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\WORK PROJECTS\Autowash Build\autowash\venv\Lib\site-packages\django\db\models\query.py", line 91, in __iter__
    results = compiler.execute_sql(
        chunked_fetch=self.chunked_fetch, chunk_size=self.chunk_size
    )
  File "D:\WORK PROJECTS\Autowash Build\autowash\venv\Lib\site-packages\django\db\models\sql\compiler.py", line 1623, in execute_sql
    cursor.execute(sql, params)
    ~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "D:\WORK PROJECTS\Autowash Build\autowash\venv\Lib\site-packages\django\db\backends\utils.py", line 122, in execute
    return super().execute(sql, params)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "D:\WORK PROJECTS\Autowash Build\autowash\venv\Lib\site-packages\django\db\backends\utils.py", line 79, in execute
    return self._execute_with_wrappers(
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~^
        sql, params, many=False, executor=self._execute
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "D:\WORK PROJECTS\Autowash Build\autowash\venv\Lib\site-packages\django\db\backends\utils.py", line 92, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "D:\WORK PROJECTS\Autowash Build\autowash\venv\Lib\site-packages\django\db\backends\utils.py", line 100, in _execute
    with self.db.wrap_database_errors:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\WORK PROJECTS\Autowash Build\autowash\venv\Lib\site-packages\django\db\utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "D:\WORK PROJECTS\Autowash Build\autowash\venv\Lib\site-packages\django\db\backends\utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
django.db.utils.ProgrammingError: relation "employees_employee" does not exist
LINE 1: ...", "employees_employee"."performance_rating" FROM "employees...
                                                             ^

ERROR 2025-06-03 15:36:05,153 basehttp 13876 23168 "GET /auth/dashboard/ HTTP/1.1" 500 171299
INFO 2025-06-03 15:36:16,200 basehttp 13876 23168 "GET / HTTP/1.1" 200 54136
WARNING 2025-06-03 15:36:16,232 basehttp 13876 23168 "GET /static/css/custom.css HTTP/1.1" 404 1969
WARNING 2025-06-03 15:36:16,241 basehttp 13876 18136 "GET /static/css/dashboard.css HTTP/1.1" 404 1978
WARNING 2025-06-03 15:36:16,246 basehttp 13876 10684 "GET /static/img/dashboard-preview.png HTTP/1.1" 404 2002
INFO 2025-06-03 15:36:22,394 basehttp 13876 10960 "GET / HTTP/1.1" 200 54136
WARNING 2025-06-03 15:36:22,414 basehttp 13876 10960 "GET /static/css/custom.css HTTP/1.1" 404 1969
WARNING 2025-06-03 15:36:22,418 basehttp 13876 18560 "GET /static/img/dashboard-preview.png HTTP/1.1" 404 2002
WARNING 2025-06-03 15:36:22,418 basehttp 13876 10224 "GET /static/css/dashboard.css HTTP/1.1" 404 1978
INFO 2025-06-03 15:36:23,934 basehttp 13876 17684 "GET /features/ HTTP/1.1" 200 54153
WARNING 2025-06-03 15:36:23,980 basehttp 13876 17684 "GET /static/css/custom.css HTTP/1.1" 404 1969
WARNING 2025-06-03 15:36:23,984 basehttp 13876 21976 "GET /static/css/dashboard.css HTTP/1.1" 404 1978
WARNING 2025-06-03 15:36:23,991 basehttp 13876 23540 "GET /static/img/service-management.png HTTP/1.1" 404 2005
WARNING 2025-06-03 15:36:23,999 basehttp 13876 17832 "GET /static/img/analytics-dashboard.png HTTP/1.1" 404 2008
WARNING 2025-06-03 15:36:24,000 basehttp 13876 10692 "GET /static/img/customer-management.png HTTP/1.1" 404 2008
INFO 2025-06-03 15:36:25,547 basehttp 13876 3256 "GET /pricing/ HTTP/1.1" 200 61465
WARNING 2025-06-03 15:36:25,587 basehttp 13876 3256 "GET /static/css/custom.css HTTP/1.1" 404 1969
WARNING 2025-06-03 15:36:25,587 basehttp 13876 3432 "GET /static/css/dashboard.css HTTP/1.1" 404 1978
INFO 2025-06-03 15:36:27,006 basehttp 13876 18228 "GET /contact/ HTTP/1.1" 200 53909
WARNING 2025-06-03 15:36:27,041 basehttp 13876 18228 "GET /static/css/custom.css HTTP/1.1" 404 1969
WARNING 2025-06-03 15:36:27,047 basehttp 13876 20900 "GET /static/css/dashboard.css HTTP/1.1" 404 1978
ERROR 2025-06-03 15:36:28,796 log 13876 10812 Internal Server Error: /auth/dashboard/
Traceback (most recent call last):
  File "D:\WORK PROJECTS\Autowash Build\autowash\venv\Lib\site-packages\django\db\backends\utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
psycopg2.errors.UndefinedTable: relation "employees_employee" does not exist
LINE 1: ...", "employees_employee"."performance_rating" FROM "employees...
                                                             ^


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\WORK PROJECTS\Autowash Build\autowash\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "D:\WORK PROJECTS\Autowash Build\autowash\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\WORK PROJECTS\Autowash Build\autowash\venv\Lib\site-packages\django\contrib\auth\decorators.py", line 59, in _view_wrapper
    return view_func(request, *args, **kwargs)
  File "D:\WORK PROJECTS\Autowash Build\autowash\apps\accounts\views.py", line 297, in dashboard_redirect
    employee = Employee.objects.get(user=request.user)
  File "D:\WORK PROJECTS\Autowash Build\autowash\venv\Lib\site-packages\django\db\models\manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
  File "D:\WORK PROJECTS\Autowash Build\autowash\venv\Lib\site-packages\django\db\models\query.py", line 629, in get
    num = len(clone)
  File "D:\WORK PROJECTS\Autowash Build\autowash\venv\Lib\site-packages\django\db\models\query.py", line 366, in __len__
    self._fetch_all()
    ~~~~~~~~~~~~~~~^^
  File "D:\WORK PROJECTS\Autowash Build\autowash\venv\Lib\site-packages\django\db\models\query.py", line 1945, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
                         ~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\WORK PROJECTS\Autowash Build\autowash\venv\Lib\site-packages\django\db\models\query.py", line 91, in __iter__
    results = compiler.execute_sql(
        chunked_fetch=self.chunked_fetch, chunk_size=self.chunk_size
    )
  File "D:\WORK PROJECTS\Autowash Build\autowash\venv\Lib\site-packages\django\db\models\sql\compiler.py", line 1623, in execute_sql
    cursor.execute(sql, params)
    ~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "D:\WORK PROJECTS\Autowash Build\autowash\venv\Lib\site-packages\django\db\backends\utils.py", line 122, in execute
    return super().execute(sql, params)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "D:\WORK PROJECTS\Autowash Build\autowash\venv\Lib\site-packages\django\db\backends\utils.py", line 79, in execute
    return self._execute_with_wrappers(
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~^
        sql, params, many=False, executor=self._execute
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "D:\WORK PROJECTS\Autowash Build\autowash\venv\Lib\site-packages\django\db\backends\utils.py", line 92, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "D:\WORK PROJECTS\Autowash Build\autowash\venv\Lib\site-packages\django\db\backends\utils.py", line 100, in _execute
    with self.db.wrap_database_errors:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\WORK PROJECTS\Autowash Build\autowash\venv\Lib\site-packages\django\db\utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "D:\WORK PROJECTS\Autowash Build\autowash\venv\Lib\site-packages\django\db\backends\utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
django.db.utils.ProgrammingError: relation "employees_employee" does not exist
LINE 1: ...", "employees_employee"."performance_rating" FROM "employees...
                                                             ^

ERROR 2025-06-03 15:36:28,802 basehttp 13876 10812 "GET /auth/dashboard/ HTTP/1.1" 500 171284
ERROR 2025-06-03 15:37:34,750 log 13876 10812 Internal Server Error: /auth/dashboard/
Traceback (most recent call last):
  File "D:\WORK PROJECTS\Autowash Build\autowash\venv\Lib\site-packages\django\db\backends\utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
psycopg2.errors.UndefinedTable: relation "employees_employee" does not exist
LINE 1: ...", "employees_employee"."performance_rating" FROM "employees...
                                                             ^


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\WORK PROJECTS\Autowash Build\autowash\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "D:\WORK PROJECTS\Autowash Build\autowash\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\WORK PROJECTS\Autowash Build\autowash\venv\Lib\site-packages\django\contrib\auth\decorators.py", line 59, in _view_wrapper
    return view_func(request, *args, **kwargs)
  File "D:\WORK PROJECTS\Autowash Build\autowash\apps\accounts\views.py", line 297, in dashboard_redirect
    employee = Employee.objects.get(user=request.user)
  File "D:\WORK PROJECTS\Autowash Build\autowash\venv\Lib\site-packages\django\db\models\manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
  File "D:\WORK PROJECTS\Autowash Build\autowash\venv\Lib\site-packages\django\db\models\query.py", line 629, in get
    num = len(clone)
  File "D:\WORK PROJECTS\Autowash Build\autowash\venv\Lib\site-packages\django\db\models\query.py", line 366, in __len__
    self._fetch_all()
    ~~~~~~~~~~~~~~~^^
  File "D:\WORK PROJECTS\Autowash Build\autowash\venv\Lib\site-packages\django\db\models\query.py", line 1945, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
                         ~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\WORK PROJECTS\Autowash Build\autowash\venv\Lib\site-packages\django\db\models\query.py", line 91, in __iter__
    results = compiler.execute_sql(
        chunked_fetch=self.chunked_fetch, chunk_size=self.chunk_size
    )
  File "D:\WORK PROJECTS\Autowash Build\autowash\venv\Lib\site-packages\django\db\models\sql\compiler.py", line 1623, in execute_sql
    cursor.execute(sql, params)
    ~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "D:\WORK PROJECTS\Autowash Build\autowash\venv\Lib\site-packages\django\db\backends\utils.py", line 122, in execute
    return super().execute(sql, params)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "D:\WORK PROJECTS\Autowash Build\autowash\venv\Lib\site-packages\django\db\backends\utils.py", line 79, in execute
    return self._execute_with_wrappers(
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~^
        sql, params, many=False, executor=self._execute
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "D:\WORK PROJECTS\Autowash Build\autowash\venv\Lib\site-packages\django\db\backends\utils.py", line 92, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "D:\WORK PROJECTS\Autowash Build\autowash\venv\Lib\site-packages\django\db\backends\utils.py", line 100, in _execute
    with self.db.wrap_database_errors:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\WORK PROJECTS\Autowash Build\autowash\venv\Lib\site-packages\django\db\utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "D:\WORK PROJECTS\Autowash Build\autowash\venv\Lib\site-packages\django\db\backends\utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
django.db.utils.ProgrammingError: relation "employees_employee" does not exist
LINE 1: ...", "employees_employee"."performance_rating" FROM "employees...
                                                             ^

ERROR 2025-06-03 15:37:34,755 basehttp 13876 10812 "GET /auth/dashboard/ HTTP/1.1" 500 171125
WARNING 2025-06-03 15:37:38,904 log 13876 10812 Not Found: /auth/
WARNING 2025-06-03 15:37:38,904 basehttp 13876 10812 "GET /auth/ HTTP/1.1" 404 5980
INFO 2025-06-03 15:38:01,483 basehttp 13876 10812 "GET /auth/business/register HTTP/1.1" 301 0
ERROR 2025-06-03 15:38:01,754 log 13876 2416 Internal Server Error: /auth/business/register/
Traceback (most recent call last):
  File "D:\WORK PROJECTS\Autowash Build\autowash\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "D:\WORK PROJECTS\Autowash Build\autowash\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\WORK PROJECTS\Autowash Build\autowash\venv\Lib\site-packages\django\contrib\auth\decorators.py", line 59, in _view_wrapper
    return view_func(request, *args, **kwargs)
  File "D:\WORK PROJECTS\Autowash Build\autowash\apps\accounts\views.py", line 189, in business_register_view
    return render(request, 'auth/business_register.html', {'form': form})
  File "D:\WORK PROJECTS\Autowash Build\autowash\venv\Lib\site-packages\django\shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "D:\WORK PROJECTS\Autowash Build\autowash\venv\Lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "D:\WORK PROJECTS\Autowash Build\autowash\venv\Lib\site-packages\django\template\loader.py", line 15, in get_template
    return engine.get_template(template_name)
           ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
  File "D:\WORK PROJECTS\Autowash Build\autowash\venv\Lib\site-packages\django\template\backends\django.py", line 79, in get_template
    return Template(self.engine.get_template(template_name), self)
                    ~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
  File "D:\WORK PROJECTS\Autowash Build\autowash\venv\Lib\site-packages\django\template\engine.py", line 177, in get_template
    template, origin = self.find_template(template_name)
                       ~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
  File "D:\WORK PROJECTS\Autowash Build\autowash\venv\Lib\site-packages\django\template\engine.py", line 159, in find_template
    template = loader.get_template(name, skip=skip)
  File "D:\WORK PROJECTS\Autowash Build\autowash\venv\Lib\site-packages\django\template\loaders\cached.py", line 57, in get_template
    template = super().get_template(template_name, skip)
  File "D:\WORK PROJECTS\Autowash Build\autowash\venv\Lib\site-packages\django\template\loaders\base.py", line 28, in get_template
    return Template(
        contents,
    ...<2 lines>...
        self.engine,
    )
  File "D:\WORK PROJECTS\Autowash Build\autowash\venv\Lib\site-packages\django\template\base.py", line 154, in __init__
    self.nodelist = self.compile_nodelist()
                    ~~~~~~~~~~~~~~~~~~~~~^^
  File "D:\WORK PROJECTS\Autowash Build\autowash\venv\Lib\site-packages\django\template\base.py", line 196, in compile_nodelist
    nodelist = parser.parse()
  File "D:\WORK PROJECTS\Autowash Build\autowash\venv\Lib\site-packages\django\template\base.py", line 518, in parse
    raise self.error(token, e)
  File "D:\WORK PROJECTS\Autowash Build\autowash\venv\Lib\site-packages\django\template\base.py", line 516, in parse
    compiled_result = compile_func(self, token)
  File "D:\WORK PROJECTS\Autowash Build\autowash\venv\Lib\site-packages\django\template\loader_tags.py", line 299, in do_extends
    nodelist = parser.parse()
  File "D:\WORK PROJECTS\Autowash Build\autowash\venv\Lib\site-packages\django\template\base.py", line 518, in parse
    raise self.error(token, e)
  File "D:\WORK PROJECTS\Autowash Build\autowash\venv\Lib\site-packages\django\template\base.py", line 516, in parse
    compiled_result = compile_func(self, token)
  File "D:\WORK PROJECTS\Autowash Build\autowash\venv\Lib\site-packages\django\template\loader_tags.py", line 234, in do_block
    nodelist = parser.parse(("endblock",))
  File "D:\WORK PROJECTS\Autowash Build\autowash\venv\Lib\site-packages\django\template\base.py", line 489, in parse
    raise self.error(token, e)
  File "D:\WORK PROJECTS\Autowash Build\autowash\venv\Lib\site-packages\django\template\base.py", line 487, in parse
    filter_expression = self.compile_filter(token.contents)
  File "D:\WORK PROJECTS\Autowash Build\autowash\venv\Lib\site-packages\django\template\base.py", line 609, in compile_filter
    return FilterExpression(token, self)
  File "D:\WORK PROJECTS\Autowash Build\autowash\venv\Lib\site-packages\django\template\base.py", line 705, in __init__
    filter_func = parser.find_filter(filter_name)
  File "D:\WORK PROJECTS\Autowash Build\autowash\venv\Lib\site-packages\django\template\base.py", line 615, in find_filter
    raise TemplateSyntaxError("Invalid filter: '%s'" % filter_name)
django.template.exceptions.TemplateSyntaxError: Invalid filter: 'add_class'
ERROR 2025-06-03 15:38:01,763 basehttp 13876 2416 "GET /auth/business/register/ HTTP/1.1" 500 294281
INFO 2025-06-03 15:38:32,416 basehttp 13876 2416 "GET /auth/business/register/ HTTP/1.1" 200 57959
WARNING 2025-06-03 15:38:32,440 basehttp 13876 2416 "GET /static/css/custom.css HTTP/1.1" 404 1969
WARNING 2025-06-03 15:38:32,441 basehttp 13876 24188 "GET /static/css/dashboard.css HTTP/1.1" 404 1978
INFO 2025-06-03 15:42:16,711 basehttp 13876 6972 "GET /auth/logout/ HTTP/1.1" 302 0
INFO 2025-06-03 15:42:16,816 basehttp 13876 6972 "GET / HTTP/1.1" 200 54768
WARNING 2025-06-03 15:42:16,850 basehttp 13876 6972 "GET /static/css/custom.css HTTP/1.1" 404 1969
WARNING 2025-06-03 15:42:16,863 basehttp 13876 3176 "GET /static/css/dashboard.css HTTP/1.1" 404 1978
WARNING 2025-06-03 15:42:16,864 basehttp 13876 19460 "GET /static/img/dashboard-preview.png HTTP/1.1" 404 2002
INFO 2025-06-03 15:42:19,594 basehttp 13876 11628 "GET /auth/login/ HTTP/1.1" 200 43518
WARNING 2025-06-03 15:42:19,619 basehttp 13876 11628 "GET /static/css/dashboard.css HTTP/1.1" 404 1978
WARNING 2025-06-03 15:42:19,620 basehttp 13876 12000 "GET /static/css/custom.css HTTP/1.1" 404 1969
INFO 2025-06-03 15:42:34,253 basehttp 13876 19056 "POST /auth/login/ HTTP/1.1" 200 44305
WARNING 2025-06-03 15:42:34,299 basehttp 13876 14068 "GET /static/css/dashboard.css HTTP/1.1" 404 1978
WARNING 2025-06-03 15:42:34,299 basehttp 13876 19056 "GET /static/css/custom.css HTTP/1.1" 404 1969
INFO 2025-06-03 15:43:03,572 basehttp 13876 21768 "POST /auth/login/ HTTP/1.1" 200 44305
WARNING 2025-06-03 15:43:03,612 basehttp 13876 7916 "GET /static/css/custom.css HTTP/1.1" 404 1969
WARNING 2025-06-03 15:43:03,613 basehttp 13876 21768 "GET /static/css/dashboard.css HTTP/1.1" 404 1978
INFO 2025-06-03 15:44:08,390 basehttp 13876 1776 "GET /auth/login/ HTTP/1.1" 200 43518
WARNING 2025-06-03 15:44:08,412 basehttp 13876 1776 "GET /static/css/custom.css HTTP/1.1" 404 1969
WARNING 2025-06-03 15:44:08,418 basehttp 13876 17244 "GET /static/css/dashboard.css HTTP/1.1" 404 1978
WARNING 2025-06-03 15:44:12,615 log 13876 6024 Not Found: /auth/business/
WARNING 2025-06-03 15:44:12,616 basehttp 13876 6024 "GET /auth/business/ HTTP/1.1" 404 6007
INFO 2025-06-03 15:44:20,068 basehttp 13876 6024 "GET /auth/business/settings HTTP/1.1" 301 0
INFO 2025-06-03 15:44:20,142 basehttp 13876 23972 "GET /auth/business/settings/ HTTP/1.1" 302 0
INFO 2025-06-03 15:44:20,231 basehttp 13876 23972 "GET /auth/login/?next=/auth/business/settings/ HTTP/1.1" 200 43518
WARNING 2025-06-03 15:44:20,255 basehttp 13876 23972 "GET /static/css/custom.css HTTP/1.1" 404 1969
WARNING 2025-06-03 15:44:20,263 basehttp 13876 12380 "GET /static/css/dashboard.css HTTP/1.1" 404 1978
INFO 2025-06-03 15:56:58,305 autoreload 13876 23380 D:\WORK PROJECTS\Autowash Build\autowash\apps\accounts\views.py changed, reloading.
INFO 2025-06-03 15:57:03,458 autoreload 23760 22432 Watching for file changes with StatReloader
INFO 2025-06-03 16:02:14,073 basehttp 23760 15584 "GET /auth/login/?next=/auth/business/settings/ HTTP/1.1" 200 43518
WARNING 2025-06-03 16:02:14,100 basehttp 23760 15584 "GET /static/css/custom.css HTTP/1.1" 404 1969
WARNING 2025-06-03 16:02:14,106 basehttp 23760 23636 "GET /static/css/dashboard.css HTTP/1.1" 404 1978
INFO 2025-06-03 16:02:16,192 basehttp 23760 19956 "GET / HTTP/1.1" 200 53991
WARNING 2025-06-03 16:02:16,226 basehttp 23760 14472 "GET /static/css/dashboard.css HTTP/1.1" 404 1978
WARNING 2025-06-03 16:02:16,227 basehttp 23760 19956 "GET /static/css/custom.css HTTP/1.1" 404 1969
WARNING 2025-06-03 16:02:16,234 basehttp 23760 20420 "GET /static/img/dashboard-preview.png HTTP/1.1" 404 2002
INFO 2025-06-03 16:02:18,537 basehttp 23760 14960 "GET /auth/login/ HTTP/1.1" 200 43518
WARNING 2025-06-03 16:02:18,565 basehttp 23760 11992 "GET /static/css/dashboard.css HTTP/1.1" 404 1978
WARNING 2025-06-03 16:02:18,565 basehttp 23760 14960 "GET /static/css/custom.css HTTP/1.1" 404 1969
INFO 2025-06-03 16:02:21,319 basehttp 23760 15288 "GET /auth/register/ HTTP/1.1" 200 51712
WARNING 2025-06-03 16:02:21,345 basehttp 23760 21204 "GET /static/css/dashboard.css HTTP/1.1" 404 1978
WARNING 2025-06-03 16:02:21,349 basehttp 23760 15288 "GET /static/css/custom.css HTTP/1.1" 404 1969
INFO 2025-06-03 16:06:55,785 basehttp 23760 22492 "GET /auth/register/ HTTP/1.1" 200 51712
WARNING 2025-06-03 16:06:55,815 basehttp 23760 22492 "GET /static/css/custom.css HTTP/1.1" 404 1969
WARNING 2025-06-03 16:06:55,823 basehttp 23760 18564 "GET /static/css/dashboard.css HTTP/1.1" 404 1978
INFO 2025-06-03 16:06:57,795 basehttp 23760 24424 "GET / HTTP/1.1" 200 53991
WARNING 2025-06-03 16:06:57,830 basehttp 23760 24424 "GET /static/css/custom.css HTTP/1.1" 404 1969
WARNING 2025-06-03 16:06:57,841 basehttp 23760 4596 "GET /static/css/dashboard.css HTTP/1.1" 404 1978
WARNING 2025-06-03 16:06:57,850 basehttp 23760 3528 "GET /static/img/dashboard-preview.png HTTP/1.1" 404 2002
INFO 2025-06-03 16:08:37,498 basehttp 23760 12616 "GET /auth/register/ HTTP/1.1" 200 51712
WARNING 2025-06-03 16:08:37,530 basehttp 23760 12616 "GET /static/css/custom.css HTTP/1.1" 404 1969
WARNING 2025-06-03 16:08:37,538 basehttp 23760 17000 "GET /static/css/dashboard.css HTTP/1.1" 404 1978
INFO 2025-06-03 16:09:16,620 basehttp 23760 18384 "POST /auth/register/ HTTP/1.1" 200 51871
WARNING 2025-06-03 16:09:16,647 basehttp 23760 6292 "GET /static/css/dashboard.css HTTP/1.1" 404 1978
WARNING 2025-06-03 16:09:16,654 basehttp 23760 18384 "GET /static/css/custom.css HTTP/1.1" 404 1969
INFO 2025-06-03 16:10:02,306 basehttp 23760 18912 "POST /auth/register/ HTTP/1.1" 302 0
ERROR 2025-06-03 16:10:02,490 log 23760 18912 Internal Server Error: /auth/business/register/
Traceback (most recent call last):
  File "D:\WORK PROJECTS\Autowash Build\autowash\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "D:\WORK PROJECTS\Autowash Build\autowash\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\WORK PROJECTS\Autowash Build\autowash\venv\Lib\site-packages\django\contrib\auth\decorators.py", line 59, in _view_wrapper
    return view_func(request, *args, **kwargs)
  File "D:\WORK PROJECTS\Autowash Build\autowash\apps\accounts\views.py", line 189, in business_register_view
    return render(request, 'auth/business_register.html', {'form': form})
  File "D:\WORK PROJECTS\Autowash Build\autowash\venv\Lib\site-packages\django\shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "D:\WORK PROJECTS\Autowash Build\autowash\venv\Lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "D:\WORK PROJECTS\Autowash Build\autowash\venv\Lib\site-packages\django\template\loader.py", line 15, in get_template
    return engine.get_template(template_name)
           ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
  File "D:\WORK PROJECTS\Autowash Build\autowash\venv\Lib\site-packages\django\template\backends\django.py", line 79, in get_template
    return Template(self.engine.get_template(template_name), self)
                    ~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
  File "D:\WORK PROJECTS\Autowash Build\autowash\venv\Lib\site-packages\django\template\engine.py", line 177, in get_template
    template, origin = self.find_template(template_name)
                       ~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
  File "D:\WORK PROJECTS\Autowash Build\autowash\venv\Lib\site-packages\django\template\engine.py", line 159, in find_template
    template = loader.get_template(name, skip=skip)
  File "D:\WORK PROJECTS\Autowash Build\autowash\venv\Lib\site-packages\django\template\loaders\cached.py", line 57, in get_template
    template = super().get_template(template_name, skip)
  File "D:\WORK PROJECTS\Autowash Build\autowash\venv\Lib\site-packages\django\template\loaders\base.py", line 28, in get_template
    return Template(
        contents,
    ...<2 lines>...
        self.engine,
    )
  File "D:\WORK PROJECTS\Autowash Build\autowash\venv\Lib\site-packages\django\template\base.py", line 154, in __init__
    self.nodelist = self.compile_nodelist()
                    ~~~~~~~~~~~~~~~~~~~~~^^
  File "D:\WORK PROJECTS\Autowash Build\autowash\venv\Lib\site-packages\django\template\base.py", line 196, in compile_nodelist
    nodelist = parser.parse()
  File "D:\WORK PROJECTS\Autowash Build\autowash\venv\Lib\site-packages\django\template\base.py", line 518, in parse
    raise self.error(token, e)
  File "D:\WORK PROJECTS\Autowash Build\autowash\venv\Lib\site-packages\django\template\base.py", line 516, in parse
    compiled_result = compile_func(self, token)
  File "D:\WORK PROJECTS\Autowash Build\autowash\venv\Lib\site-packages\django\template\loader_tags.py", line 299, in do_extends
    nodelist = parser.parse()
  File "D:\WORK PROJECTS\Autowash Build\autowash\venv\Lib\site-packages\django\template\base.py", line 518, in parse
    raise self.error(token, e)
  File "D:\WORK PROJECTS\Autowash Build\autowash\venv\Lib\site-packages\django\template\base.py", line 516, in parse
    compiled_result = compile_func(self, token)
  File "D:\WORK PROJECTS\Autowash Build\autowash\venv\Lib\site-packages\django\template\loader_tags.py", line 234, in do_block
    nodelist = parser.parse(("endblock",))
  File "D:\WORK PROJECTS\Autowash Build\autowash\venv\Lib\site-packages\django\template\base.py", line 489, in parse
    raise self.error(token, e)
  File "D:\WORK PROJECTS\Autowash Build\autowash\venv\Lib\site-packages\django\template\base.py", line 487, in parse
    filter_expression = self.compile_filter(token.contents)
  File "D:\WORK PROJECTS\Autowash Build\autowash\venv\Lib\site-packages\django\template\base.py", line 609, in compile_filter
    return FilterExpression(token, self)
  File "D:\WORK PROJECTS\Autowash Build\autowash\venv\Lib\site-packages\django\template\base.py", line 705, in __init__
    filter_func = parser.find_filter(filter_name)
  File "D:\WORK PROJECTS\Autowash Build\autowash\venv\Lib\site-packages\django\template\base.py", line 615, in find_filter
    raise TemplateSyntaxError("Invalid filter: '%s'" % filter_name)
django.template.exceptions.TemplateSyntaxError: Invalid filter: 'add_class'
ERROR 2025-06-03 16:10:02,506 basehttp 23760 18912 "GET /auth/business/register/ HTTP/1.1" 500 294857
INFO 2025-06-03 16:10:27,783 basehttp 23760 18912 "GET /auth/business/register/ HTTP/1.1" 200 58993
WARNING 2025-06-03 16:10:27,805 basehttp 23760 18912 "GET /static/css/custom.css HTTP/1.1" 404 1969
WARNING 2025-06-03 16:10:27,810 basehttp 23760 23836 "GET /static/css/dashboard.css HTTP/1.1" 404 1978
ERROR 2025-06-03 16:11:43,699 log 23760 14804 Internal Server Error: /auth/dashboard/
Traceback (most recent call last):
  File "D:\WORK PROJECTS\Autowash Build\autowash\venv\Lib\site-packages\django\db\backends\utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
psycopg2.errors.UndefinedTable: relation "employees_employee" does not exist
LINE 1: ...", "employees_employee"."performance_rating" FROM "employees...
                                                             ^


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\WORK PROJECTS\Autowash Build\autowash\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "D:\WORK PROJECTS\Autowash Build\autowash\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\WORK PROJECTS\Autowash Build\autowash\venv\Lib\site-packages\django\contrib\auth\decorators.py", line 59, in _view_wrapper
    return view_func(request, *args, **kwargs)
  File "D:\WORK PROJECTS\Autowash Build\autowash\apps\accounts\views.py", line 303, in dashboard_redirect
    employee = Employee.objects.get(user=request.user, is_active=True)
  File "D:\WORK PROJECTS\Autowash Build\autowash\venv\Lib\site-packages\django\db\models\manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
  File "D:\WORK PROJECTS\Autowash Build\autowash\venv\Lib\site-packages\django\db\models\query.py", line 629, in get
    num = len(clone)
  File "D:\WORK PROJECTS\Autowash Build\autowash\venv\Lib\site-packages\django\db\models\query.py", line 366, in __len__
    self._fetch_all()
    ~~~~~~~~~~~~~~~^^
  File "D:\WORK PROJECTS\Autowash Build\autowash\venv\Lib\site-packages\django\db\models\query.py", line 1945, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
                         ~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\WORK PROJECTS\Autowash Build\autowash\venv\Lib\site-packages\django\db\models\query.py", line 91, in __iter__
    results = compiler.execute_sql(
        chunked_fetch=self.chunked_fetch, chunk_size=self.chunk_size
    )
  File "D:\WORK PROJECTS\Autowash Build\autowash\venv\Lib\site-packages\django\db\models\sql\compiler.py", line 1623, in execute_sql
    cursor.execute(sql, params)
    ~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "D:\WORK PROJECTS\Autowash Build\autowash\venv\Lib\site-packages\django\db\backends\utils.py", line 122, in execute
    return super().execute(sql, params)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "D:\WORK PROJECTS\Autowash Build\autowash\venv\Lib\site-packages\django\db\backends\utils.py", line 79, in execute
    return self._execute_with_wrappers(
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~^
        sql, params, many=False, executor=self._execute
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "D:\WORK PROJECTS\Autowash Build\autowash\venv\Lib\site-packages\django\db\backends\utils.py", line 92, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "D:\WORK PROJECTS\Autowash Build\autowash\venv\Lib\site-packages\django\db\backends\utils.py", line 100, in _execute
    with self.db.wrap_database_errors:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\WORK PROJECTS\Autowash Build\autowash\venv\Lib\site-packages\django\db\utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "D:\WORK PROJECTS\Autowash Build\autowash\venv\Lib\site-packages\django\db\backends\utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
django.db.utils.ProgrammingError: relation "employees_employee" does not exist
LINE 1: ...", "employees_employee"."performance_rating" FROM "employees...
                                                             ^

ERROR 2025-06-03 16:11:43,706 basehttp 23760 14804 "GET /auth/dashboard/ HTTP/1.1" 500 171936
INFO 2025-06-03 16:14:28,946 autoreload 23760 22432 D:\WORK PROJECTS\Autowash Build\autowash\apps\accounts\views.py changed, reloading.
INFO 2025-06-03 16:14:34,197 autoreload 22512 4224 Watching for file changes with StatReloader
INFO 2025-06-03 16:14:40,868 autoreload 22512 4224 D:\WORK PROJECTS\Autowash Build\autowash\apps\accounts\views.py changed, reloading.
INFO 2025-06-03 16:14:46,455 autoreload 6808 8396 Watching for file changes with StatReloader
INFO 2025-06-03 16:16:40,008 basehttp 6808 16056 "GET /auth/dashboard/ HTTP/1.1" 302 0
INFO 2025-06-03 16:16:40,297 basehttp 6808 16056 "GET /auth/business/register/ HTTP/1.1" 200 59014
WARNING 2025-06-03 16:16:40,338 basehttp 6808 16056 "GET /static/css/custom.css HTTP/1.1" 404 1969
WARNING 2025-06-03 16:16:40,346 basehttp 6808 17672 "GET /static/css/dashboard.css HTTP/1.1" 404 1978
INFO 2025-06-03 16:16:51,100 basehttp 6808 1816 "GET /auth/dashboard/ HTTP/1.1" 302 0
INFO 2025-06-03 16:16:51,218 basehttp 6808 1816 "GET /auth/business/register/ HTTP/1.1" 200 59014
WARNING 2025-06-03 16:16:51,254 basehttp 6808 1816 "GET /static/css/custom.css HTTP/1.1" 404 1969
WARNING 2025-06-03 16:16:51,255 basehttp 6808 17740 "GET /static/css/dashboard.css HTTP/1.1" 404 1978
INFO 2025-06-03 16:16:58,901 basehttp 6808 16320 "GET /auth/dashboard/ HTTP/1.1" 302 0
INFO 2025-06-03 16:16:58,991 basehttp 6808 16320 "GET /auth/business/register/ HTTP/1.1" 200 59014
WARNING 2025-06-03 16:16:59,017 basehttp 6808 4008 "GET /static/css/dashboard.css HTTP/1.1" 404 1978
WARNING 2025-06-03 16:16:59,017 basehttp 6808 16320 "GET /static/css/custom.css HTTP/1.1" 404 1969
INFO 2025-06-03 16:17:02,773 basehttp 6808 2148 "GET / HTTP/1.1" 200 54136
WARNING 2025-06-03 16:17:02,801 basehttp 6808 2148 "GET /static/css/custom.css HTTP/1.1" 404 1969
WARNING 2025-06-03 16:17:02,812 basehttp 6808 20012 "GET /static/img/dashboard-preview.png HTTP/1.1" 404 2002
WARNING 2025-06-03 16:17:02,812 basehttp 6808 340 "GET /static/css/dashboard.css HTTP/1.1" 404 1978
INFO 2025-06-03 16:17:04,910 basehttp 6808 4576 "GET /auth/dashboard/ HTTP/1.1" 302 0
INFO 2025-06-03 16:17:04,996 basehttp 6808 4576 "GET /auth/business/register/ HTTP/1.1" 200 59014
WARNING 2025-06-03 16:17:05,018 basehttp 6808 4576 "GET /static/css/custom.css HTTP/1.1" 404 1969
WARNING 2025-06-03 16:17:05,023 basehttp 6808 22632 "GET /static/css/dashboard.css HTTP/1.1" 404 1978
INFO 2025-06-03 16:35:28,538 autoreload 6808 8396 D:\WORK PROJECTS\Autowash Build\autowash\apps\accounts\views.py changed, reloading.
INFO 2025-06-03 16:35:33,715 autoreload 5152 16244 Watching for file changes with StatReloader
INFO 2025-06-03 16:35:37,302 basehttp 5152 18224 "GET / HTTP/1.1" 200 54136
WARNING 2025-06-03 16:35:37,335 basehttp 5152 18224 "GET /static/css/custom.css HTTP/1.1" 404 1969
WARNING 2025-06-03 16:35:37,349 basehttp 5152 11240 "GET /static/img/dashboard-preview.png HTTP/1.1" 404 2002
WARNING 2025-06-03 16:35:37,349 basehttp 5152 17336 "GET /static/css/dashboard.css HTTP/1.1" 404 1978
INFO 2025-06-03 16:35:42,019 basehttp 5152 17672 "GET /auth/dashboard/ HTTP/1.1" 302 0
INFO 2025-06-03 16:35:42,228 basehttp 5152 17672 "GET /auth/business/register/ HTTP/1.1" 200 59014
WARNING 2025-06-03 16:35:42,255 basehttp 5152 17672 "GET /static/css/custom.css HTTP/1.1" 404 1969
WARNING 2025-06-03 16:35:42,255 basehttp 5152 8476 "GET /static/css/dashboard.css HTTP/1.1" 404 1978
INFO 2025-06-03 16:38:32,910 autoreload 5152 16244 D:\WORK PROJECTS\Autowash Build\autowash\apps\accounts\views.py changed, reloading.
INFO 2025-06-03 16:38:38,410 autoreload 12272 10136 Watching for file changes with StatReloader
INFO 2025-06-03 16:38:42,658 autoreload 12272 10136 D:\WORK PROJECTS\Autowash Build\autowash\apps\accounts\views.py changed, reloading.
INFO 2025-06-03 16:38:47,491 autoreload 13604 16796 Watching for file changes with StatReloader
INFO 2025-06-03 16:40:18,298 autoreload 13604 16796 D:\WORK PROJECTS\Autowash Build\autowash\apps\accounts\views.py changed, reloading.
INFO 2025-06-03 16:40:24,538 autoreload 14904 10148 Watching for file changes with StatReloader
INFO 2025-06-03 16:40:58,202 autoreload 14904 10148 D:\WORK PROJECTS\Autowash Build\autowash\apps\accounts\forms.py changed, reloading.
INFO 2025-06-03 16:41:03,523 autoreload 6700 12308 Watching for file changes with StatReloader
INFO 2025-06-03 16:41:04,983 basehttp 6700 5428 "GET / HTTP/1.1" 200 54136
WARNING 2025-06-03 16:41:05,017 basehttp 6700 5428 "GET /static/css/custom.css HTTP/1.1" 404 1969
WARNING 2025-06-03 16:41:05,029 basehttp 6700 7860 "GET /static/img/dashboard-preview.png HTTP/1.1" 404 2002
WARNING 2025-06-03 16:41:05,029 basehttp 6700 13564 "GET /static/css/dashboard.css HTTP/1.1" 404 1978
INFO 2025-06-03 16:41:06,909 basehttp 6700 8460 "GET /auth/dashboard/ HTTP/1.1" 302 0
INFO 2025-06-03 16:41:07,072 basehttp 6700 8460 "GET /auth/business/register/ HTTP/1.1" 200 41055
WARNING 2025-06-03 16:41:07,106 basehttp 6700 21948 "GET /static/css/custom.css HTTP/1.1" 404 1969
WARNING 2025-06-03 16:41:07,106 basehttp 6700 8460 "GET /static/css/dashboard.css HTTP/1.1" 404 1978
INFO 2025-06-03 16:41:27,093 basehttp 6700 3048 "POST /auth/business/register/ HTTP/1.1" 200 41143
WARNING 2025-06-03 16:41:27,128 basehttp 6700 20216 "GET /static/css/dashboard.css HTTP/1.1" 404 1978
WARNING 2025-06-03 16:41:27,129 basehttp 6700 3048 "GET /static/css/custom.css HTTP/1.1" 404 1969
INFO 2025-06-03 16:42:42,624 basehttp 6700 11972 "GET / HTTP/1.1" 200 54136
WARNING 2025-06-03 16:42:42,650 basehttp 6700 11972 "GET /static/css/custom.css HTTP/1.1" 404 1969
WARNING 2025-06-03 16:42:42,660 basehttp 6700 16560 "GET /static/css/dashboard.css HTTP/1.1" 404 1978
WARNING 2025-06-03 16:42:42,666 basehttp 6700 12620 "GET /static/img/dashboard-preview.png HTTP/1.1" 404 2002
INFO 2025-06-03 16:42:44,248 basehttp 6700 6260 "GET /auth/dashboard/ HTTP/1.1" 302 0
INFO 2025-06-03 16:42:44,350 basehttp 6700 6260 "GET /auth/business/register/ HTTP/1.1" 200 41055
WARNING 2025-06-03 16:42:44,379 basehttp 6700 6260 "GET /static/css/custom.css HTTP/1.1" 404 1969
WARNING 2025-06-03 16:42:44,386 basehttp 6700 8696 "GET /static/css/dashboard.css HTTP/1.1" 404 1978
INFO 2025-06-03 16:44:28,471 autoreload 6700 12308 D:\WORK PROJECTS\Autowash Build\autowash\apps\accounts\forms.py changed, reloading.
INFO 2025-06-03 16:44:35,037 autoreload 16972 15772 Watching for file changes with StatReloader
INFO 2025-06-03 16:44:54,578 autoreload 16972 15772 D:\WORK PROJECTS\Autowash Build\autowash\apps\accounts\views.py changed, reloading.
INFO 2025-06-03 16:45:00,319 autoreload 24208 21836 Watching for file changes with StatReloader
INFO 2025-06-03 16:45:01,786 basehttp 24208 9688 "GET / HTTP/1.1" 200 54136
WARNING 2025-06-03 16:45:01,830 basehttp 24208 6096 "GET /static/img/dashboard-preview.png HTTP/1.1" 404 2002
WARNING 2025-06-03 16:45:01,837 basehttp 24208 15952 "GET /static/css/dashboard.css HTTP/1.1" 404 1978
WARNING 2025-06-03 16:45:01,838 basehttp 24208 9688 "GET /static/css/custom.css HTTP/1.1" 404 1969
INFO 2025-06-03 16:45:03,754 basehttp 24208 10164 "GET /auth/dashboard/ HTTP/1.1" 302 0
INFO 2025-06-03 16:45:03,930 basehttp 24208 10164 "GET /auth/business/register/ HTTP/1.1" 200 47316
WARNING 2025-06-03 16:45:03,958 basehttp 24208 10164 "GET /static/css/custom.css HTTP/1.1" 404 1969
WARNING 2025-06-03 16:45:03,965 basehttp 24208 10040 "GET /static/css/dashboard.css HTTP/1.1" 404 1978
INFO 2025-06-03 16:47:46,593 autoreload 24208 21836 D:\WORK PROJECTS\Autowash Build\autowash\apps\accounts\forms.py changed, reloading.
INFO 2025-06-03 16:47:53,386 autoreload 15120 20692 Watching for file changes with StatReloader
INFO 2025-06-03 16:47:58,608 autoreload 15120 20692 D:\WORK PROJECTS\Autowash Build\autowash\apps\accounts\views.py changed, reloading.
INFO 2025-06-03 16:48:03,500 autoreload 11068 2392 Watching for file changes with StatReloader
INFO 2025-06-03 16:48:09,794 basehttp 11068 3696 "GET / HTTP/1.1" 200 54136
WARNING 2025-06-03 16:48:09,846 basehttp 11068 3696 "GET /static/css/custom.css HTTP/1.1" 404 1969
WARNING 2025-06-03 16:48:09,858 basehttp 11068 11240 "GET /static/css/dashboard.css HTTP/1.1" 404 1978
WARNING 2025-06-03 16:48:09,869 basehttp 11068 4532 "GET /static/img/dashboard-preview.png HTTP/1.1" 404 2002
INFO 2025-06-03 16:48:18,639 basehttp 11068 2500 "GET /auth/dashboard/ HTTP/1.1" 302 0
INFO 2025-06-03 16:48:18,809 basehttp 11068 2500 "GET /auth/business/register/ HTTP/1.1" 200 43747
WARNING 2025-06-03 16:48:18,851 basehttp 11068 2500 "GET /static/css/custom.css HTTP/1.1" 404 1969
WARNING 2025-06-03 16:48:18,851 basehttp 11068 22848 "GET /static/css/dashboard.css HTTP/1.1" 404 1978
INFO 2025-06-03 16:48:35,904 basehttp 11068 23660 "POST /auth/business/register/ HTTP/1.1" 200 43808
WARNING 2025-06-03 16:48:35,931 basehttp 11068 23660 "GET /static/css/custom.css HTTP/1.1" 404 1969
WARNING 2025-06-03 16:48:35,931 basehttp 11068 1672 "GET /static/css/dashboard.css HTTP/1.1" 404 1978
INFO 2025-06-03 16:48:44,498 basehttp 11068 19524 "POST /auth/business/register/ HTTP/1.1" 200 43808
WARNING 2025-06-03 16:48:44,529 basehttp 11068 19524 "GET /static/css/custom.css HTTP/1.1" 404 1969
WARNING 2025-06-03 16:48:44,529 basehttp 11068 10732 "GET /static/css/dashboard.css HTTP/1.1" 404 1978
INFO 2025-06-03 16:50:05,441 autoreload 11068 2392 D:\WORK PROJECTS\Autowash Build\autowash\apps\accounts\views.py changed, reloading.
INFO 2025-06-03 16:50:10,714 autoreload 1776 12264 Watching for file changes with StatReloader
INFO 2025-06-03 16:50:18,902 autoreload 1776 12264 D:\WORK PROJECTS\Autowash Build\autowash\apps\accounts\views.py changed, reloading.
INFO 2025-06-03 16:50:24,753 autoreload 19580 10596 Watching for file changes with StatReloader
INFO 2025-06-03 16:50:29,811 basehttp 19580 19508 "GET /auth/business/register/ HTTP/1.1" 200 42527
WARNING 2025-06-03 16:50:29,841 basehttp 19580 19508 "GET /static/css/custom.css HTTP/1.1" 404 1969
WARNING 2025-06-03 16:50:29,841 basehttp 19580 14660 "GET /static/css/dashboard.css HTTP/1.1" 404 1978
INFO 2025-06-03 16:50:38,228 basehttp 19580 15508 "POST /auth/business/register/ HTTP/1.1" 200 42846
WARNING 2025-06-03 16:50:38,253 basehttp 19580 15508 "GET /static/css/custom.css HTTP/1.1" 404 1969
WARNING 2025-06-03 16:50:38,253 basehttp 19580 15676 "GET /static/css/dashboard.css HTTP/1.1" 404 1978
INFO 2025-06-03 16:51:15,479 basehttp 19580 13172 "POST /auth/business/register/ HTTP/1.1" 302 0
ERROR 2025-06-03 16:51:15,633 log 19580 13172 Internal Server Error: /subscriptions/
Traceback (most recent call last):
  File "D:\WORK PROJECTS\Autowash Build\autowash\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "D:\WORK PROJECTS\Autowash Build\autowash\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\WORK PROJECTS\Autowash Build\autowash\apps\subscriptions\views.py", line 52, in pricing_view
    return render(request, 'subscriptions/pricing.html', context)
  File "D:\WORK PROJECTS\Autowash Build\autowash\venv\Lib\site-packages\django\shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "D:\WORK PROJECTS\Autowash Build\autowash\venv\Lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "D:\WORK PROJECTS\Autowash Build\autowash\venv\Lib\site-packages\django\template\loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: subscriptions/pricing.html
ERROR 2025-06-03 16:51:15,638 basehttp 19580 13172 "GET /subscriptions/ HTTP/1.1" 500 103971
INFO 2025-06-03 16:52:00,241 basehttp 19580 13172 "GET /subscriptions/ HTTP/1.1" 200 49314
WARNING 2025-06-03 16:52:00,270 basehttp 19580 13172 "GET /static/css/custom.css HTTP/1.1" 404 1969
WARNING 2025-06-03 16:52:00,277 basehttp 19580 22624 "GET /static/css/dashboard.css HTTP/1.1" 404 1978
INFO 2025-06-03 16:52:08,388 basehttp 19580 13080 "GET / HTTP/1.1" 200 54136
WARNING 2025-06-03 16:52:08,417 basehttp 19580 13080 "GET /static/css/custom.css HTTP/1.1" 404 1969
WARNING 2025-06-03 16:52:08,431 basehttp 19580 24160 "GET /static/css/dashboard.css HTTP/1.1" 404 1978
WARNING 2025-06-03 16:52:08,431 basehttp 19580 13816 "GET /static/img/dashboard-preview.png HTTP/1.1" 404 2002
INFO 2025-06-03 16:52:10,325 basehttp 19580 4988 "GET /auth/dashboard/ HTTP/1.1" 302 0
INFO 2025-06-03 16:52:34,412 basehttp 19580 4988 "GET / HTTP/1.1" 200 54136
WARNING 2025-06-03 16:52:34,432 basehttp 19580 4988 "GET /static/css/custom.css HTTP/1.1" 404 1969
WARNING 2025-06-03 16:52:34,437 basehttp 19580 16056 "GET /static/css/dashboard.css HTTP/1.1" 404 1978
WARNING 2025-06-03 16:52:34,443 basehttp 19580 15296 "GET /static/img/dashboard-preview.png HTTP/1.1" 404 2002
INFO 2025-06-03 16:52:37,781 basehttp 19580 22500 "GET /auth/dashboard/ HTTP/1.1" 302 0
INFO 2025-06-03 16:54:30,876 autoreload 19580 10596 D:\WORK PROJECTS\Autowash Build\autowash\apps\accounts\forms.py changed, reloading.
INFO 2025-06-03 16:54:37,077 autoreload 19120 14068 Watching for file changes with StatReloader
INFO 2025-06-03 16:55:47,533 autoreload 19120 14068 D:\WORK PROJECTS\Autowash Build\autowash\apps\accounts\views.py changed, reloading.
INFO 2025-06-03 16:55:53,343 autoreload 14420 12956 Watching for file changes with StatReloader
INFO 2025-06-03 16:56:02,345 autoreload 14420 12956 D:\WORK PROJECTS\Autowash Build\autowash\apps\accounts\views.py changed, reloading.
INFO 2025-06-03 16:56:09,129 autoreload 10960 10936 Watching for file changes with StatReloader
INFO 2025-06-03 16:56:19,134 autoreload 10960 10936 D:\WORK PROJECTS\Autowash Build\autowash\apps\accounts\views.py changed, reloading.
INFO 2025-06-03 16:56:24,918 autoreload 11132 1672 Watching for file changes with StatReloader
INFO 2025-06-03 16:57:04,087 basehttp 11132 14776 "GET / HTTP/1.1" 200 54136
WARNING 2025-06-03 16:57:04,129 basehttp 11132 24520 "GET /static/css/dashboard.css HTTP/1.1" 404 1978
WARNING 2025-06-03 16:57:04,133 basehttp 11132 19056 "GET /static/img/dashboard-preview.png HTTP/1.1" 404 2002
WARNING 2025-06-03 16:57:04,134 basehttp 11132 14776 "GET /static/css/custom.css HTTP/1.1" 404 1969
INFO 2025-06-03 16:57:06,172 basehttp 11132 12084 "GET /auth/logout/ HTTP/1.1" 302 0
INFO 2025-06-03 16:57:06,269 basehttp 11132 12084 "GET / HTTP/1.1" 200 54768
WARNING 2025-06-03 16:57:06,306 basehttp 11132 13744 "GET /static/css/dashboard.css HTTP/1.1" 404 1978
WARNING 2025-06-03 16:57:06,306 basehttp 11132 12084 "GET /static/css/custom.css HTTP/1.1" 404 1969
WARNING 2025-06-03 16:57:06,314 basehttp 11132 8292 "GET /static/img/dashboard-preview.png HTTP/1.1" 404 2002
INFO 2025-06-03 16:57:08,790 basehttp 11132 17004 "GET /auth/login/ HTTP/1.1" 200 43518
WARNING 2025-06-03 16:57:08,827 basehttp 11132 17004 "GET /static/css/custom.css HTTP/1.1" 404 1969
WARNING 2025-06-03 16:57:08,835 basehttp 11132 15252 "GET /static/css/dashboard.css HTTP/1.1" 404 1978
INFO 2025-06-03 16:57:12,435 basehttp 11132 18640 "GET /auth/register/ HTTP/1.1" 200 51712
WARNING 2025-06-03 16:57:12,468 basehttp 11132 18640 "GET /static/css/custom.css HTTP/1.1" 404 1969
WARNING 2025-06-03 16:57:12,476 basehttp 11132 14396 "GET /static/css/dashboard.css HTTP/1.1" 404 1978
INFO 2025-06-03 16:57:43,542 basehttp 11132 5604 "POST /auth/register/ HTTP/1.1" 200 51876
WARNING 2025-06-03 16:57:43,574 basehttp 11132 5604 "GET /static/css/custom.css HTTP/1.1" 404 1969
WARNING 2025-06-03 16:57:43,574 basehttp 11132 23316 "GET /static/css/dashboard.css HTTP/1.1" 404 1978
INFO 2025-06-03 16:58:32,344 basehttp 11132 3244 "POST /auth/register/ HTTP/1.1" 302 0
INFO 2025-06-03 16:58:32,488 basehttp 11132 3244 "GET /auth/business/register/ HTTP/1.1" 200 60730
WARNING 2025-06-03 16:58:32,534 basehttp 11132 3244 "GET /static/css/custom.css HTTP/1.1" 404 1969
WARNING 2025-06-03 16:58:32,534 basehttp 11132 18252 "GET /static/css/dashboard.css HTTP/1.1" 404 1978
INFO 2025-06-03 16:58:43,315 basehttp 11132 13208 "GET /auth/ajax/check-business-name/?name=Wash HTTP/1.1" 200 51
INFO 2025-06-03 16:58:53,168 basehttp 11132 13208 "GET /auth/ajax/check-business-name/?name=Test HTTP/1.1" 200 56
INFO 2025-06-03 16:58:58,911 basehttp 11132 13208 "GET /auth/ajax/check-business-name/?name=Wash HTTP/1.1" 200 51
INFO 2025-06-03 17:02:25,045 autoreload 11132 1672 D:\WORK PROJECTS\Autowash Build\autowash\apps\accounts\forms.py changed, reloading.
INFO 2025-06-03 17:02:31,149 autoreload 1248 21124 Watching for file changes with StatReloader
INFO 2025-06-03 17:02:54,952 autoreload 1248 21124 D:\WORK PROJECTS\Autowash Build\autowash\apps\accounts\views.py changed, reloading.
INFO 2025-06-03 17:03:01,016 autoreload 3336 6328 Watching for file changes with StatReloader
INFO 2025-06-03 17:03:37,999 basehttp 3336 17596 "GET /auth/business/register/ HTTP/1.1" 200 49538
WARNING 2025-06-03 17:03:38,029 basehttp 3336 17596 "GET /static/css/custom.css HTTP/1.1" 404 1969
WARNING 2025-06-03 17:03:38,029 basehttp 3336 2976 "GET /static/css/dashboard.css HTTP/1.1" 404 1978
INFO 2025-06-03 17:06:20,510 autoreload 3336 6328 D:\WORK PROJECTS\Autowash Build\autowash\apps\accounts\forms.py changed, reloading.
INFO 2025-06-03 17:06:26,850 autoreload 2500 5996 Watching for file changes with StatReloader
INFO 2025-06-03 17:07:12,154 autoreload 2500 5996 D:\WORK PROJECTS\Autowash Build\autowash\apps\accounts\views.py changed, reloading.
INFO 2025-06-03 17:07:18,526 autoreload 3696 10976 Watching for file changes with StatReloader
INFO 2025-06-03 17:08:44,347 basehttp 3696 19408 "GET / HTTP/1.1" 200 54136
WARNING 2025-06-03 17:08:44,385 basehttp 3696 19408 "GET /static/css/custom.css HTTP/1.1" 404 1969
WARNING 2025-06-03 17:08:44,386 basehttp 3696 4992 "GET /static/css/dashboard.css HTTP/1.1" 404 1978
WARNING 2025-06-03 17:08:44,392 basehttp 3696 22056 "GET /static/img/dashboard-preview.png HTTP/1.1" 404 2002
INFO 2025-06-03 17:08:46,497 basehttp 3696 8312 "GET /auth/dashboard/ HTTP/1.1" 302 0
INFO 2025-06-03 17:08:46,640 basehttp 3696 8312 "GET /auth/business/register/ HTTP/1.1" 200 53525
WARNING 2025-06-03 17:08:46,668 basehttp 3696 8312 "GET /static/css/custom.css HTTP/1.1" 404 1969
WARNING 2025-06-03 17:08:46,674 basehttp 3696 11848 "GET /static/css/dashboard.css HTTP/1.1" 404 1978
INFO 2025-06-03 17:08:54,239 basehttp 3696 15252 "GET /auth/ajax/check-business-name/?name=Alex HTTP/1.1" 200 51
INFO 2025-06-03 17:10:34,314 autoreload 3696 10976 D:\WORK PROJECTS\Autowash Build\autowash\apps\accounts\forms.py changed, reloading.
INFO 2025-06-03 17:10:39,245 autoreload 22364 3884 Watching for file changes with StatReloader
INFO 2025-06-03 17:10:40,674 basehttp 22364 23728 "GET /auth/business/register/ HTTP/1.1" 200 52052
WARNING 2025-06-03 17:10:40,739 basehttp 22364 23728 "GET /static/css/custom.css HTTP/1.1" 404 1969
WARNING 2025-06-03 17:10:40,749 basehttp 22364 6300 "GET /static/css/dashboard.css HTTP/1.1" 404 1978
INFO 2025-06-03 17:10:44,786 basehttp 22364 23664 "GET /auth/dashboard/ HTTP/1.1" 302 0
INFO 2025-06-03 17:10:44,878 basehttp 22364 23664 "GET /auth/business/register/ HTTP/1.1" 200 53259
WARNING 2025-06-03 17:10:44,902 basehttp 22364 23664 "GET /static/css/custom.css HTTP/1.1" 404 1969
WARNING 2025-06-03 17:10:44,909 basehttp 22364 24512 "GET /static/css/dashboard.css HTTP/1.1" 404 1978
INFO 2025-06-03 17:10:51,641 basehttp 22364 18640 "GET /auth/ajax/check-business-name/?name=Test HTTP/1.1" 200 56
INFO 2025-06-03 17:10:56,051 basehttp 22364 18640 "GET /auth/ajax/check-business-name/?name=James HTTP/1.1" 200 51
INFO 2025-06-03 17:11:29,476 basehttp 22364 18640 "GET / HTTP/1.1" 200 54136
WARNING 2025-06-03 17:11:29,523 basehttp 22364 24104 "GET /static/css/dashboard.css HTTP/1.1" 404 1978
WARNING 2025-06-03 17:11:29,528 basehttp 22364 18640 "GET /static/css/custom.css HTTP/1.1" 404 1969
WARNING 2025-06-03 17:11:29,528 basehttp 22364 11516 "GET /static/img/dashboard-preview.png HTTP/1.1" 404 2002
INFO 2025-06-03 17:11:31,004 basehttp 22364 8296 "GET /auth/dashboard/ HTTP/1.1" 302 0
INFO 2025-06-03 17:11:31,208 basehttp 22364 8296 "GET /auth/business/register/ HTTP/1.1" 200 43747
WARNING 2025-06-03 17:11:31,246 basehttp 22364 8296 "GET /static/css/custom.css HTTP/1.1" 404 1969
WARNING 2025-06-03 17:11:31,254 basehttp 22364 4460 "GET /static/css/dashboard.css HTTP/1.1" 404 1978
INFO 2025-06-03 17:11:42,648 basehttp 22364 14764 "POST /auth/business/register/ HTTP/1.1" 200 42904
WARNING 2025-06-03 17:11:42,675 basehttp 22364 11128 "GET /static/css/dashboard.css HTTP/1.1" 404 1978
WARNING 2025-06-03 17:11:42,675 basehttp 22364 14764 "GET /static/css/custom.css HTTP/1.1" 404 1969
INFO 2025-06-03 17:12:23,654 basehttp 22364 15684 "POST /auth/business/register/ HTTP/1.1" 302 0
INFO 2025-06-03 17:12:23,777 basehttp 22364 15684 "GET /subscriptions/ HTTP/1.1" 200 49312
WARNING 2025-06-03 17:12:23,798 basehttp 22364 15684 "GET /static/css/custom.css HTTP/1.1" 404 1969
WARNING 2025-06-03 17:12:23,804 basehttp 22364 20016 "GET /static/css/dashboard.css HTTP/1.1" 404 1978
INFO 2025-06-03 17:13:12,506 basehttp 22364 13076 "GET /auth/dashboard/ HTTP/1.1" 302 0
INFO 2025-06-03 17:16:08,195 autoreload 22364 3884 D:\WORK PROJECTS\Autowash Build\autowash\apps\accounts\views.py changed, reloading.
INFO 2025-06-03 17:16:14,977 autoreload 12920 15296 Watching for file changes with StatReloader
INFO 2025-06-03 17:16:25,664 basehttp 12920 19620 "GET / HTTP/1.1" 200 54136
WARNING 2025-06-03 17:16:25,702 basehttp 12920 19620 "GET /static/css/custom.css HTTP/1.1" 404 1969
WARNING 2025-06-03 17:16:25,709 basehttp 12920 1800 "GET /static/css/dashboard.css HTTP/1.1" 404 1978
WARNING 2025-06-03 17:16:25,715 basehttp 12920 1672 "GET /static/img/dashboard-preview.png HTTP/1.1" 404 2002
INFO 2025-06-03 17:16:27,497 basehttp 12920 5176 "GET /auth/dashboard/ HTTP/1.1" 302 0
INFO 2025-06-03 17:16:38,020 basehttp 12920 5176 "GET /auth/logout/ HTTP/1.1" 302 0
INFO 2025-06-03 17:16:38,262 basehttp 12920 5176 "GET / HTTP/1.1" 200 54768
WARNING 2025-06-03 17:16:38,317 basehttp 12920 5176 "GET /static/css/custom.css HTTP/1.1" 404 1969
WARNING 2025-06-03 17:16:38,317 basehttp 12920 6656 "GET /static/img/dashboard-preview.png HTTP/1.1" 404 2002
WARNING 2025-06-03 17:16:38,317 basehttp 12920 24324 "GET /static/css/dashboard.css HTTP/1.1" 404 1978
INFO 2025-06-03 17:16:39,668 basehttp 12920 23764 "GET /auth/login/ HTTP/1.1" 200 43518
WARNING 2025-06-03 17:16:39,723 basehttp 12920 24300 "GET /static/css/dashboard.css HTTP/1.1" 404 1978
WARNING 2025-06-03 17:16:39,723 basehttp 12920 23764 "GET /static/css/custom.css HTTP/1.1" 404 1969
INFO 2025-06-03 17:16:42,199 basehttp 12920 18276 "GET /auth/register/ HTTP/1.1" 200 51712
WARNING 2025-06-03 17:16:42,233 basehttp 12920 18276 "GET /static/css/custom.css HTTP/1.1" 404 1969
WARNING 2025-06-03 17:16:42,240 basehttp 12920 11840 "GET /static/css/dashboard.css HTTP/1.1" 404 1978
INFO 2025-06-03 17:17:32,332 basehttp 12920 22024 "POST /auth/register/ HTTP/1.1" 302 0
INFO 2025-06-03 17:17:32,503 basehttp 12920 22024 "GET /auth/business/register/ HTTP/1.1" 200 53502
WARNING 2025-06-03 17:17:32,564 basehttp 12920 22024 "GET /static/css/custom.css HTTP/1.1" 404 1969
WARNING 2025-06-03 17:17:32,564 basehttp 12920 15436 "GET /static/css/dashboard.css HTTP/1.1" 404 1978
INFO 2025-06-03 17:17:38,245 basehttp 12920 21528 "GET /auth/ajax/check-business-name/?name=Brandon HTTP/1.1" 200 51
INFO 2025-06-03 17:18:21,940 basehttp 12920 21528 "GET /auth/business/register/ HTTP/1.1" 200 42527
WARNING 2025-06-03 17:18:21,965 basehttp 12920 21528 "GET /static/css/custom.css HTTP/1.1" 404 1969
WARNING 2025-06-03 17:18:21,972 basehttp 12920 2556 "GET /static/css/dashboard.css HTTP/1.1" 404 1978
INFO 2025-06-03 17:18:39,520 basehttp 12920 24472 "POST /auth/business/register/ HTTP/1.1" 200 42904
WARNING 2025-06-03 17:18:39,543 basehttp 12920 24472 "GET /static/css/custom.css HTTP/1.1" 404 1969
WARNING 2025-06-03 17:18:39,551 basehttp 12920 11132 "GET /static/css/dashboard.css HTTP/1.1" 404 1978
INFO 2025-06-03 17:19:43,190 autoreload 12920 15296 D:\WORK PROJECTS\Autowash Build\autowash\apps\accounts\forms.py changed, reloading.
INFO 2025-06-03 17:19:48,526 autoreload 10092 23428 Watching for file changes with StatReloader
INFO 2025-06-03 17:19:49,774 basehttp 10092 14548 "GET /auth/business/register/ HTTP/1.1" 200 45634
WARNING 2025-06-03 17:19:49,805 basehttp 10092 14548 "GET /static/css/custom.css HTTP/1.1" 404 1969
WARNING 2025-06-03 17:19:49,812 basehttp 10092 4988 "GET /static/css/dashboard.css HTTP/1.1" 404 1978
INFO 2025-06-03 17:20:13,675 basehttp 10092 13432 "POST /auth/business/register/ HTTP/1.1" 200 46052
WARNING 2025-06-03 17:20:13,700 basehttp 10092 13432 "GET /static/css/custom.css HTTP/1.1" 404 1969
WARNING 2025-06-03 17:20:13,708 basehttp 10092 11972 "GET /static/css/dashboard.css HTTP/1.1" 404 1978
INFO 2025-06-03 17:20:27,390 basehttp 10092 24328 "POST /auth/business/register/ HTTP/1.1" 200 46052
WARNING 2025-06-03 17:20:27,422 basehttp 10092 7924 "GET /static/css/dashboard.css HTTP/1.1" 404 1978
WARNING 2025-06-03 17:20:27,422 basehttp 10092 24328 "GET /static/css/custom.css HTTP/1.1" 404 1969
INFO 2025-06-03 17:20:37,741 basehttp 10092 21988 "POST /auth/business/register/ HTTP/1.1" 200 46052
WARNING 2025-06-03 17:20:37,768 basehttp 10092 21988 "GET /static/css/custom.css HTTP/1.1" 404 1969
WARNING 2025-06-03 17:20:37,775 basehttp 10092 1684 "GET /static/css/dashboard.css HTTP/1.1" 404 1978
INFO 2025-06-03 17:20:46,848 basehttp 10092 13460 "POST /auth/business/register/ HTTP/1.1" 200 46052
WARNING 2025-06-03 17:20:46,874 basehttp 10092 13460 "GET /static/css/custom.css HTTP/1.1" 404 1969
WARNING 2025-06-03 17:20:46,874 basehttp 10092 17412 "GET /static/css/dashboard.css HTTP/1.1" 404 1978
INFO 2025-06-03 17:20:54,819 basehttp 10092 7992 "POST /auth/business/register/ HTTP/1.1" 200 46052
WARNING 2025-06-03 17:20:54,852 basehttp 10092 14028 "GET /static/css/dashboard.css HTTP/1.1" 404 1978
WARNING 2025-06-03 17:20:54,852 basehttp 10092 7992 "GET /static/css/custom.css HTTP/1.1" 404 1969
INFO 2025-06-03 17:21:01,816 basehttp 10092 8344 "POST /auth/business/register/ HTTP/1.1" 200 46052
WARNING 2025-06-03 17:21:01,843 basehttp 10092 8344 "GET /static/css/custom.css HTTP/1.1" 404 1969
WARNING 2025-06-03 17:21:01,849 basehttp 10092 16460 "GET /static/css/dashboard.css HTTP/1.1" 404 1978
INFO 2025-06-03 17:21:16,923 autoreload 10092 23428 D:\WORK PROJECTS\Autowash Build\autowash\apps\accounts\forms.py changed, reloading.
INFO 2025-06-03 17:21:21,890 autoreload 13500 15312 Watching for file changes with StatReloader
INFO 2025-06-03 17:21:28,145 basehttp 13500 10988 "GET /auth/business/register/ HTTP/1.1" 200 42527
WARNING 2025-06-03 17:21:28,206 basehttp 13500 10988 "GET /static/css/custom.css HTTP/1.1" 404 1969
WARNING 2025-06-03 17:21:28,206 basehttp 13500 20836 "GET /static/css/dashboard.css HTTP/1.1" 404 1978
INFO 2025-06-03 17:21:42,166 basehttp 13500 12084 "GET /auth/logout/ HTTP/1.1" 302 0
INFO 2025-06-03 17:21:42,326 basehttp 13500 12084 "GET / HTTP/1.1" 200 54768
WARNING 2025-06-03 17:21:42,359 basehttp 13500 12084 "GET /static/css/custom.css HTTP/1.1" 404 1969
WARNING 2025-06-03 17:21:42,367 basehttp 13500 14532 "GET /static/css/dashboard.css HTTP/1.1" 404 1978
WARNING 2025-06-03 17:21:42,374 basehttp 13500 3308 "GET /static/img/dashboard-preview.png HTTP/1.1" 404 2002
INFO 2025-06-03 17:21:44,028 basehttp 13500 14472 "GET /auth/login/ HTTP/1.1" 200 43518
WARNING 2025-06-03 17:21:44,057 basehttp 13500 14472 "GET /static/css/custom.css HTTP/1.1" 404 1969
WARNING 2025-06-03 17:21:44,064 basehttp 13500 5604 "GET /static/css/dashboard.css HTTP/1.1" 404 1978
INFO 2025-06-03 17:22:00,758 basehttp 13500 22908 "POST /auth/login/ HTTP/1.1" 200 44305
WARNING 2025-06-03 17:22:00,792 basehttp 13500 22908 "GET /static/css/custom.css HTTP/1.1" 404 1969
WARNING 2025-06-03 17:22:00,793 basehttp 13500 15284 "GET /static/css/dashboard.css HTTP/1.1" 404 1978
INFO 2025-06-03 17:22:19,323 basehttp 13500 20208 "POST /auth/login/ HTTP/1.1" 200 44305
WARNING 2025-06-03 17:22:19,353 basehttp 13500 20208 "GET /static/css/custom.css HTTP/1.1" 404 1969
WARNING 2025-06-03 17:22:19,353 basehttp 13500 17024 "GET /static/css/dashboard.css HTTP/1.1" 404 1978
INFO 2025-06-03 17:22:26,659 basehttp 13500 2300 "GET / HTTP/1.1" 200 53991
WARNING 2025-06-03 17:22:26,679 basehttp 13500 2300 "GET /static/css/custom.css HTTP/1.1" 404 1969
WARNING 2025-06-03 17:22:26,690 basehttp 13500 20448 "GET /static/img/dashboard-preview.png HTTP/1.1" 404 2002
WARNING 2025-06-03 17:22:26,690 basehttp 13500 18216 "GET /static/css/dashboard.css HTTP/1.1" 404 1978
