INFO 2025-06-03 12:28:19,180 autoreload 3092 23084 Watching for file changes with StatReloader
INFO 2025-06-03 12:29:04,495 autoreload 15856 1960 Watching for file changes with StatReloader
WARNING 2025-06-03 12:29:21,601 log 15856 23364 Not Found: /
WARNING 2025-06-03 12:29:21,601 basehttp 15856 23364 "GET / HTTP/1.1" 404 1937
WARNING 2025-06-03 12:29:21,995 log 15856 21484 Not Found: /favicon.ico
WARNING 2025-06-03 12:29:21,995 basehttp 15856 21484 "GET /favicon.ico HTTP/1.1" 404 1835
WARNING 2025-06-03 12:31:01,898 log 15856 1132 Not Found: /login
WARNING 2025-06-03 12:31:01,898 basehttp 15856 1132 "GET /login HTTP/1.1" 404 1823
WARNING 2025-06-03 12:31:05,776 log 15856 13536 Not Found: /accounts
WARNING 2025-06-03 12:31:05,777 basehttp 15856 13536 "GET /accounts HTTP/1.1" 404 1829
WARNING 2025-06-03 12:36:31,020 log 15856 23388 Not Found: /accounts
WARNING 2025-06-03 12:36:31,021 basehttp 15856 23388 "GET /accounts HTTP/1.1" 404 1829
INFO 2025-06-03 12:37:03,064 autoreload 10288 2512 Watching for file changes with StatReloader
WARNING 2025-06-03 12:37:07,363 log 10288 12708 Not Found: /
WARNING 2025-06-03 12:37:07,364 basehttp 10288 12708 "GET / HTTP/1.1" 404 1937
ERROR 2025-06-03 12:37:13,541 log 10288 8476 Internal Server Error: /
Traceback (most recent call last):
  File "D:\WORK PROJECTS\Autowash Build\autowash\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "D:\WORK PROJECTS\Autowash Build\autowash\venv\Lib\site-packages\django\utils\deprecation.py", line 119, in __call__
    response = self.process_request(request)
  File "D:\WORK PROJECTS\Autowash Build\autowash\venv\Lib\site-packages\django_tenants\middleware\main.py", line 50, in process_request
    tenant.domain_url = hostname
    ^^^^^^^^^^^^^^^^^
AttributeError: property 'domain_url' of 'Business' object has no setter
ERROR 2025-06-03 12:37:13,545 basehttp 10288 8476 "GET / HTTP/1.1" 500 86898
ERROR 2025-06-03 12:37:14,157 log 10288 12488 Internal Server Error: /favicon.ico
Traceback (most recent call last):
  File "D:\WORK PROJECTS\Autowash Build\autowash\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "D:\WORK PROJECTS\Autowash Build\autowash\venv\Lib\site-packages\django\utils\deprecation.py", line 119, in __call__
    response = self.process_request(request)
  File "D:\WORK PROJECTS\Autowash Build\autowash\venv\Lib\site-packages\django_tenants\middleware\main.py", line 50, in process_request
    tenant.domain_url = hostname
    ^^^^^^^^^^^^^^^^^
AttributeError: property 'domain_url' of 'Business' object has no setter
ERROR 2025-06-03 12:37:14,161 basehttp 10288 12488 "GET /favicon.ico HTTP/1.1" 500 86698
INFO 2025-06-03 12:43:36,434 autoreload 10288 2512 D:\WORK PROJECTS\Autowash Build\autowash\apps\accounts\models.py changed, reloading.
INFO 2025-06-03 12:43:41,125 autoreload 15856 22184 Watching for file changes with StatReloader
ERROR 2025-06-03 12:44:05,721 log 15856 15152 Internal Server Error: /
Traceback (most recent call last):
  File "D:\WORK PROJECTS\Autowash Build\autowash\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "D:\WORK PROJECTS\Autowash Build\autowash\venv\Lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
  File "D:\WORK PROJECTS\Autowash Build\autowash\venv\Lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "D:\WORK PROJECTS\Autowash Build\autowash\venv\Lib\site-packages\django\template\response.py", line 90, in rendered_content
    template = self.resolve_template(self.template_name)
  File "D:\WORK PROJECTS\Autowash Build\autowash\venv\Lib\site-packages\django\template\response.py", line 72, in resolve_template
    return select_template(template, using=self.using)
  File "D:\WORK PROJECTS\Autowash Build\autowash\venv\Lib\site-packages\django\template\loader.py", line 47, in select_template
    raise TemplateDoesNotExist(", ".join(template_name_list), chain=chain)
django.template.exceptions.TemplateDoesNotExist: public/landing.html
ERROR 2025-06-03 12:44:05,726 basehttp 15856 15152 "GET / HTTP/1.1" 500 105335
WARNING 2025-06-03 12:44:06,178 log 15856 15152 Not Found: /favicon.ico
WARNING 2025-06-03 12:44:06,179 basehttp 15856 15152 "GET /favicon.ico HTTP/1.1" 404 3682
INFO 2025-06-03 12:48:03,185 basehttp 15856 14844 code 400, message Bad request version ("\x9c\x1b\x95'\x83³AÕ\x8en\x91\x8eòsZlà»/j9\x92\x98")
ERROR 2025-06-03 12:48:03,198 basehttp 15856 14844 You're accessing the development server over HTTPS, but it only supports HTTP.
INFO 2025-06-03 12:48:03,204 basehttp 15856 11160 code 400, message Bad request version ('Ömù')
ERROR 2025-06-03 12:48:03,205 basehttp 15856 11160 You're accessing the development server over HTTPS, but it only supports HTTP.
INFO 2025-06-03 12:48:07,268 basehttp 15856 3112 code 400, message Bad HTTP/0.9 request type ('\x16\x03\x01\x06à\x01\x00\x06Ü\x03\x03*r@9')
ERROR 2025-06-03 12:48:07,269 basehttp 15856 3112 You're accessing the development server over HTTPS, but it only supports HTTP.
INFO 2025-06-03 12:48:07,269 basehttp 15856 13276 code 400, message Bad HTTP/0.9 request type ('\x16\x03\x01\x06À\x01\x00\x06¼\x03\x03ÏZAÛ\x9fàð£yH\x02{&Å(uþh¤øÑbGñµ\x1ao-"ø¥L')
ERROR 2025-06-03 12:48:07,270 basehttp 15856 13276 You're accessing the development server over HTTPS, but it only supports HTTP.
INFO 2025-06-03 12:48:07,271 basehttp 15856 23452 code 400, message Bad request syntax ('\x16\x03\x01\x06À\x01\x00\x06¼\x03\x03K\x07©èz¨×¬Ðà\x1bø')
ERROR 2025-06-03 12:48:07,271 basehttp 15856 23452 You're accessing the development server over HTTPS, but it only supports HTTP.
INFO 2025-06-03 12:48:07,272 basehttp 15856 23776 code 400, message Bad request version ('íÖ^½ÂF')
ERROR 2025-06-03 12:48:07,272 basehttp 15856 23776 You're accessing the development server over HTTPS, but it only supports HTTP.
INFO 2025-06-03 12:48:16,992 basehttp 15856 10156 code 400, message Bad request version ('ºº\x13\x01\x13\x02\x13\x03À+À/À,À0Ì©Ì¨À\x13À\x14\x00\x9c\x00\x9d\x00/\x005\x01\x00\x06\x93JJ\x00\x00\x00\x1b\x00\x03\x02\x00\x02ÿ\x01\x00\x01\x00\x00')
ERROR 2025-06-03 12:48:16,993 basehttp 15856 10156 You're accessing the development server over HTTPS, but it only supports HTTP.
INFO 2025-06-03 12:48:16,995 basehttp 15856 19960 code 400, message Bad request version ('AkÖ÷Å\x8c\x19ÜiW{µ·')
ERROR 2025-06-03 12:48:16,996 basehttp 15856 19960 You're accessing the development server over HTTPS, but it only supports HTTP.
INFO 2025-06-03 12:48:24,697 basehttp 15856 19956 code 400, message Bad request version ('A¦Z\x02ðq¤\x02î$Ï«')
ERROR 2025-06-03 12:48:24,698 basehttp 15856 19956 You're accessing the development server over HTTPS, but it only supports HTTP.
INFO 2025-06-03 12:48:24,700 basehttp 15856 13164 code 400, message Bad request version ('\x00\x12\x00\x10\x04\x03\x08\x04\x04\x01\x05\x03\x08\x05\x05\x01\x08\x06\x06\x01\x00\x05\x00\x05\x01\x00\x00\x00\x00\x00\x1b\x00\x03\x02\x00\x02\x00')
ERROR 2025-06-03 12:48:24,700 basehttp 15856 13164 You're accessing the development server over HTTPS, but it only supports HTTP.
INFO 2025-06-03 12:48:24,703 basehttp 15856 13344 code 400, message Bad request version ('aiñ\x89\x80Z.^a=i')
INFO 2025-06-03 12:48:24,704 basehttp 15856 23648 code 400, message Bad request version ('ÈÆØ')
ERROR 2025-06-03 12:48:24,704 basehttp 15856 13344 You're accessing the development server over HTTPS, but it only supports HTTP.
ERROR 2025-06-03 12:48:24,704 basehttp 15856 23648 You're accessing the development server over HTTPS, but it only supports HTTP.
INFO 2025-06-03 12:48:24,707 basehttp 15856 13492 code 400, message Bad request version ('\x00\x02\x01\x00\x00\x12\x00\x00\x00\x17\x00\x00\x00')
INFO 2025-06-03 12:48:24,707 basehttp 15856 16056 code 400, message Bad HTTP/0.9 request type ('\x16\x03\x01\x07\x00\x01\x00\x06ü\x03\x03\x9cÀIåPx\x05\x07íëNèmûo_\x93Õä\x15\x0774\x86)Ûän]\x04Ê%')
ERROR 2025-06-03 12:48:24,708 basehttp 15856 13492 You're accessing the development server over HTTPS, but it only supports HTTP.
ERROR 2025-06-03 12:48:24,710 basehttp 15856 16056 You're accessing the development server over HTTPS, but it only supports HTTP.
INFO 2025-06-03 12:49:56,039 basehttp 15856 3444 code 400, message Bad request version ('\x02\x95\x8cª?IØ\x07\x12¥,P\x9bÕ¸v3Y\x86\x06u[g¸b\x05cÿ\x9a!I§\x7fI.àU;\x185Èô}\x946ûmqb¥È\x95]S&\x9cÙ´z×WÎ5!a')
ERROR 2025-06-03 12:49:56,040 basehttp 15856 3444 You're accessing the development server over HTTPS, but it only supports HTTP.
INFO 2025-06-03 12:49:56,042 basehttp 15856 19328 code 400, message Bad request syntax ("\x16\x03\x01\x06à\x01\x00\x06Ü\x03\x03M%9'ºq&«\x91L\x11\x1b\x93ÛÚx*'\x94\x00\x8a\x8eR\x02")
ERROR 2025-06-03 12:49:56,042 basehttp 15856 19328 You're accessing the development server over HTTPS, but it only supports HTTP.
INFO 2025-06-03 12:49:58,692 basehttp 15856 8476 code 400, message Bad request version ('i4\x82')
ERROR 2025-06-03 12:49:58,693 basehttp 15856 8476 You're accessing the development server over HTTPS, but it only supports HTTP.
INFO 2025-06-03 12:49:58,694 basehttp 15856 17412 code 400, message Bad request version ('"K\x8dðxúU\xad®\x16yW\x92e\x9bëë\x83Kâþ\x8e')
ERROR 2025-06-03 12:49:58,695 basehttp 15856 17412 You're accessing the development server over HTTPS, but it only supports HTTP.
INFO 2025-06-03 12:49:58,697 basehttp 15856 15792 code 400, message Bad request version ('(')
ERROR 2025-06-03 12:49:58,698 basehttp 15856 15792 You're accessing the development server over HTTPS, but it only supports HTTP.
INFO 2025-06-03 12:49:58,698 basehttp 15856 4428 code 400, message Bad request version ('X\x98\x05¼\x8d»\x19Ð\x10H^\x18Ï')
ERROR 2025-06-03 12:49:58,699 basehttp 15856 4428 You're accessing the development server over HTTPS, but it only supports HTTP.
INFO 2025-06-03 12:49:58,700 basehttp 15856 15976 code 400, message Bad request version ('::\x13\x01\x13\x02\x13\x03À+À/À,À0Ì©Ì¨À\x13À\x14\x00\x9c\x00\x9d\x00/\x005\x01\x00\x06S\x1a\x1a\x00\x00\x00+\x00\x07\x06ªª\x03\x04\x03\x03\x00')
ERROR 2025-06-03 12:49:58,700 basehttp 15856 15976 You're accessing the development server over HTTPS, but it only supports HTTP.
INFO 2025-06-03 12:49:58,701 basehttp 15856 23944 code 400, message Bad request syntax ('\x16\x03\x01\x06à\x01\x00\x06Ü\x03\x03ZÆ\x8fX\x13SÑ¤x\x8d\x94Ó\x05íHú]\x80\x88')
ERROR 2025-06-03 12:49:58,702 basehttp 15856 23944 You're accessing the development server over HTTPS, but it only supports HTTP.
INFO 2025-06-03 12:50:22,040 basehttp 15856 21712 code 400, message Bad request version ('ªª\x13\x01\x13\x02\x13\x03À+À/À,À0Ì©Ì¨À\x13À\x14\x00\x9c\x00\x9d\x00/\x005\x01\x00\x06\x93ªª\x00\x00\x00')
ERROR 2025-06-03 12:50:22,040 basehttp 15856 21712 You're accessing the development server over HTTPS, but it only supports HTTP.
INFO 2025-06-03 12:50:22,042 basehttp 15856 20212 code 400, message Bad request version ('\x00\x02\x01\x00\x00-\x00\x02\x01\x01\x00+\x00\x07\x06úú\x03\x04\x03\x03\x00')
ERROR 2025-06-03 12:50:22,042 basehttp 15856 20212 You're accessing the development server over HTTPS, but it only supports HTTP.
INFO 2025-06-03 12:51:21,571 basehttp 15856 6776 code 400, message Bad request version ('\x02h2\x08http/1.1\x00')
ERROR 2025-06-03 12:51:21,572 basehttp 15856 6776 You're accessing the development server over HTTPS, but it only supports HTTP.
INFO 2025-06-03 12:51:21,573 basehttp 15856 21484 code 400, message Bad HTTP/0.9 request type ('\x16\x03\x01\x06')
ERROR 2025-06-03 12:51:21,574 basehttp 15856 21484 You're accessing the development server over HTTPS, but it only supports HTTP.
INFO 2025-06-03 12:52:08,866 autoreload 23068 21712 Watching for file changes with StatReloader
ERROR 2025-06-03 12:52:14,704 log 23068 13108 Internal Server Error: /
Traceback (most recent call last):
  File "D:\WORK PROJECTS\Autowash Build\autowash\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "D:\WORK PROJECTS\Autowash Build\autowash\venv\Lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
  File "D:\WORK PROJECTS\Autowash Build\autowash\venv\Lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "D:\WORK PROJECTS\Autowash Build\autowash\venv\Lib\site-packages\django\template\response.py", line 90, in rendered_content
    template = self.resolve_template(self.template_name)
  File "D:\WORK PROJECTS\Autowash Build\autowash\venv\Lib\site-packages\django\template\response.py", line 72, in resolve_template
    return select_template(template, using=self.using)
  File "D:\WORK PROJECTS\Autowash Build\autowash\venv\Lib\site-packages\django\template\loader.py", line 47, in select_template
    raise TemplateDoesNotExist(", ".join(template_name_list), chain=chain)
django.template.exceptions.TemplateDoesNotExist: public/landing.html
ERROR 2025-06-03 12:52:14,709 basehttp 23068 13108 "GET / HTTP/1.1" 500 100814
WARNING 2025-06-03 12:52:15,168 log 23068 14004 Not Found: /favicon.ico
WARNING 2025-06-03 12:52:15,169 basehttp 23068 14004 "GET /favicon.ico HTTP/1.1" 404 3682
WARNING 2025-06-03 12:52:30,135 log 23068 12104 Not Found: /accounts/register
WARNING 2025-06-03 12:52:30,136 basehttp 23068 12104 "GET /accounts/register HTTP/1.1" 404 10566
INFO 2025-06-03 12:52:41,412 basehttp 23068 12104 "GET /accounts/signup HTTP/1.1" 301 0
INFO 2025-06-03 12:52:41,678 basehttp 23068 20132 "GET /accounts/signup/ HTTP/1.1" 200 2510
WARNING 2025-06-03 12:52:56,105 log 23068 20132 Not Found: /accounts/register/
WARNING 2025-06-03 12:52:56,105 basehttp 23068 20132 "GET /accounts/register/ HTTP/1.1" 404 10569
INFO 2025-06-03 12:53:48,556 autoreload 23068 21712 D:\WORK PROJECTS\Autowash Build\autowash\autowash\urls_public.py changed, reloading.
INFO 2025-06-03 12:53:52,863 autoreload 5632 14860 Watching for file changes with StatReloader
ERROR 2025-06-03 12:53:56,178 log 5632 23636 Internal Server Error: /auth/register/
Traceback (most recent call last):
  File "D:\WORK PROJECTS\Autowash Build\autowash\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "D:\WORK PROJECTS\Autowash Build\autowash\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\WORK PROJECTS\Autowash Build\autowash\apps\accounts\views.py", line 90, in register_view
    return render(request, 'auth/register.html', {'form': form})
  File "D:\WORK PROJECTS\Autowash Build\autowash\venv\Lib\site-packages\django\shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "D:\WORK PROJECTS\Autowash Build\autowash\venv\Lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "D:\WORK PROJECTS\Autowash Build\autowash\venv\Lib\site-packages\django\template\loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: auth/register.html
ERROR 2025-06-03 12:53:56,183 basehttp 5632 23636 "GET /auth/register/ HTTP/1.1" 500 102730
ERROR 2025-06-03 13:02:24,557 log 5632 24144 Internal Server Error: /auth/register/
Traceback (most recent call last):
  File "D:\WORK PROJECTS\Autowash Build\autowash\venv\Lib\site-packages\django\template\backends\django.py", line 107, in render
    return self.template.render(context)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "D:\WORK PROJECTS\Autowash Build\autowash\venv\Lib\site-packages\django\template\base.py", line 171, in render
    return self._render(context)
           ~~~~~~~~~~~~^^^^^^^^^
  File "D:\WORK PROJECTS\Autowash Build\autowash\venv\Lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "D:\WORK PROJECTS\Autowash Build\autowash\venv\Lib\site-packages\django\template\base.py", line 1016, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "D:\WORK PROJECTS\Autowash Build\autowash\venv\Lib\site-packages\django\template\base.py", line 977, in render_annotated
    return self.render(context)
           ~~~~~~~~~~~^^^^^^^^^
  File "D:\WORK PROJECTS\Autowash Build\autowash\venv\Lib\site-packages\django\template\loader_tags.py", line 134, in render
    compiled_parent = self.get_parent(context)
  File "D:\WORK PROJECTS\Autowash Build\autowash\venv\Lib\site-packages\django\template\loader_tags.py", line 131, in get_parent
    return self.find_template(parent, context)
           ~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
  File "D:\WORK PROJECTS\Autowash Build\autowash\venv\Lib\site-packages\django\template\loader_tags.py", line 109, in find_template
    template, origin = context.template.engine.find_template(
                       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
        template_name,
        ^^^^^^^^^^^^^^
        skip=history,
        ^^^^^^^^^^^^^
    )
    ^
  File "D:\WORK PROJECTS\Autowash Build\autowash\venv\Lib\site-packages\django\template\engine.py", line 163, in find_template
    raise TemplateDoesNotExist(name, tried=tried)
django.template.exceptions.TemplateDoesNotExist: base.html

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\WORK PROJECTS\Autowash Build\autowash\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "D:\WORK PROJECTS\Autowash Build\autowash\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\WORK PROJECTS\Autowash Build\autowash\apps\accounts\views.py", line 90, in register_view
    return render(request, 'auth/register.html', {'form': form})
  File "D:\WORK PROJECTS\Autowash Build\autowash\venv\Lib\site-packages\django\shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "D:\WORK PROJECTS\Autowash Build\autowash\venv\Lib\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^
  File "D:\WORK PROJECTS\Autowash Build\autowash\venv\Lib\site-packages\django\template\backends\django.py", line 109, in render
    reraise(exc, self.backend)
    ~~~~~~~^^^^^^^^^^^^^^^^^^^
  File "D:\WORK PROJECTS\Autowash Build\autowash\venv\Lib\site-packages\django\template\backends\django.py", line 130, in reraise
    raise new from exc
django.template.exceptions.TemplateDoesNotExist: base.html
ERROR 2025-06-03 13:02:24,566 basehttp 5632 24144 "GET /auth/register/ HTTP/1.1" 500 152481
ERROR 2025-06-03 13:02:26,292 log 5632 24144 Internal Server Error: /auth/register/
Traceback (most recent call last):
  File "D:\WORK PROJECTS\Autowash Build\autowash\venv\Lib\site-packages\django\template\backends\django.py", line 107, in render
    return self.template.render(context)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "D:\WORK PROJECTS\Autowash Build\autowash\venv\Lib\site-packages\django\template\base.py", line 171, in render
    return self._render(context)
           ~~~~~~~~~~~~^^^^^^^^^
  File "D:\WORK PROJECTS\Autowash Build\autowash\venv\Lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "D:\WORK PROJECTS\Autowash Build\autowash\venv\Lib\site-packages\django\template\base.py", line 1016, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "D:\WORK PROJECTS\Autowash Build\autowash\venv\Lib\site-packages\django\template\base.py", line 977, in render_annotated
    return self.render(context)
           ~~~~~~~~~~~^^^^^^^^^
  File "D:\WORK PROJECTS\Autowash Build\autowash\venv\Lib\site-packages\django\template\loader_tags.py", line 134, in render
    compiled_parent = self.get_parent(context)
  File "D:\WORK PROJECTS\Autowash Build\autowash\venv\Lib\site-packages\django\template\loader_tags.py", line 131, in get_parent
    return self.find_template(parent, context)
           ~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
  File "D:\WORK PROJECTS\Autowash Build\autowash\venv\Lib\site-packages\django\template\loader_tags.py", line 109, in find_template
    template, origin = context.template.engine.find_template(
                       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
        template_name,
        ^^^^^^^^^^^^^^
        skip=history,
        ^^^^^^^^^^^^^
    )
    ^
  File "D:\WORK PROJECTS\Autowash Build\autowash\venv\Lib\site-packages\django\template\engine.py", line 163, in find_template
    raise TemplateDoesNotExist(name, tried=tried)
django.template.exceptions.TemplateDoesNotExist: base.html

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\WORK PROJECTS\Autowash Build\autowash\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "D:\WORK PROJECTS\Autowash Build\autowash\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\WORK PROJECTS\Autowash Build\autowash\apps\accounts\views.py", line 90, in register_view
    return render(request, 'auth/register.html', {'form': form})
  File "D:\WORK PROJECTS\Autowash Build\autowash\venv\Lib\site-packages\django\shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "D:\WORK PROJECTS\Autowash Build\autowash\venv\Lib\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^
  File "D:\WORK PROJECTS\Autowash Build\autowash\venv\Lib\site-packages\django\template\backends\django.py", line 109, in render
    reraise(exc, self.backend)
    ~~~~~~~^^^^^^^^^^^^^^^^^^^
  File "D:\WORK PROJECTS\Autowash Build\autowash\venv\Lib\site-packages\django\template\backends\django.py", line 130, in reraise
    raise new from exc
django.template.exceptions.TemplateDoesNotExist: base.html
ERROR 2025-06-03 13:02:26,297 basehttp 5632 24144 "GET /auth/register/ HTTP/1.1" 500 152481
ERROR 2025-06-03 13:03:45,575 log 5632 24144 Internal Server Error: /auth/register/
Traceback (most recent call last):
  File "D:\WORK PROJECTS\Autowash Build\autowash\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "D:\WORK PROJECTS\Autowash Build\autowash\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\WORK PROJECTS\Autowash Build\autowash\apps\accounts\views.py", line 90, in register_view
    return render(request, 'auth/register.html', {'form': form})
  File "D:\WORK PROJECTS\Autowash Build\autowash\venv\Lib\site-packages\django\shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "D:\WORK PROJECTS\Autowash Build\autowash\venv\Lib\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^
  File "D:\WORK PROJECTS\Autowash Build\autowash\venv\Lib\site-packages\django\template\backends\django.py", line 107, in render
    return self.template.render(context)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "D:\WORK PROJECTS\Autowash Build\autowash\venv\Lib\site-packages\django\template\base.py", line 171, in render
    return self._render(context)
           ~~~~~~~~~~~~^^^^^^^^^
  File "D:\WORK PROJECTS\Autowash Build\autowash\venv\Lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "D:\WORK PROJECTS\Autowash Build\autowash\venv\Lib\site-packages\django\template\base.py", line 1016, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "D:\WORK PROJECTS\Autowash Build\autowash\venv\Lib\site-packages\django\template\base.py", line 977, in render_annotated
    return self.render(context)
           ~~~~~~~~~~~^^^^^^^^^
  File "D:\WORK PROJECTS\Autowash Build\autowash\venv\Lib\site-packages\django\template\loader_tags.py", line 134, in render
    compiled_parent = self.get_parent(context)
  File "D:\WORK PROJECTS\Autowash Build\autowash\venv\Lib\site-packages\django\template\loader_tags.py", line 131, in get_parent
    return self.find_template(parent, context)
           ~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
  File "D:\WORK PROJECTS\Autowash Build\autowash\venv\Lib\site-packages\django\template\loader_tags.py", line 109, in find_template
    template, origin = context.template.engine.find_template(
                       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
        template_name,
        ^^^^^^^^^^^^^^
        skip=history,
        ^^^^^^^^^^^^^
    )
    ^
  File "D:\WORK PROJECTS\Autowash Build\autowash\venv\Lib\site-packages\django\template\engine.py", line 159, in find_template
    template = loader.get_template(name, skip=skip)
  File "D:\WORK PROJECTS\Autowash Build\autowash\venv\Lib\site-packages\django\template\loaders\cached.py", line 57, in get_template
    template = super().get_template(template_name, skip)
  File "D:\WORK PROJECTS\Autowash Build\autowash\venv\Lib\site-packages\django\template\loaders\base.py", line 28, in get_template
    return Template(
        contents,
    ...<2 lines>...
        self.engine,
    )
  File "D:\WORK PROJECTS\Autowash Build\autowash\venv\Lib\site-packages\django\template\base.py", line 154, in __init__
    self.nodelist = self.compile_nodelist()
                    ~~~~~~~~~~~~~~~~~~~~~^^
  File "D:\WORK PROJECTS\Autowash Build\autowash\venv\Lib\site-packages\django\template\base.py", line 196, in compile_nodelist
    nodelist = parser.parse()
  File "D:\WORK PROJECTS\Autowash Build\autowash\venv\Lib\site-packages\django\template\base.py", line 518, in parse
    raise self.error(token, e)
  File "D:\WORK PROJECTS\Autowash Build\autowash\venv\Lib\site-packages\django\template\base.py", line 516, in parse
    compiled_result = compile_func(self, token)
  File "D:\WORK PROJECTS\Autowash Build\autowash\venv\Lib\site-packages\django\template\defaulttags.py", line 976, in do_if
    nodelist = parser.parse(("endif",))
  File "D:\WORK PROJECTS\Autowash Build\autowash\venv\Lib\site-packages\django\template\base.py", line 518, in parse
    raise self.error(token, e)
  File "D:\WORK PROJECTS\Autowash Build\autowash\venv\Lib\site-packages\django\template\base.py", line 516, in parse
    compiled_result = compile_func(self, token)
  File "D:\WORK PROJECTS\Autowash Build\autowash\venv\Lib\site-packages\django\template\loader_tags.py", line 228, in do_block
    raise TemplateSyntaxError(
        "'%s' tag with name '%s' appears more than once" % (bits[0], block_name)
    )
django.template.exceptions.TemplateSyntaxError: 'block' tag with name 'content' appears more than once
ERROR 2025-06-03 13:03:45,585 basehttp 5632 24144 "GET /auth/register/ HTTP/1.1" 500 222952
INFO 2025-06-03 13:04:53,629 basehttp 5632 24144 "GET /auth/register/ HTTP/1.1" 200 12570
WARNING 2025-06-03 13:04:53,653 basehttp 5632 24144 "GET /static/css/custom.css HTTP/1.1" 404 1969
WARNING 2025-06-03 13:04:53,659 basehttp 5632 21036 "GET /static/css/dashboard.css HTTP/1.1" 404 1978
WARNING 2025-06-03 13:04:54,250 basehttp 5632 23236 "GET /static/img/favicon.ico HTTP/1.1" 404 1972
INFO 2025-06-03 13:04:59,910 basehttp 5632 3528 "GET /auth/login/ HTTP/1.1" 200 12567
WARNING 2025-06-03 13:04:59,957 basehttp 5632 3528 "GET /static/css/custom.css HTTP/1.1" 404 1969
WARNING 2025-06-03 13:04:59,957 basehttp 5632 2604 "GET /static/css/dashboard.css HTTP/1.1" 404 1978
INFO 2025-06-03 13:05:02,164 basehttp 5632 5748 "GET /auth/register/ HTTP/1.1" 200 12570
WARNING 2025-06-03 13:05:02,201 basehttp 5632 5748 "GET /static/css/custom.css HTTP/1.1" 404 1969
WARNING 2025-06-03 13:05:02,207 basehttp 5632 23752 "GET /static/css/dashboard.css HTTP/1.1" 404 1978
ERROR 2025-06-03 13:05:10,720 log 5632 19260 Internal Server Error: /
Traceback (most recent call last):
  File "D:\WORK PROJECTS\Autowash Build\autowash\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "D:\WORK PROJECTS\Autowash Build\autowash\venv\Lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
  File "D:\WORK PROJECTS\Autowash Build\autowash\venv\Lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "D:\WORK PROJECTS\Autowash Build\autowash\venv\Lib\site-packages\django\template\response.py", line 90, in rendered_content
    template = self.resolve_template(self.template_name)
  File "D:\WORK PROJECTS\Autowash Build\autowash\venv\Lib\site-packages\django\template\response.py", line 72, in resolve_template
    return select_template(template, using=self.using)
  File "D:\WORK PROJECTS\Autowash Build\autowash\venv\Lib\site-packages\django\template\loader.py", line 47, in select_template
    raise TemplateDoesNotExist(", ".join(template_name_list), chain=chain)
django.template.exceptions.TemplateDoesNotExist: public/landing.html
ERROR 2025-06-03 13:05:10,723 basehttp 5632 19260 "GET / HTTP/1.1" 500 101604
ERROR 2025-06-03 13:05:13,536 log 5632 19260 Internal Server Error: /features/
Traceback (most recent call last):
  File "D:\WORK PROJECTS\Autowash Build\autowash\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "D:\WORK PROJECTS\Autowash Build\autowash\venv\Lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
  File "D:\WORK PROJECTS\Autowash Build\autowash\venv\Lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "D:\WORK PROJECTS\Autowash Build\autowash\venv\Lib\site-packages\django\template\response.py", line 90, in rendered_content
    template = self.resolve_template(self.template_name)
  File "D:\WORK PROJECTS\Autowash Build\autowash\venv\Lib\site-packages\django\template\response.py", line 72, in resolve_template
    return select_template(template, using=self.using)
  File "D:\WORK PROJECTS\Autowash Build\autowash\venv\Lib\site-packages\django\template\loader.py", line 47, in select_template
    raise TemplateDoesNotExist(", ".join(template_name_list), chain=chain)
django.template.exceptions.TemplateDoesNotExist: public/features.html
ERROR 2025-06-03 13:05:13,539 basehttp 5632 19260 "GET /features/ HTTP/1.1" 500 101715
ERROR 2025-06-03 13:05:16,802 log 5632 19260 Internal Server Error: /pricing/
Traceback (most recent call last):
  File "D:\WORK PROJECTS\Autowash Build\autowash\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "D:\WORK PROJECTS\Autowash Build\autowash\venv\Lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
  File "D:\WORK PROJECTS\Autowash Build\autowash\venv\Lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "D:\WORK PROJECTS\Autowash Build\autowash\venv\Lib\site-packages\django\template\response.py", line 90, in rendered_content
    template = self.resolve_template(self.template_name)
  File "D:\WORK PROJECTS\Autowash Build\autowash\venv\Lib\site-packages\django\template\response.py", line 72, in resolve_template
    return select_template(template, using=self.using)
  File "D:\WORK PROJECTS\Autowash Build\autowash\venv\Lib\site-packages\django\template\loader.py", line 47, in select_template
    raise TemplateDoesNotExist(", ".join(template_name_list), chain=chain)
django.template.exceptions.TemplateDoesNotExist: public/pricing.html
ERROR 2025-06-03 13:05:16,805 basehttp 5632 19260 "GET /pricing/ HTTP/1.1" 500 101676
ERROR 2025-06-03 13:05:20,642 log 5632 19260 Internal Server Error: /contact/
Traceback (most recent call last):
  File "D:\WORK PROJECTS\Autowash Build\autowash\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "D:\WORK PROJECTS\Autowash Build\autowash\venv\Lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
  File "D:\WORK PROJECTS\Autowash Build\autowash\venv\Lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "D:\WORK PROJECTS\Autowash Build\autowash\venv\Lib\site-packages\django\template\response.py", line 90, in rendered_content
    template = self.resolve_template(self.template_name)
  File "D:\WORK PROJECTS\Autowash Build\autowash\venv\Lib\site-packages\django\template\response.py", line 72, in resolve_template
    return select_template(template, using=self.using)
  File "D:\WORK PROJECTS\Autowash Build\autowash\venv\Lib\site-packages\django\template\loader.py", line 47, in select_template
    raise TemplateDoesNotExist(", ".join(template_name_list), chain=chain)
django.template.exceptions.TemplateDoesNotExist: public/contact.html
ERROR 2025-06-03 13:05:20,644 basehttp 5632 19260 "GET /contact/ HTTP/1.1" 500 101676
INFO 2025-06-03 13:05:24,524 basehttp 5632 19260 "GET /auth/register/ HTTP/1.1" 200 12570
WARNING 2025-06-03 13:05:24,544 basehttp 5632 19260 "GET /static/css/custom.css HTTP/1.1" 404 1969
WARNING 2025-06-03 13:05:24,545 basehttp 5632 7856 "GET /static/css/dashboard.css HTTP/1.1" 404 1978
ERROR 2025-06-03 13:05:36,028 log 5632 5996 Internal Server Error: /
Traceback (most recent call last):
  File "D:\WORK PROJECTS\Autowash Build\autowash\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "D:\WORK PROJECTS\Autowash Build\autowash\venv\Lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
  File "D:\WORK PROJECTS\Autowash Build\autowash\venv\Lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "D:\WORK PROJECTS\Autowash Build\autowash\venv\Lib\site-packages\django\template\response.py", line 90, in rendered_content
    template = self.resolve_template(self.template_name)
  File "D:\WORK PROJECTS\Autowash Build\autowash\venv\Lib\site-packages\django\template\response.py", line 72, in resolve_template
    return select_template(template, using=self.using)
  File "D:\WORK PROJECTS\Autowash Build\autowash\venv\Lib\site-packages\django\template\loader.py", line 47, in select_template
    raise TemplateDoesNotExist(", ".join(template_name_list), chain=chain)
django.template.exceptions.TemplateDoesNotExist: public/landing.html
ERROR 2025-06-03 13:05:36,030 basehttp 5632 5996 "GET / HTTP/1.1" 500 101604
INFO 2025-06-03 13:05:40,444 basehttp 5632 5996 "GET /auth/login/ HTTP/1.1" 200 12567
WARNING 2025-06-03 13:05:40,481 basehttp 5632 5996 "GET /static/css/custom.css HTTP/1.1" 404 1969
WARNING 2025-06-03 13:05:40,491 basehttp 5632 13248 "GET /static/css/dashboard.css HTTP/1.1" 404 1978
INFO 2025-06-03 13:05:43,899 basehttp 5632 17716 "GET /auth/register/ HTTP/1.1" 200 12570
WARNING 2025-06-03 13:05:43,932 basehttp 5632 17716 "GET /static/css/custom.css HTTP/1.1" 404 1969
WARNING 2025-06-03 13:05:43,932 basehttp 5632 13820 "GET /static/css/dashboard.css HTTP/1.1" 404 1978
INFO 2025-06-03 13:05:46,651 basehttp 5632 12260 "GET /auth/register/ HTTP/1.1" 200 12570
WARNING 2025-06-03 13:05:46,677 basehttp 5632 12260 "GET /static/css/custom.css HTTP/1.1" 404 1969
WARNING 2025-06-03 13:05:46,677 basehttp 5632 10164 "GET /static/css/dashboard.css HTTP/1.1" 404 1978
INFO 2025-06-03 13:06:01,515 basehttp 5632 17032 "GET /auth/register/ HTTP/1.1" 200 12570
WARNING 2025-06-03 13:06:01,537 basehttp 5632 17032 "GET /static/css/custom.css HTTP/1.1" 404 1969
WARNING 2025-06-03 13:06:01,542 basehttp 5632 12964 "GET /static/css/dashboard.css HTTP/1.1" 404 1978
ERROR 2025-06-03 13:06:04,035 log 5632 19180 Internal Server Error: /
Traceback (most recent call last):
  File "D:\WORK PROJECTS\Autowash Build\autowash\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "D:\WORK PROJECTS\Autowash Build\autowash\venv\Lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
  File "D:\WORK PROJECTS\Autowash Build\autowash\venv\Lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "D:\WORK PROJECTS\Autowash Build\autowash\venv\Lib\site-packages\django\template\response.py", line 90, in rendered_content
    template = self.resolve_template(self.template_name)
  File "D:\WORK PROJECTS\Autowash Build\autowash\venv\Lib\site-packages\django\template\response.py", line 72, in resolve_template
    return select_template(template, using=self.using)
  File "D:\WORK PROJECTS\Autowash Build\autowash\venv\Lib\site-packages\django\template\loader.py", line 47, in select_template
    raise TemplateDoesNotExist(", ".join(template_name_list), chain=chain)
django.template.exceptions.TemplateDoesNotExist: public/landing.html
ERROR 2025-06-03 13:06:04,038 basehttp 5632 19180 "GET / HTTP/1.1" 500 101604
ERROR 2025-06-03 13:06:34,175 log 5632 19180 Internal Server Error: /auth/login/
Traceback (most recent call last):
  File "D:\WORK PROJECTS\Autowash Build\autowash\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "D:\WORK PROJECTS\Autowash Build\autowash\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\WORK PROJECTS\Autowash Build\autowash\apps\accounts\views.py", line 112, in login_view
    return render(request, 'auth/login.html')
  File "D:\WORK PROJECTS\Autowash Build\autowash\venv\Lib\site-packages\django\shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "D:\WORK PROJECTS\Autowash Build\autowash\venv\Lib\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^
  File "D:\WORK PROJECTS\Autowash Build\autowash\venv\Lib\site-packages\django\template\backends\django.py", line 107, in render
    return self.template.render(context)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "D:\WORK PROJECTS\Autowash Build\autowash\venv\Lib\site-packages\django\template\base.py", line 171, in render
    return self._render(context)
           ~~~~~~~~~~~~^^^^^^^^^
  File "D:\WORK PROJECTS\Autowash Build\autowash\venv\Lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "D:\WORK PROJECTS\Autowash Build\autowash\venv\Lib\site-packages\django\template\base.py", line 1016, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "D:\WORK PROJECTS\Autowash Build\autowash\venv\Lib\site-packages\django\template\base.py", line 977, in render_annotated
    return self.render(context)
           ~~~~~~~~~~~^^^^^^^^^
  File "D:\WORK PROJECTS\Autowash Build\autowash\venv\Lib\site-packages\django\template\loader_tags.py", line 134, in render
    compiled_parent = self.get_parent(context)
  File "D:\WORK PROJECTS\Autowash Build\autowash\venv\Lib\site-packages\django\template\loader_tags.py", line 131, in get_parent
    return self.find_template(parent, context)
           ~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
  File "D:\WORK PROJECTS\Autowash Build\autowash\venv\Lib\site-packages\django\template\loader_tags.py", line 109, in find_template
    template, origin = context.template.engine.find_template(
                       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
        template_name,
        ^^^^^^^^^^^^^^
        skip=history,
        ^^^^^^^^^^^^^
    )
    ^
  File "D:\WORK PROJECTS\Autowash Build\autowash\venv\Lib\site-packages\django\template\engine.py", line 159, in find_template
    template = loader.get_template(name, skip=skip)
  File "D:\WORK PROJECTS\Autowash Build\autowash\venv\Lib\site-packages\django\template\loaders\cached.py", line 57, in get_template
    template = super().get_template(template_name, skip)
  File "D:\WORK PROJECTS\Autowash Build\autowash\venv\Lib\site-packages\django\template\loaders\base.py", line 28, in get_template
    return Template(
        contents,
    ...<2 lines>...
        self.engine,
    )
  File "D:\WORK PROJECTS\Autowash Build\autowash\venv\Lib\site-packages\django\template\base.py", line 154, in __init__
    self.nodelist = self.compile_nodelist()
                    ~~~~~~~~~~~~~~~~~~~~~^^
  File "D:\WORK PROJECTS\Autowash Build\autowash\venv\Lib\site-packages\django\template\base.py", line 196, in compile_nodelist
    nodelist = parser.parse()
  File "D:\WORK PROJECTS\Autowash Build\autowash\venv\Lib\site-packages\django\template\base.py", line 518, in parse
    raise self.error(token, e)
  File "D:\WORK PROJECTS\Autowash Build\autowash\venv\Lib\site-packages\django\template\base.py", line 516, in parse
    compiled_result = compile_func(self, token)
  File "D:\WORK PROJECTS\Autowash Build\autowash\venv\Lib\site-packages\django\template\defaulttags.py", line 976, in do_if
    nodelist = parser.parse(("endif",))
  File "D:\WORK PROJECTS\Autowash Build\autowash\venv\Lib\site-packages\django\template\base.py", line 518, in parse
    raise self.error(token, e)
  File "D:\WORK PROJECTS\Autowash Build\autowash\venv\Lib\site-packages\django\template\base.py", line 516, in parse
    compiled_result = compile_func(self, token)
  File "D:\WORK PROJECTS\Autowash Build\autowash\venv\Lib\site-packages\django\template\loader_tags.py", line 228, in do_block
    raise TemplateSyntaxError(
        "'%s' tag with name '%s' appears more than once" % (bits[0], block_name)
    )
django.template.exceptions.TemplateSyntaxError: 'block' tag with name 'content' appears more than once
ERROR 2025-06-03 13:06:34,181 basehttp 5632 19180 "GET /auth/login/ HTTP/1.1" 500 221094
WARNING 2025-06-03 13:08:40,282 log 5632 19180 Not Found: /admin
WARNING 2025-06-03 13:08:40,283 basehttp 5632 19180 "GET /admin HTTP/1.1" 404 3664
INFO 2025-06-03 13:08:49,594 basehttp 5632 19180 "GET /system-admin HTTP/1.1" 301 0
INFO 2025-06-03 13:08:49,695 basehttp 5632 14112 "GET /system-admin/ HTTP/1.1" 302 0
INFO 2025-06-03 13:08:49,857 basehttp 5632 14112 "GET /system-admin/login/?next=/system-admin/ HTTP/1.1" 200 4202
INFO 2025-06-03 13:08:49,876 basehttp 5632 14112 "GET /static/admin/css/base.css HTTP/1.1" 200 22120
INFO 2025-06-03 13:08:49,885 basehttp 5632 14112 "GET /static/admin/css/dark_mode.css HTTP/1.1" 200 2808
INFO 2025-06-03 13:08:49,887 basehttp 5632 3968 "GET /static/admin/css/login.css HTTP/1.1" 200 951
INFO 2025-06-03 13:08:49,888 basehttp 5632 21684 "GET /static/admin/css/nav_sidebar.css HTTP/1.1" 200 2810
INFO 2025-06-03 13:08:49,889 basehttp 5632 1220 "GET /static/admin/css/responsive.css HTTP/1.1" 200 16565
INFO 2025-06-03 13:08:49,912 basehttp 5632 13892 "GET /static/admin/js/theme.js HTTP/1.1" 200 1653
INFO 2025-06-03 13:08:49,921 basehttp 5632 1220 "GET /static/admin/js/nav_sidebar.js HTTP/1.1" 200 3063
INFO 2025-06-03 13:08:58,834 basehttp 5632 1220 "POST /system-admin/login/?next=/system-admin/ HTTP/1.1" 302 0
INFO 2025-06-03 13:08:59,020 basehttp 5632 1220 "GET /system-admin/ HTTP/1.1" 200 26412
INFO 2025-06-03 13:08:59,060 basehttp 5632 1220 "GET /static/admin/css/dashboard.css HTTP/1.1" 200 441
INFO 2025-06-03 13:08:59,078 basehttp 5632 13892 "GET /static/admin/img/icon-addlink.svg HTTP/1.1" 200 331
INFO 2025-06-03 13:08:59,078 basehttp 5632 21684 "GET /static/admin/img/icon-changelink.svg HTTP/1.1" 200 380
INFO 2025-06-03 13:09:09,079 basehttp 5632 13892 "GET /system-admin/subscriptions/subscriptionplan/ HTTP/1.1" 200 18855
INFO 2025-06-03 13:09:09,133 basehttp 5632 13892 "GET /static/admin/css/changelists.css HTTP/1.1" 200 6878
INFO 2025-06-03 13:09:09,165 basehttp 5632 3968 "GET /static/admin/js/jquery.init.js HTTP/1.1" 200 347
INFO 2025-06-03 13:09:09,185 basehttp 5632 14112 "GET /static/admin/js/core.js HTTP/1.1" 200 6208
INFO 2025-06-03 13:09:09,191 basehttp 5632 13892 "GET /static/admin/js/actions.js HTTP/1.1" 200 8076
INFO 2025-06-03 13:09:09,199 basehttp 5632 17092 "GET /static/admin/js/admin/RelatedObjectLookups.js HTTP/1.1" 200 9777
INFO 2025-06-03 13:09:09,235 basehttp 5632 14112 "GET /static/admin/js/prepopulate.js HTTP/1.1" 200 1531
INFO 2025-06-03 13:09:09,236 basehttp 5632 17092 "GET /static/admin/img/search.svg HTTP/1.1" 200 458
INFO 2025-06-03 13:09:09,243 basehttp 5632 3968 "GET /static/admin/js/urlify.js HTTP/1.1" 200 7887
INFO 2025-06-03 13:09:09,301 basehttp 5632 1220 "GET /static/admin/js/vendor/jquery/jquery.js HTTP/1.1" 200 285314
INFO 2025-06-03 13:09:09,383 basehttp 5632 21684 "GET /system-admin/jsi18n/ HTTP/1.1" 200 3342
INFO 2025-06-03 13:09:09,419 basehttp 5632 21684 "GET /static/admin/js/filters.js HTTP/1.1" 200 978
INFO 2025-06-03 13:09:09,448 basehttp 5632 13892 "GET /static/admin/js/vendor/xregexp/xregexp.js HTTP/1.1" 200 325171
INFO 2025-06-03 13:09:09,506 basehttp 5632 21684 "GET /static/admin/img/icon-viewlink.svg HTTP/1.1" 200 581
INFO 2025-06-03 13:09:09,510 basehttp 5632 13892 "GET /static/admin/img/tooltag-add.svg HTTP/1.1" 200 331
INFO 2025-06-03 13:09:22,675 basehttp 5632 13892 "GET /system-admin/auth/user/ HTTP/1.1" 200 20968
INFO 2025-06-03 13:09:22,715 basehttp 5632 13892 "GET /static/admin/img/icon-yes.svg HTTP/1.1" 200 436
INFO 2025-06-03 13:09:22,798 basehttp 5632 21684 "GET /system-admin/jsi18n/ HTTP/1.1" 200 3342
INFO 2025-06-03 13:09:22,834 basehttp 5632 21684 "GET /static/admin/img/sorting-icons.svg HTTP/1.1" 200 1097
INFO 2025-06-03 13:09:25,116 basehttp 5632 21684 "GET /system-admin/auth/user/1/change/ HTTP/1.1" 200 68421
INFO 2025-06-03 13:09:25,154 basehttp 5632 21684 "GET /static/admin/css/forms.css HTTP/1.1" 200 8525
INFO 2025-06-03 13:09:25,203 basehttp 5632 13892 "GET /static/admin/js/calendar.js HTTP/1.1" 200 9141
INFO 2025-06-03 13:09:25,209 basehttp 5632 1220 "GET /static/admin/js/admin/DateTimeShortcuts.js HTTP/1.1" 200 19319
INFO 2025-06-03 13:09:25,211 basehttp 5632 13892 "GET /static/admin/css/widgets.css HTTP/1.1" 200 11991
INFO 2025-06-03 13:09:25,212 basehttp 5632 17092 "GET /static/admin/js/SelectFilter2.js HTTP/1.1" 200 15709
INFO 2025-06-03 13:09:25,213 basehttp 5632 3968 "GET /static/admin/js/SelectBox.js HTTP/1.1" 200 4530
INFO 2025-06-03 13:09:25,214 basehttp 5632 21684 "GET /static/admin/js/prepopulate_init.js HTTP/1.1" 200 586
INFO 2025-06-03 13:09:25,255 basehttp 5632 13892 "GET /static/admin/js/change_form.js HTTP/1.1" 200 606
INFO 2025-06-03 13:09:25,323 basehttp 5632 14112 "GET /system-admin/jsi18n/ HTTP/1.1" 200 3342
INFO 2025-06-03 13:09:25,437 basehttp 5632 3968 "GET /static/admin/img/icon-clock.svg HTTP/1.1" 200 677
INFO 2025-06-03 13:09:25,439 basehttp 5632 14112 "GET /static/admin/img/selector-icons.svg HTTP/1.1" 200 3291
INFO 2025-06-03 13:09:25,439 basehttp 5632 13892 "GET /static/admin/img/icon-calendar.svg HTTP/1.1" 200 1086
INFO 2025-06-03 13:09:36,271 basehttp 5632 13892 "GET /system-admin/account/emailaddress/ HTTP/1.1" 200 18379
INFO 2025-06-03 13:09:36,399 basehttp 5632 13892 "GET /system-admin/jsi18n/ HTTP/1.1" 200 3342
INFO 2025-06-03 13:09:39,330 basehttp 5632 13892 "GET /system-admin/account/emailaddress/add/ HTTP/1.1" 200 19635
INFO 2025-06-03 13:09:39,457 basehttp 5632 13892 "GET /system-admin/jsi18n/ HTTP/1.1" 200 3342
INFO 2025-06-03 13:09:42,949 basehttp 5632 13892 "GET /system-admin/account/emailaddress/ HTTP/1.1" 200 18379
ERROR 2025-06-03 13:11:41,900 log 5632 13892 Internal Server Error: /
Traceback (most recent call last):
  File "D:\WORK PROJECTS\Autowash Build\autowash\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "D:\WORK PROJECTS\Autowash Build\autowash\venv\Lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
  File "D:\WORK PROJECTS\Autowash Build\autowash\venv\Lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "D:\WORK PROJECTS\Autowash Build\autowash\venv\Lib\site-packages\django\template\response.py", line 90, in rendered_content
    template = self.resolve_template(self.template_name)
  File "D:\WORK PROJECTS\Autowash Build\autowash\venv\Lib\site-packages\django\template\response.py", line 72, in resolve_template
    return select_template(template, using=self.using)
  File "D:\WORK PROJECTS\Autowash Build\autowash\venv\Lib\site-packages\django\template\loader.py", line 47, in select_template
    raise TemplateDoesNotExist(", ".join(template_name_list), chain=chain)
django.template.exceptions.TemplateDoesNotExist: public/landing.html
ERROR 2025-06-03 13:11:41,902 basehttp 5632 13892 "GET / HTTP/1.1" 500 101767
INFO 2025-06-03 13:11:59,216 basehttp 5632 13892 "GET /auth/profile/ HTTP/1.1" 200 12561
WARNING 2025-06-03 13:11:59,255 basehttp 5632 14112 "GET /static/css/dashboard.css HTTP/1.1" 404 1978
WARNING 2025-06-03 13:11:59,256 basehttp 5632 13892 "GET /static/css/custom.css HTTP/1.1" 404 1969
ERROR 2025-06-03 13:12:04,200 log 5632 3968 Internal Server Error: /auth/dashboard/
Traceback (most recent call last):
  File "D:\WORK PROJECTS\Autowash Build\autowash\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "D:\WORK PROJECTS\Autowash Build\autowash\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\WORK PROJECTS\Autowash Build\autowash\venv\Lib\site-packages\django\contrib\auth\decorators.py", line 59, in _view_wrapper
    return view_func(request, *args, **kwargs)
  File "D:\WORK PROJECTS\Autowash Build\autowash\apps\accounts\views.py", line 289, in dashboard_redirect
    return redirect('subscriptions:plans')
  File "D:\WORK PROJECTS\Autowash Build\autowash\venv\Lib\site-packages\django\shortcuts.py", line 51, in redirect
    resolve_url(to, *args, **kwargs),
    ~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^
  File "D:\WORK PROJECTS\Autowash Build\autowash\venv\Lib\site-packages\django\shortcuts.py", line 184, in resolve_url
    return reverse(to, args=args, kwargs=kwargs)
  File "D:\WORK PROJECTS\Autowash Build\autowash\venv\Lib\site-packages\django\urls\base.py", line 98, in reverse
    resolved_url = resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
  File "D:\WORK PROJECTS\Autowash Build\autowash\venv\Lib\site-packages\django\urls\resolvers.py", line 831, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'plans' not found. 'plans' is not a valid view function or pattern name.
ERROR 2025-06-03 13:12:04,205 basehttp 5632 3968 "GET /auth/dashboard/ HTTP/1.1" 500 109445
INFO 2025-06-03 13:16:51,440 autoreload 5632 14860 D:\WORK PROJECTS\Autowash Build\autowash\apps\subscriptions\urls.py changed, reloading.
INFO 2025-06-03 13:16:55,821 autoreload 20140 13720 Watching for file changes with StatReloader
ERROR 2025-06-03 13:17:42,299 log 20140 3356 Internal Server Error: /auth/dashboard/
Traceback (most recent call last):
  File "D:\WORK PROJECTS\Autowash Build\autowash\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "D:\WORK PROJECTS\Autowash Build\autowash\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\WORK PROJECTS\Autowash Build\autowash\venv\Lib\site-packages\django\contrib\auth\decorators.py", line 59, in _view_wrapper
    return view_func(request, *args, **kwargs)
  File "D:\WORK PROJECTS\Autowash Build\autowash\apps\accounts\views.py", line 289, in dashboard_redirect
    return redirect('subscriptions:plans')
  File "D:\WORK PROJECTS\Autowash Build\autowash\venv\Lib\site-packages\django\shortcuts.py", line 51, in redirect
    resolve_url(to, *args, **kwargs),
    ~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^
  File "D:\WORK PROJECTS\Autowash Build\autowash\venv\Lib\site-packages\django\shortcuts.py", line 184, in resolve_url
    return reverse(to, args=args, kwargs=kwargs)
  File "D:\WORK PROJECTS\Autowash Build\autowash\venv\Lib\site-packages\django\urls\base.py", line 98, in reverse
    resolved_url = resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
  File "D:\WORK PROJECTS\Autowash Build\autowash\venv\Lib\site-packages\django\urls\resolvers.py", line 831, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'plans' not found. 'plans' is not a valid view function or pattern name.
ERROR 2025-06-03 13:17:42,307 basehttp 20140 3356 "GET /auth/dashboard/ HTTP/1.1" 500 109563
INFO 2025-06-03 13:18:02,167 autoreload 20140 13720 D:\WORK PROJECTS\Autowash Build\autowash\apps\subscriptions\urls.py changed, reloading.
INFO 2025-06-03 13:18:06,740 autoreload 14544 15292 Watching for file changes with StatReloader
INFO 2025-06-03 13:18:08,020 basehttp 14544 11464 "GET /auth/dashboard/ HTTP/1.1" 302 0
ERROR 2025-06-03 13:18:08,299 log 14544 11464 Internal Server Error: /subscriptions/
Traceback (most recent call last):
  File "D:\WORK PROJECTS\Autowash Build\autowash\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "D:\WORK PROJECTS\Autowash Build\autowash\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\WORK PROJECTS\Autowash Build\autowash\apps\subscriptions\views.py", line 52, in pricing_view
    return render(request, 'subscriptions/pricing.html', context)
  File "D:\WORK PROJECTS\Autowash Build\autowash\venv\Lib\site-packages\django\shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "D:\WORK PROJECTS\Autowash Build\autowash\venv\Lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "D:\WORK PROJECTS\Autowash Build\autowash\venv\Lib\site-packages\django\template\loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: subscriptions/pricing.html
ERROR 2025-06-03 13:18:08,308 basehttp 14544 11464 "GET /subscriptions/ HTTP/1.1" 500 103821
INFO 2025-06-03 13:18:31,222 basehttp 14544 11464 "GET /auth/profile/ HTTP/1.1" 200 13527
INFO 2025-06-03 13:18:37,534 basehttp 14544 11464 "GET /auth/logout/ HTTP/1.1" 302 0
ERROR 2025-06-03 13:18:37,642 log 14544 11464 Internal Server Error: /
Traceback (most recent call last):
  File "D:\WORK PROJECTS\Autowash Build\autowash\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "D:\WORK PROJECTS\Autowash Build\autowash\venv\Lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
  File "D:\WORK PROJECTS\Autowash Build\autowash\venv\Lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "D:\WORK PROJECTS\Autowash Build\autowash\venv\Lib\site-packages\django\template\response.py", line 90, in rendered_content
    template = self.resolve_template(self.template_name)
  File "D:\WORK PROJECTS\Autowash Build\autowash\venv\Lib\site-packages\django\template\response.py", line 72, in resolve_template
    return select_template(template, using=self.using)
  File "D:\WORK PROJECTS\Autowash Build\autowash\venv\Lib\site-packages\django\template\loader.py", line 47, in select_template
    raise TemplateDoesNotExist(", ".join(template_name_list), chain=chain)
django.template.exceptions.TemplateDoesNotExist: public/landing.html
ERROR 2025-06-03 13:18:37,644 basehttp 14544 11464 "GET / HTTP/1.1" 500 101874
INFO 2025-06-03 13:18:41,751 basehttp 14544 11464 "GET /auth/profile/ HTTP/1.1" 302 0
INFO 2025-06-03 13:18:41,929 basehttp 14544 11464 "GET /auth/login/?next=/auth/profile/ HTTP/1.1" 200 12938
WARNING 2025-06-03 13:18:41,956 basehttp 14544 11464 "GET /static/css/custom.css HTTP/1.1" 404 1969
WARNING 2025-06-03 13:18:41,957 basehttp 14544 14184 "GET /static/css/dashboard.css HTTP/1.1" 404 1978
INFO 2025-06-03 13:18:44,519 basehttp 14544 23240 "GET /auth/register/ HTTP/1.1" 200 12570
WARNING 2025-06-03 13:18:44,554 basehttp 14544 23240 "GET /static/css/custom.css HTTP/1.1" 404 1969
WARNING 2025-06-03 13:18:44,559 basehttp 14544 21208 "GET /static/css/dashboard.css HTTP/1.1" 404 1978
INFO 2025-06-03 13:19:06,108 basehttp 14544 18064 "GET /auth/login/ HTTP/1.1" 200 12567
WARNING 2025-06-03 13:19:06,151 basehttp 14544 17292 "GET /static/css/dashboard.css HTTP/1.1" 404 1978
WARNING 2025-06-03 13:19:06,151 basehttp 14544 18064 "GET /static/css/custom.css HTTP/1.1" 404 1969
ERROR 2025-06-03 13:19:11,523 log 14544 5260 Internal Server Error: /
Traceback (most recent call last):
  File "D:\WORK PROJECTS\Autowash Build\autowash\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "D:\WORK PROJECTS\Autowash Build\autowash\venv\Lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
  File "D:\WORK PROJECTS\Autowash Build\autowash\venv\Lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "D:\WORK PROJECTS\Autowash Build\autowash\venv\Lib\site-packages\django\template\response.py", line 90, in rendered_content
    template = self.resolve_template(self.template_name)
  File "D:\WORK PROJECTS\Autowash Build\autowash\venv\Lib\site-packages\django\template\response.py", line 72, in resolve_template
    return select_template(template, using=self.using)
  File "D:\WORK PROJECTS\Autowash Build\autowash\venv\Lib\site-packages\django\template\loader.py", line 47, in select_template
    raise TemplateDoesNotExist(", ".join(template_name_list), chain=chain)
django.template.exceptions.TemplateDoesNotExist: public/landing.html
ERROR 2025-06-03 13:19:11,525 basehttp 14544 5260 "GET / HTTP/1.1" 500 101601
INFO 2025-06-03 13:20:18,931 basehttp 14544 5260 "GET /auth/register/ HTTP/1.1" 200 12570
WARNING 2025-06-03 13:20:18,962 basehttp 14544 5260 "GET /static/css/custom.css HTTP/1.1" 404 1969
WARNING 2025-06-03 13:20:18,972 basehttp 14544 23020 "GET /static/css/dashboard.css HTTP/1.1" 404 1978
ERROR 2025-06-03 13:20:20,829 log 14544 4372 Internal Server Error: /pricing/
Traceback (most recent call last):
  File "D:\WORK PROJECTS\Autowash Build\autowash\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "D:\WORK PROJECTS\Autowash Build\autowash\venv\Lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
  File "D:\WORK PROJECTS\Autowash Build\autowash\venv\Lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "D:\WORK PROJECTS\Autowash Build\autowash\venv\Lib\site-packages\django\template\response.py", line 90, in rendered_content
    template = self.resolve_template(self.template_name)
  File "D:\WORK PROJECTS\Autowash Build\autowash\venv\Lib\site-packages\django\template\response.py", line 72, in resolve_template
    return select_template(template, using=self.using)
  File "D:\WORK PROJECTS\Autowash Build\autowash\venv\Lib\site-packages\django\template\loader.py", line 47, in select_template
    raise TemplateDoesNotExist(", ".join(template_name_list), chain=chain)
django.template.exceptions.TemplateDoesNotExist: public/pricing.html
ERROR 2025-06-03 13:20:20,831 basehttp 14544 4372 "GET /pricing/ HTTP/1.1" 500 101676
ERROR 2025-06-03 13:20:25,741 log 14544 4372 Internal Server Error: /
Traceback (most recent call last):
  File "D:\WORK PROJECTS\Autowash Build\autowash\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "D:\WORK PROJECTS\Autowash Build\autowash\venv\Lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
  File "D:\WORK PROJECTS\Autowash Build\autowash\venv\Lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "D:\WORK PROJECTS\Autowash Build\autowash\venv\Lib\site-packages\django\template\response.py", line 90, in rendered_content
    template = self.resolve_template(self.template_name)
  File "D:\WORK PROJECTS\Autowash Build\autowash\venv\Lib\site-packages\django\template\response.py", line 72, in resolve_template
    return select_template(template, using=self.using)
  File "D:\WORK PROJECTS\Autowash Build\autowash\venv\Lib\site-packages\django\template\loader.py", line 47, in select_template
    raise TemplateDoesNotExist(", ".join(template_name_list), chain=chain)
django.template.exceptions.TemplateDoesNotExist: public/landing.html
ERROR 2025-06-03 13:20:25,743 basehttp 14544 4372 "GET / HTTP/1.1" 500 101604
